// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d01e034e9290

package operations

import (
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

type AddTeamMembersRequestBody struct {
	Members []string `json:"members"`
}

func (a *AddTeamMembersRequestBody) GetMembers() []string {
	if a == nil {
		return []string{}
	}
	return a.Members
}

type AddTeamMembersRequest struct {
	ID   string                    `pathParam:"style=simple,explode=false,name=id"`
	Body AddTeamMembersRequestBody `request:"mediaType=application/json"`
}

func (a *AddTeamMembersRequest) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AddTeamMembersRequest) GetBody() AddTeamMembersRequestBody {
	if a == nil {
		return AddTeamMembersRequestBody{}
	}
	return a.Body
}

type AddTeamMembersResponseBody struct {
	Status float64 `json:"status"`
}

func (a *AddTeamMembersResponseBody) GetStatus() float64 {
	if a == nil {
		return 0.0
	}
	return a.Status
}

type AddTeamMembersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *AddTeamMembersResponseBody
}

func (a AddTeamMembersResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AddTeamMembersResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AddTeamMembersResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AddTeamMembersResponse) GetObject() *AddTeamMembersResponseBody {
	if a == nil {
		return nil
	}
	return a.Object
}
