// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

type DeleteSDKConnectionRequest struct {
	// The id of the requested resource
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteSDKConnectionRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteSDKConnectionResponseBody struct {
	DeletedID string `json:"deletedId"`
}

func (d *DeleteSDKConnectionResponseBody) GetDeletedID() string {
	if d == nil {
		return ""
	}
	return d.DeletedID
}

type DeleteSDKConnectionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *DeleteSDKConnectionResponseBody
}

func (d DeleteSDKConnectionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteSDKConnectionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteSDKConnectionResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteSDKConnectionResponse) GetObject() *DeleteSDKConnectionResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}
