// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/growthbook/cli/v2/internal/sdk/models/components"
	"github.com/growthbook/cli/v2/internal/sdk/sdkinternal/utils"
)

type DeleteConfigRevisionPropertyRequest struct {
	Key     string `pathParam:"style=simple,explode=false,name=key"`
	Version string `pathParam:"style=simple,explode=false,name=version"`
	// Name of the property to remove.
	Property string `queryParam:"style=form,explode=true,name=property"`
}

func (d *DeleteConfigRevisionPropertyRequest) GetKey() string {
	if d == nil {
		return ""
	}
	return d.Key
}

func (d *DeleteConfigRevisionPropertyRequest) GetVersion() string {
	if d == nil {
		return ""
	}
	return d.Version
}

func (d *DeleteConfigRevisionPropertyRequest) GetProperty() string {
	if d == nil {
		return ""
	}
	return d.Property
}

// DeleteConfigRevisionPropertyResponseBody - Resource deleted
type DeleteConfigRevisionPropertyResponseBody struct {
	Revision components.ConfigRevision `json:"revision"`
}

func (d *DeleteConfigRevisionPropertyResponseBody) GetRevision() components.ConfigRevision {
	if d == nil {
		return components.ConfigRevision{}
	}
	return d.Revision
}

type DeleteConfigRevisionPropertyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Resource deleted
	Object *DeleteConfigRevisionPropertyResponseBody
}

func (d DeleteConfigRevisionPropertyResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteConfigRevisionPropertyResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteConfigRevisionPropertyResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteConfigRevisionPropertyResponse) GetObject() *DeleteConfigRevisionPropertyResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}
