// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

type DeleteFeatureRevisionRuleV2RequestBody struct {
	// Title for a newly created draft. Only used when version is "new"; ignored for existing revisions.
	RevisionTitle *string `json:"revisionTitle,omitzero"`
	// Comment for a newly created draft. Only used when version is "new"; ignored for existing revisions.
	RevisionComment *string `json:"revisionComment,omitzero"`
}

func (d *DeleteFeatureRevisionRuleV2RequestBody) GetRevisionTitle() *string {
	if d == nil {
		return nil
	}
	return d.RevisionTitle
}

func (d *DeleteFeatureRevisionRuleV2RequestBody) GetRevisionComment() *string {
	if d == nil {
		return nil
	}
	return d.RevisionComment
}

// #region class-body-deletefeaturerevisionrulev2requestbody
// #endregion class-body-deletefeaturerevisionrulev2requestbody

type DeleteFeatureRevisionRuleV2Request struct {
	ID      string                                 `pathParam:"style=simple,explode=false,name=id"`
	Version string                                 `pathParam:"style=simple,explode=false,name=version"`
	RuleID  string                                 `pathParam:"style=simple,explode=false,name=ruleId"`
	Body    DeleteFeatureRevisionRuleV2RequestBody `request:"mediaType=application/json"`
}

func (d *DeleteFeatureRevisionRuleV2Request) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DeleteFeatureRevisionRuleV2Request) GetVersion() string {
	if d == nil {
		return ""
	}
	return d.Version
}

func (d *DeleteFeatureRevisionRuleV2Request) GetRuleID() string {
	if d == nil {
		return ""
	}
	return d.RuleID
}

func (d *DeleteFeatureRevisionRuleV2Request) GetBody() DeleteFeatureRevisionRuleV2RequestBody {
	if d == nil {
		return DeleteFeatureRevisionRuleV2RequestBody{}
	}
	return d.Body
}

// #region class-body-deletefeaturerevisionrulev2request
// #endregion class-body-deletefeaturerevisionrulev2request

// DeleteFeatureRevisionRuleV2ResponseBody - Resource deleted
type DeleteFeatureRevisionRuleV2ResponseBody struct {
	Revision components.FeatureRevisionV2 `json:"revision"`
}

func (d *DeleteFeatureRevisionRuleV2ResponseBody) GetRevision() components.FeatureRevisionV2 {
	if d == nil {
		return components.FeatureRevisionV2{}
	}
	return d.Revision
}

// #region class-body-deletefeaturerevisionrulev2responsebody
// #endregion class-body-deletefeaturerevisionrulev2responsebody

type DeleteFeatureRevisionRuleV2Response struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Resource deleted
	Object *DeleteFeatureRevisionRuleV2ResponseBody
}

func (d DeleteFeatureRevisionRuleV2Response) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteFeatureRevisionRuleV2Response) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteFeatureRevisionRuleV2Response) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteFeatureRevisionRuleV2Response) GetObject() *DeleteFeatureRevisionRuleV2ResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}

// #region class-body-deletefeaturerevisionrulev2response
// #endregion class-body-deletefeaturerevisionrulev2response
