// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

type GetConstantReferencesRequest struct {
	// The key of the constant
	Key string `pathParam:"style=simple,explode=false,name=key"`
}

func (g *GetConstantReferencesRequest) GetKey() string {
	if g == nil {
		return ""
	}
	return g.Key
}

type GetConstantReferencesFeature struct {
	ID      string  `json:"id"`
	Name    *string `json:"name,omitzero"`
	Project *string `json:"project,omitzero"`
}

func (g *GetConstantReferencesFeature) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetConstantReferencesFeature) GetName() *string {
	if g == nil {
		return nil
	}
	return g.Name
}

func (g *GetConstantReferencesFeature) GetProject() *string {
	if g == nil {
		return nil
	}
	return g.Project
}

// GetConstantReferencesResponseBody - Successful response
type GetConstantReferencesResponseBody struct {
	Features  []GetConstantReferencesFeature `json:"features"`
	Constants []components.Constants         `json:"constants"`
}

func (g *GetConstantReferencesResponseBody) GetFeatures() []GetConstantReferencesFeature {
	if g == nil {
		return []GetConstantReferencesFeature{}
	}
	return g.Features
}

func (g *GetConstantReferencesResponseBody) GetConstants() []components.Constants {
	if g == nil {
		return []components.Constants{}
	}
	return g.Constants
}

type GetConstantReferencesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	Object *GetConstantReferencesResponseBody
}

func (g GetConstantReferencesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetConstantReferencesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetConstantReferencesResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetConstantReferencesResponse) GetObject() *GetConstantReferencesResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
