// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

type GetFeatureStaleV2Request struct {
	// Comma-separated list of feature IDs (URL-encoded if needed). Example: `my_feature,another_feature`
	//
	Ids string `queryParam:"style=form,explode=true,name=ids"`
}

func (g *GetFeatureStaleV2Request) GetIds() string {
	if g == nil {
		return ""
	}
	return g.Ids
}

// #region class-body-getfeaturestalev2request
// #endregion class-body-getfeaturestalev2request

// GetFeatureStaleV2ResponseBody - Successful response
type GetFeatureStaleV2ResponseBody struct {
	// Map of feature ID to stale status. Only requested features that were found and readable are included.
	Features map[string]components.Features `json:"features"`
}

func (g *GetFeatureStaleV2ResponseBody) GetFeatures() map[string]components.Features {
	if g == nil {
		return map[string]components.Features{}
	}
	return g.Features
}

// #region class-body-getfeaturestalev2responsebody
// #endregion class-body-getfeaturestalev2responsebody

type GetFeatureStaleV2Response struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	Object *GetFeatureStaleV2ResponseBody
}

func (g GetFeatureStaleV2Response) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetFeatureStaleV2Response) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetFeatureStaleV2Response) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetFeatureStaleV2Response) GetObject() *GetFeatureStaleV2ResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}

// #region class-body-getfeaturestalev2response
// #endregion class-body-getfeaturestalev2response
