// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

type GetFeatureRevisionV2Request struct {
	ID      string `pathParam:"style=simple,explode=false,name=id"`
	Version string `pathParam:"style=simple,explode=false,name=version"`
}

func (g *GetFeatureRevisionV2Request) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetFeatureRevisionV2Request) GetVersion() string {
	if g == nil {
		return ""
	}
	return g.Version
}

// #region class-body-getfeaturerevisionv2request
// #endregion class-body-getfeaturerevisionv2request

type GetFeatureRevisionV2ResponseBody struct {
	Revision components.FeatureRevisionV2 `json:"revision"`
}

func (g *GetFeatureRevisionV2ResponseBody) GetRevision() components.FeatureRevisionV2 {
	if g == nil {
		return components.FeatureRevisionV2{}
	}
	return g.Revision
}

// #region class-body-getfeaturerevisionv2responsebody
// #endregion class-body-getfeaturerevisionv2responsebody

type GetFeatureRevisionV2Response struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *GetFeatureRevisionV2ResponseBody
}

func (g GetFeatureRevisionV2Response) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetFeatureRevisionV2Response) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetFeatureRevisionV2Response) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetFeatureRevisionV2Response) GetObject() *GetFeatureRevisionV2ResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}

// #region class-body-getfeaturerevisionv2response
// #endregion class-body-getfeaturerevisionv2response
