// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

type GetFeatureRevisionLogV2Request struct {
	ID      string `pathParam:"style=simple,explode=false,name=id"`
	Version string `pathParam:"style=simple,explode=false,name=version"`
}

func (g *GetFeatureRevisionLogV2Request) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetFeatureRevisionLogV2Request) GetVersion() string {
	if g == nil {
		return ""
	}
	return g.Version
}

// #region class-body-getfeaturerevisionlogv2request
// #endregion class-body-getfeaturerevisionlogv2request

// GetFeatureRevisionLogV2ResponseBody - Successful response
type GetFeatureRevisionLogV2ResponseBody struct {
	Log []components.Log `json:"log"`
}

func (g *GetFeatureRevisionLogV2ResponseBody) GetLog() []components.Log {
	if g == nil {
		return []components.Log{}
	}
	return g.Log
}

// #region class-body-getfeaturerevisionlogv2responsebody
// #endregion class-body-getfeaturerevisionlogv2responsebody

type GetFeatureRevisionLogV2Response struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	Object *GetFeatureRevisionLogV2ResponseBody
}

func (g GetFeatureRevisionLogV2Response) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetFeatureRevisionLogV2Response) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetFeatureRevisionLogV2Response) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetFeatureRevisionLogV2Response) GetObject() *GetFeatureRevisionLogV2ResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}

// #region class-body-getfeaturerevisionlogv2response
// #endregion class-body-getfeaturerevisionlogv2response
