// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

type GetMetricGroupRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetMetricGroupRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetMetricGroupResponseBody struct {
	MetricGroup components.MetricGroup `json:"metricGroup"`
}

func (g *GetMetricGroupResponseBody) GetMetricGroup() components.MetricGroup {
	if g == nil {
		return components.MetricGroup{}
	}
	return g.MetricGroup
}

type GetMetricGroupResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *GetMetricGroupResponseBody
}

func (g GetMetricGroupResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMetricGroupResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMetricGroupResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetMetricGroupResponse) GetObject() *GetMetricGroupResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
