// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/growthbook/cli/internal/sdk/models/components"
)

type GetSDKPayloadRequest struct {
	Key string `pathParam:"style=simple,explode=false,name=key"`
}

func (g *GetSDKPayloadRequest) GetKey() string {
	if g == nil {
		return ""
	}
	return g.Key
}

type GetSDKPayloadResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	Any any
}

func (g *GetSDKPayloadResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSDKPayloadResponse) GetAny() any {
	if g == nil {
		return nil
	}
	return g.Any
}
