// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7269de7f26f5

package operations

import (
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

type GetSavedGroupRevisionsRequest struct {
	SavedGroupID string `pathParam:"style=simple,explode=false,name=savedGroupId"`
	// The number of items to return
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// How many items to skip (use in conjunction with limit for pagination)
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
	// If true, return all matching items and ignore limit/offset.
	// Self-hosted only. Has no effect unless API_ALLOW_SKIP_PAGINATION is set to true or 1.
	SkipPagination any `queryParam:"style=form,explode=true,name=skipPagination"`
	// Filter by revision status. Accepts a comma-separated list, or the literal `open` for non-merged/non-discarded revisions.
	Status *string `queryParam:"style=form,explode=true,name=status"`
	Author *string `queryParam:"style=form,explode=true,name=author"`
	// If true, return only revisions authored by the calling user. Requires a user-scoped API key. Mutually exclusive with `author`.
	Mine any `queryParam:"style=form,explode=true,name=mine"`
}

func (g GetSavedGroupRevisionsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSavedGroupRevisionsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetSavedGroupRevisionsRequest) GetSavedGroupID() string {
	if g == nil {
		return ""
	}
	return g.SavedGroupID
}

func (g *GetSavedGroupRevisionsRequest) GetLimit() *int64 {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GetSavedGroupRevisionsRequest) GetOffset() *int64 {
	if g == nil {
		return nil
	}
	return g.Offset
}

func (g *GetSavedGroupRevisionsRequest) GetSkipPagination() any {
	if g == nil {
		return nil
	}
	return g.SkipPagination
}

func (g *GetSavedGroupRevisionsRequest) GetStatus() *string {
	if g == nil {
		return nil
	}
	return g.Status
}

func (g *GetSavedGroupRevisionsRequest) GetAuthor() *string {
	if g == nil {
		return nil
	}
	return g.Author
}

func (g *GetSavedGroupRevisionsRequest) GetMine() any {
	if g == nil {
		return nil
	}
	return g.Mine
}

type GetSavedGroupRevisionsResponseBody struct {
	Revisions  []components.SavedGroupRevision `json:"revisions"`
	Limit      int64                           `json:"limit"`
	Offset     int64                           `json:"offset"`
	Count      int64                           `json:"count"`
	Total      int64                           `json:"total"`
	HasMore    bool                            `json:"hasMore"`
	NextOffset *int64                          `json:"nextOffset"`
}

func (g *GetSavedGroupRevisionsResponseBody) GetRevisions() []components.SavedGroupRevision {
	if g == nil {
		return []components.SavedGroupRevision{}
	}
	return g.Revisions
}

func (g *GetSavedGroupRevisionsResponseBody) GetLimit() int64 {
	if g == nil {
		return 0
	}
	return g.Limit
}

func (g *GetSavedGroupRevisionsResponseBody) GetOffset() int64 {
	if g == nil {
		return 0
	}
	return g.Offset
}

func (g *GetSavedGroupRevisionsResponseBody) GetCount() int64 {
	if g == nil {
		return 0
	}
	return g.Count
}

func (g *GetSavedGroupRevisionsResponseBody) GetTotal() int64 {
	if g == nil {
		return 0
	}
	return g.Total
}

func (g *GetSavedGroupRevisionsResponseBody) GetHasMore() bool {
	if g == nil {
		return false
	}
	return g.HasMore
}

func (g *GetSavedGroupRevisionsResponseBody) GetNextOffset() *int64 {
	if g == nil {
		return nil
	}
	return g.NextOffset
}

type GetSavedGroupRevisionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *GetSavedGroupRevisionsResponseBody
}

func (g GetSavedGroupRevisionsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSavedGroupRevisionsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetSavedGroupRevisionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSavedGroupRevisionsResponse) GetObject() *GetSavedGroupRevisionsResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
