// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

type ListOrganizationsRequest struct {
	// Search string to search organization names, owner emails, and external ids by
	Search *string `queryParam:"style=form,explode=true,name=search"`
	// The number of items to return
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// How many items to skip (use in conjunction with limit for pagination)
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
}

func (l ListOrganizationsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListOrganizationsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListOrganizationsRequest) GetSearch() *string {
	if l == nil {
		return nil
	}
	return l.Search
}

func (l *ListOrganizationsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListOrganizationsRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

// ListOrganizationsResponseBody - Successful response
type ListOrganizationsResponseBody struct {
	Organizations []components.Organization `json:"organizations"`
	Limit         int64                     `json:"limit"`
	Offset        int64                     `json:"offset"`
	Count         int64                     `json:"count"`
	Total         int64                     `json:"total"`
	HasMore       bool                      `json:"hasMore"`
	NextOffset    *int64                    `json:"nextOffset"`
}

func (l *ListOrganizationsResponseBody) GetOrganizations() []components.Organization {
	if l == nil {
		return []components.Organization{}
	}
	return l.Organizations
}

func (l *ListOrganizationsResponseBody) GetLimit() int64 {
	if l == nil {
		return 0
	}
	return l.Limit
}

func (l *ListOrganizationsResponseBody) GetOffset() int64 {
	if l == nil {
		return 0
	}
	return l.Offset
}

func (l *ListOrganizationsResponseBody) GetCount() int64 {
	if l == nil {
		return 0
	}
	return l.Count
}

func (l *ListOrganizationsResponseBody) GetTotal() int64 {
	if l == nil {
		return 0
	}
	return l.Total
}

func (l *ListOrganizationsResponseBody) GetHasMore() bool {
	if l == nil {
		return false
	}
	return l.HasMore
}

func (l *ListOrganizationsResponseBody) GetNextOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.NextOffset
}

type ListOrganizationsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	Object *ListOrganizationsResponseBody
}

func (l ListOrganizationsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListOrganizationsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListOrganizationsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListOrganizationsResponse) GetObject() *ListOrganizationsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
