// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

type ListConstantRevisionsRequest struct {
	// The number of items to return
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// How many items to skip (use in conjunction with limit for pagination)
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
	// If true, return all matching items and ignore limit/offset.
	// Self-hosted only. Has no effect unless API_ALLOW_SKIP_PAGINATION is set to true or 1.
	SkipPagination any `queryParam:"style=form,explode=true,name=skipPagination"`
	// Restrict results to revisions for a single constant (by its key). When omitted, returns revisions across every constant the caller can read.
	Key *string `queryParam:"style=form,explode=true,name=key"`
	// Filter by revision status. Accepts a comma-separated list, or the literal `open` for non-merged/non-discarded revisions.
	Status *string `queryParam:"style=form,explode=true,name=status"`
	Author *string `queryParam:"style=form,explode=true,name=author"`
	// If true, return only revisions authored by the calling user. Requires a user-scoped API key. Mutually exclusive with `author`.
	Mine any `queryParam:"style=form,explode=true,name=mine"`
}

func (l ListConstantRevisionsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListConstantRevisionsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListConstantRevisionsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListConstantRevisionsRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListConstantRevisionsRequest) GetSkipPagination() any {
	if l == nil {
		return nil
	}
	return l.SkipPagination
}

func (l *ListConstantRevisionsRequest) GetKey() *string {
	if l == nil {
		return nil
	}
	return l.Key
}

func (l *ListConstantRevisionsRequest) GetStatus() *string {
	if l == nil {
		return nil
	}
	return l.Status
}

func (l *ListConstantRevisionsRequest) GetAuthor() *string {
	if l == nil {
		return nil
	}
	return l.Author
}

func (l *ListConstantRevisionsRequest) GetMine() any {
	if l == nil {
		return nil
	}
	return l.Mine
}

// ListConstantRevisionsResponseBody - Successful response
type ListConstantRevisionsResponseBody struct {
	Revisions  []components.ConstantRevision `json:"revisions"`
	Limit      int64                         `json:"limit"`
	Offset     int64                         `json:"offset"`
	Count      int64                         `json:"count"`
	Total      int64                         `json:"total"`
	HasMore    bool                          `json:"hasMore"`
	NextOffset *int64                        `json:"nextOffset"`
}

func (l *ListConstantRevisionsResponseBody) GetRevisions() []components.ConstantRevision {
	if l == nil {
		return []components.ConstantRevision{}
	}
	return l.Revisions
}

func (l *ListConstantRevisionsResponseBody) GetLimit() int64 {
	if l == nil {
		return 0
	}
	return l.Limit
}

func (l *ListConstantRevisionsResponseBody) GetOffset() int64 {
	if l == nil {
		return 0
	}
	return l.Offset
}

func (l *ListConstantRevisionsResponseBody) GetCount() int64 {
	if l == nil {
		return 0
	}
	return l.Count
}

func (l *ListConstantRevisionsResponseBody) GetTotal() int64 {
	if l == nil {
		return 0
	}
	return l.Total
}

func (l *ListConstantRevisionsResponseBody) GetHasMore() bool {
	if l == nil {
		return false
	}
	return l.HasMore
}

func (l *ListConstantRevisionsResponseBody) GetNextOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.NextOffset
}

type ListConstantRevisionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	Object *ListConstantRevisionsResponseBody

	Next func() (*ListConstantRevisionsResponse, error)
}

func (l ListConstantRevisionsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListConstantRevisionsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListConstantRevisionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListConstantRevisionsResponse) GetObject() *ListConstantRevisionsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
