// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

type ListDimensionsRequest struct {
	// The number of items to return
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// How many items to skip (use in conjunction with limit for pagination)
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
	// Filter by Data Source
	DatasourceID *string `queryParam:"style=form,explode=true,name=datasourceId"`
}

func (l ListDimensionsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListDimensionsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListDimensionsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListDimensionsRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListDimensionsRequest) GetDatasourceID() *string {
	if l == nil {
		return nil
	}
	return l.DatasourceID
}

// ListDimensionsResponseBody - Successful response
type ListDimensionsResponseBody struct {
	Dimensions []components.Dimension `json:"dimensions"`
	Limit      int64                  `json:"limit"`
	Offset     int64                  `json:"offset"`
	Count      int64                  `json:"count"`
	Total      int64                  `json:"total"`
	HasMore    bool                   `json:"hasMore"`
	NextOffset *int64                 `json:"nextOffset"`
}

func (l *ListDimensionsResponseBody) GetDimensions() []components.Dimension {
	if l == nil {
		return []components.Dimension{}
	}
	return l.Dimensions
}

func (l *ListDimensionsResponseBody) GetLimit() int64 {
	if l == nil {
		return 0
	}
	return l.Limit
}

func (l *ListDimensionsResponseBody) GetOffset() int64 {
	if l == nil {
		return 0
	}
	return l.Offset
}

func (l *ListDimensionsResponseBody) GetCount() int64 {
	if l == nil {
		return 0
	}
	return l.Count
}

func (l *ListDimensionsResponseBody) GetTotal() int64 {
	if l == nil {
		return 0
	}
	return l.Total
}

func (l *ListDimensionsResponseBody) GetHasMore() bool {
	if l == nil {
		return false
	}
	return l.HasMore
}

func (l *ListDimensionsResponseBody) GetNextOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.NextOffset
}

type ListDimensionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	Object *ListDimensionsResponseBody
}

func (l ListDimensionsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListDimensionsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListDimensionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListDimensionsResponse) GetObject() *ListDimensionsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
