// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

type ListFactTableFiltersRequest struct {
	// Specify a specific fact table
	FactTableID string `pathParam:"style=simple,explode=false,name=factTableId"`
	// The number of items to return
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// How many items to skip (use in conjunction with limit for pagination)
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
}

func (l ListFactTableFiltersRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListFactTableFiltersRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListFactTableFiltersRequest) GetFactTableID() string {
	if l == nil {
		return ""
	}
	return l.FactTableID
}

func (l *ListFactTableFiltersRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListFactTableFiltersRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

type ListFactTableFiltersResponseBody struct {
	FactTableFilters []components.FactTableFilter `json:"factTableFilters"`
	Limit            int64                        `json:"limit"`
	Offset           int64                        `json:"offset"`
	Count            int64                        `json:"count"`
	Total            int64                        `json:"total"`
	HasMore          bool                         `json:"hasMore"`
	NextOffset       *int64                       `json:"nextOffset"`
}

func (l *ListFactTableFiltersResponseBody) GetFactTableFilters() []components.FactTableFilter {
	if l == nil {
		return []components.FactTableFilter{}
	}
	return l.FactTableFilters
}

func (l *ListFactTableFiltersResponseBody) GetLimit() int64 {
	if l == nil {
		return 0
	}
	return l.Limit
}

func (l *ListFactTableFiltersResponseBody) GetOffset() int64 {
	if l == nil {
		return 0
	}
	return l.Offset
}

func (l *ListFactTableFiltersResponseBody) GetCount() int64 {
	if l == nil {
		return 0
	}
	return l.Count
}

func (l *ListFactTableFiltersResponseBody) GetTotal() int64 {
	if l == nil {
		return 0
	}
	return l.Total
}

func (l *ListFactTableFiltersResponseBody) GetHasMore() bool {
	if l == nil {
		return false
	}
	return l.HasMore
}

func (l *ListFactTableFiltersResponseBody) GetNextOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.NextOffset
}

type ListFactTableFiltersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *ListFactTableFiltersResponseBody
}

func (l ListFactTableFiltersResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListFactTableFiltersResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListFactTableFiltersResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListFactTableFiltersResponse) GetObject() *ListFactTableFiltersResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
