// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

// ListAttributesResponseBody - Successful response
type ListAttributesResponseBody struct {
	Attributes []components.Attribute `json:"attributes"`
}

func (l *ListAttributesResponseBody) GetAttributes() []components.Attribute {
	if l == nil {
		return []components.Attribute{}
	}
	return l.Attributes
}

type ListAttributesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	Object *ListAttributesResponseBody
}

func (l ListAttributesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAttributesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListAttributesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListAttributesResponse) GetObject() *ListAttributesResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
