// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

type ListCodeRefsRequest struct {
	// The number of items to return
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// How many items to skip (use in conjunction with limit for pagination)
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
}

func (l ListCodeRefsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListCodeRefsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListCodeRefsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListCodeRefsRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

// ListCodeRefsResponseBody - Successful response
type ListCodeRefsResponseBody struct {
	CodeRefs   []components.CodeRef `json:"codeRefs"`
	Limit      int64                `json:"limit"`
	Offset     int64                `json:"offset"`
	Count      int64                `json:"count"`
	Total      int64                `json:"total"`
	HasMore    bool                 `json:"hasMore"`
	NextOffset *int64               `json:"nextOffset"`
}

func (l *ListCodeRefsResponseBody) GetCodeRefs() []components.CodeRef {
	if l == nil {
		return []components.CodeRef{}
	}
	return l.CodeRefs
}

func (l *ListCodeRefsResponseBody) GetLimit() int64 {
	if l == nil {
		return 0
	}
	return l.Limit
}

func (l *ListCodeRefsResponseBody) GetOffset() int64 {
	if l == nil {
		return 0
	}
	return l.Offset
}

func (l *ListCodeRefsResponseBody) GetCount() int64 {
	if l == nil {
		return 0
	}
	return l.Count
}

func (l *ListCodeRefsResponseBody) GetTotal() int64 {
	if l == nil {
		return 0
	}
	return l.Total
}

func (l *ListCodeRefsResponseBody) GetHasMore() bool {
	if l == nil {
		return false
	}
	return l.HasMore
}

func (l *ListCodeRefsResponseBody) GetNextOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.NextOffset
}

type ListCodeRefsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	Object *ListCodeRefsResponseBody

	Next func() (*ListCodeRefsResponse, error)
}

func (l ListCodeRefsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListCodeRefsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListCodeRefsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListCodeRefsResponse) GetObject() *ListCodeRefsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
