// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

type ListConstantsRequest struct {
	// The number of items to return
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// How many items to skip (use in conjunction with limit for pagination)
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
}

func (l ListConstantsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListConstantsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListConstantsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListConstantsRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

// ListConstantsResponseBody - Successful response
type ListConstantsResponseBody struct {
	Constants  []components.Constant `json:"constants"`
	Limit      int64                 `json:"limit"`
	Offset     int64                 `json:"offset"`
	Count      int64                 `json:"count"`
	Total      int64                 `json:"total"`
	HasMore    bool                  `json:"hasMore"`
	NextOffset *int64                `json:"nextOffset"`
}

func (l *ListConstantsResponseBody) GetConstants() []components.Constant {
	if l == nil {
		return []components.Constant{}
	}
	return l.Constants
}

func (l *ListConstantsResponseBody) GetLimit() int64 {
	if l == nil {
		return 0
	}
	return l.Limit
}

func (l *ListConstantsResponseBody) GetOffset() int64 {
	if l == nil {
		return 0
	}
	return l.Offset
}

func (l *ListConstantsResponseBody) GetCount() int64 {
	if l == nil {
		return 0
	}
	return l.Count
}

func (l *ListConstantsResponseBody) GetTotal() int64 {
	if l == nil {
		return 0
	}
	return l.Total
}

func (l *ListConstantsResponseBody) GetHasMore() bool {
	if l == nil {
		return false
	}
	return l.HasMore
}

func (l *ListConstantsResponseBody) GetNextOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.NextOffset
}

type ListConstantsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	Object *ListConstantsResponseBody

	Next func() (*ListConstantsResponse, error)
}

func (l ListConstantsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListConstantsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListConstantsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListConstantsResponse) GetObject() *ListConstantsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
