// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 70825c791658

package operations

import (
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

type ListNamespacesRequest struct {
	// The number of items to return
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// How many items to skip (use in conjunction with limit for pagination)
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
}

func (l ListNamespacesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListNamespacesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListNamespacesRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListNamespacesRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

type ListNamespacesResponseBody struct {
	Namespaces []components.Namespace `json:"namespaces"`
	Limit      int64                  `json:"limit"`
	Offset     int64                  `json:"offset"`
	Count      int64                  `json:"count"`
	Total      int64                  `json:"total"`
	HasMore    bool                   `json:"hasMore"`
	NextOffset *int64                 `json:"nextOffset"`
}

func (l *ListNamespacesResponseBody) GetNamespaces() []components.Namespace {
	if l == nil {
		return []components.Namespace{}
	}
	return l.Namespaces
}

func (l *ListNamespacesResponseBody) GetLimit() int64 {
	if l == nil {
		return 0
	}
	return l.Limit
}

func (l *ListNamespacesResponseBody) GetOffset() int64 {
	if l == nil {
		return 0
	}
	return l.Offset
}

func (l *ListNamespacesResponseBody) GetCount() int64 {
	if l == nil {
		return 0
	}
	return l.Count
}

func (l *ListNamespacesResponseBody) GetTotal() int64 {
	if l == nil {
		return 0
	}
	return l.Total
}

func (l *ListNamespacesResponseBody) GetHasMore() bool {
	if l == nil {
		return false
	}
	return l.HasMore
}

func (l *ListNamespacesResponseBody) GetNextOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.NextOffset
}

type ListNamespacesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *ListNamespacesResponseBody
}

func (l ListNamespacesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListNamespacesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListNamespacesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListNamespacesResponse) GetObject() *ListNamespacesResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
