// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

type PostFactTableUpdateTime struct {
	Time     string `json:"time"`
	Timezone string `json:"timezone"`
}

func (p *PostFactTableUpdateTime) GetTime() string {
	if p == nil {
		return ""
	}
	return p.Time
}

func (p *PostFactTableUpdateTime) GetTimezone() string {
	if p == nil {
		return ""
	}
	return p.Timezone
}

// PostFactTableAggregatedFactTableSettings - Settings for maintaining shared daily aggregated tables (a subset of userIdTypes plus the daily update time and restate lookback window) used to speed up CUPED. Requires the data pipeline (pipeline-mode) feature.
type PostFactTableAggregatedFactTableSettings struct {
	IDTypes        []string                `json:"idTypes"`
	UpdateTime     PostFactTableUpdateTime `json:"updateTime"`
	LookbackWindow int64                   `json:"lookbackWindow"`
}

func (p *PostFactTableAggregatedFactTableSettings) GetIDTypes() []string {
	if p == nil {
		return []string{}
	}
	return p.IDTypes
}

func (p *PostFactTableAggregatedFactTableSettings) GetUpdateTime() PostFactTableUpdateTime {
	if p == nil {
		return PostFactTableUpdateTime{}
	}
	return p.UpdateTime
}

func (p *PostFactTableAggregatedFactTableSettings) GetLookbackWindow() int64 {
	if p == nil {
		return 0
	}
	return p.LookbackWindow
}

// PostFactTableManagedBy - Set this to "api" to disable editing in the GrowthBook UI
type PostFactTableManagedBy string

const (
	PostFactTableManagedByUnknown PostFactTableManagedBy = ""
	PostFactTableManagedByAPI     PostFactTableManagedBy = "api"
	PostFactTableManagedByAdmin   PostFactTableManagedBy = "admin"
)

func (e PostFactTableManagedBy) ToPointer() *PostFactTableManagedBy {
	return &e
}
func (e *PostFactTableManagedBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "":
		fallthrough
	case "api":
		fallthrough
	case "admin":
		*e = PostFactTableManagedBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostFactTableManagedBy: %v", v)
	}
}

type PostFactTableRequest struct {
	Name string `json:"name"`
	// Description of the fact table
	Description *string `json:"description,omitzero"`
	// The userId or email address of the owner. If an email address is provided, it will be used to look up the userId of the matching organization member. If an ID is provided, it will be validated as existing in the organization.
	Owner *string `json:"owner,omitzero"`
	// List of associated project ids
	Projects []string `json:"projects,omitzero"`
	// List of associated tags
	Tags []string `json:"tags,omitzero"`
	// The datasource id
	Datasource string `json:"datasource"`
	// List of identifier columns in this table. For example, "id" or "anonymous_id"
	UserIDTypes []string `json:"userIdTypes"`
	// Settings for maintaining shared daily aggregated tables (a subset of userIdTypes plus the daily update time and restate lookback window) used to speed up CUPED. Requires the data pipeline (pipeline-mode) feature.
	AggregatedFactTableSettings *PostFactTableAggregatedFactTableSettings `json:"aggregatedFactTableSettings,omitzero"`
	// The SQL query for this fact table
	SQL string `json:"sql"`
	// The event name used in SQL template variables
	EventName *string `json:"eventName,omitzero"`
	// Set this to "api" to disable editing in the GrowthBook UI
	ManagedBy *PostFactTableManagedBy `json:"managedBy,omitzero"`
}

func (p PostFactTableRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostFactTableRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostFactTableRequest) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PostFactTableRequest) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PostFactTableRequest) GetOwner() *string {
	if p == nil {
		return nil
	}
	return p.Owner
}

func (p *PostFactTableRequest) GetProjects() []string {
	if p == nil {
		return nil
	}
	return p.Projects
}

func (p *PostFactTableRequest) GetTags() []string {
	if p == nil {
		return nil
	}
	return p.Tags
}

func (p *PostFactTableRequest) GetDatasource() string {
	if p == nil {
		return ""
	}
	return p.Datasource
}

func (p *PostFactTableRequest) GetUserIDTypes() []string {
	if p == nil {
		return []string{}
	}
	return p.UserIDTypes
}

func (p *PostFactTableRequest) GetAggregatedFactTableSettings() *PostFactTableAggregatedFactTableSettings {
	if p == nil {
		return nil
	}
	return p.AggregatedFactTableSettings
}

func (p *PostFactTableRequest) GetSQL() string {
	if p == nil {
		return ""
	}
	return p.SQL
}

func (p *PostFactTableRequest) GetEventName() *string {
	if p == nil {
		return nil
	}
	return p.EventName
}

func (p *PostFactTableRequest) GetManagedBy() *PostFactTableManagedBy {
	if p == nil {
		return nil
	}
	return p.ManagedBy
}

// PostFactTableResponseBody - Resource created
type PostFactTableResponseBody struct {
	FactTable components.FactTable `json:"factTable"`
}

func (p *PostFactTableResponseBody) GetFactTable() components.FactTable {
	if p == nil {
		return components.FactTable{}
	}
	return p.FactTable
}

type PostFactTableResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Resource created
	Object *PostFactTableResponseBody
}

func (p PostFactTableResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostFactTableResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostFactTableResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostFactTableResponse) GetObject() *PostFactTableResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
