// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

// PostSegmentManagedBy - Where this Segment must be managed from. If not set (empty string), it can be managed from anywhere.
type PostSegmentManagedBy string

const (
	PostSegmentManagedByUnknown PostSegmentManagedBy = ""
	PostSegmentManagedByAPI     PostSegmentManagedBy = "api"
)

func (e PostSegmentManagedBy) ToPointer() *PostSegmentManagedBy {
	return &e
}
func (e *PostSegmentManagedBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "":
		fallthrough
	case "api":
		*e = PostSegmentManagedBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostSegmentManagedBy: %v", v)
	}
}

// PostSegmentType - GrowthBook supports two types of Segments, SQL and FACT. SQL segments are defined by a SQL query, and FACT segments are defined by a fact table and filters.
type PostSegmentType string

const (
	PostSegmentTypeSQL  PostSegmentType = "SQL"
	PostSegmentTypeFact PostSegmentType = "FACT"
)

func (e PostSegmentType) ToPointer() *PostSegmentType {
	return &e
}
func (e *PostSegmentType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "SQL":
		fallthrough
	case "FACT":
		*e = PostSegmentType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostSegmentType: %v", v)
	}
}

type PostSegmentRequest struct {
	// Name of the segment
	Name string `json:"name"`
	// The userId or email address of the owner. If an email address is provided, it will be used to look up the userId of the matching organization member. If an ID is provided, it will be validated as existing in the organization.
	Owner *string `json:"owner,omitzero"`
	// Description of the segment
	Description *string `json:"description,omitzero"`
	// ID of the datasource this segment belongs to
	DatasourceID string `json:"datasourceId"`
	// Type of identifier (user, anonymous, etc.)
	IdentifierType string `json:"identifierType"`
	// List of project IDs for projects that can access this segment
	Projects []string `json:"projects,omitzero"`
	// Where this Segment must be managed from. If not set (empty string), it can be managed from anywhere.
	ManagedBy *PostSegmentManagedBy `json:"managedBy,omitzero"`
	// GrowthBook supports two types of Segments, SQL and FACT. SQL segments are defined by a SQL query, and FACT segments are defined by a fact table and filters.
	Type PostSegmentType `json:"type"`
	// SQL query that defines the Segment. This is required for SQL segments.
	Query *string `json:"query,omitzero"`
	// ID of the fact table this segment belongs to. This is required for FACT segments.
	FactTableID *string `json:"factTableId,omitzero"`
	// Optional array of fact table filter ids that can further define the Fact Table based Segment.
	Filters []string `json:"filters,omitzero"`
}

func (p PostSegmentRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostSegmentRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostSegmentRequest) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PostSegmentRequest) GetOwner() *string {
	if p == nil {
		return nil
	}
	return p.Owner
}

func (p *PostSegmentRequest) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PostSegmentRequest) GetDatasourceID() string {
	if p == nil {
		return ""
	}
	return p.DatasourceID
}

func (p *PostSegmentRequest) GetIdentifierType() string {
	if p == nil {
		return ""
	}
	return p.IdentifierType
}

func (p *PostSegmentRequest) GetProjects() []string {
	if p == nil {
		return nil
	}
	return p.Projects
}

func (p *PostSegmentRequest) GetManagedBy() *PostSegmentManagedBy {
	if p == nil {
		return nil
	}
	return p.ManagedBy
}

func (p *PostSegmentRequest) GetType() PostSegmentType {
	if p == nil {
		return PostSegmentType("")
	}
	return p.Type
}

func (p *PostSegmentRequest) GetQuery() *string {
	if p == nil {
		return nil
	}
	return p.Query
}

func (p *PostSegmentRequest) GetFactTableID() *string {
	if p == nil {
		return nil
	}
	return p.FactTableID
}

func (p *PostSegmentRequest) GetFilters() []string {
	if p == nil {
		return nil
	}
	return p.Filters
}

type PostSegmentResponseBody struct {
	Segment components.Segment `json:"segment"`
}

func (p *PostSegmentResponseBody) GetSegment() components.Segment {
	if p == nil {
		return components.Segment{}
	}
	return p.Segment
}

type PostSegmentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *PostSegmentResponseBody
}

func (p PostSegmentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostSegmentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostSegmentResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostSegmentResponse) GetObject() *PostSegmentResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
