// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

type PostFeatureRevisionDiscardRequestBody struct {
}

type PostFeatureRevisionDiscardRequest struct {
	ID      string                                `pathParam:"style=simple,explode=false,name=id"`
	Version string                                `pathParam:"style=simple,explode=false,name=version"`
	Body    PostFeatureRevisionDiscardRequestBody `request:"mediaType=application/json"`
}

func (p *PostFeatureRevisionDiscardRequest) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PostFeatureRevisionDiscardRequest) GetVersion() string {
	if p == nil {
		return ""
	}
	return p.Version
}

func (p *PostFeatureRevisionDiscardRequest) GetBody() PostFeatureRevisionDiscardRequestBody {
	if p == nil {
		return PostFeatureRevisionDiscardRequestBody{}
	}
	return p.Body
}

type PostFeatureRevisionDiscardResponseBody struct {
	Revision components.FeatureRevision `json:"revision"`
}

func (p *PostFeatureRevisionDiscardResponseBody) GetRevision() components.FeatureRevision {
	if p == nil {
		return components.FeatureRevision{}
	}
	return p.Revision
}

type PostFeatureRevisionDiscardResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *PostFeatureRevisionDiscardResponseBody
}

func (p PostFeatureRevisionDiscardResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostFeatureRevisionDiscardResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostFeatureRevisionDiscardResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostFeatureRevisionDiscardResponse) GetObject() *PostFeatureRevisionDiscardResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
