// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

type PostFeatureRevisionRecallReviewV2RequestBody struct {
}

// #region class-body-postfeaturerevisionrecallreviewv2requestbody
// #endregion class-body-postfeaturerevisionrecallreviewv2requestbody

type PostFeatureRevisionRecallReviewV2Request struct {
	ID      string                                       `pathParam:"style=simple,explode=false,name=id"`
	Version string                                       `pathParam:"style=simple,explode=false,name=version"`
	Body    PostFeatureRevisionRecallReviewV2RequestBody `request:"mediaType=application/json"`
}

func (p *PostFeatureRevisionRecallReviewV2Request) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PostFeatureRevisionRecallReviewV2Request) GetVersion() string {
	if p == nil {
		return ""
	}
	return p.Version
}

func (p *PostFeatureRevisionRecallReviewV2Request) GetBody() PostFeatureRevisionRecallReviewV2RequestBody {
	if p == nil {
		return PostFeatureRevisionRecallReviewV2RequestBody{}
	}
	return p.Body
}

// #region class-body-postfeaturerevisionrecallreviewv2request
// #endregion class-body-postfeaturerevisionrecallreviewv2request

// PostFeatureRevisionRecallReviewV2ResponseBody - Resource created
type PostFeatureRevisionRecallReviewV2ResponseBody struct {
	Revision components.FeatureRevisionV2 `json:"revision"`
}

func (p *PostFeatureRevisionRecallReviewV2ResponseBody) GetRevision() components.FeatureRevisionV2 {
	if p == nil {
		return components.FeatureRevisionV2{}
	}
	return p.Revision
}

// #region class-body-postfeaturerevisionrecallreviewv2responsebody
// #endregion class-body-postfeaturerevisionrecallreviewv2responsebody

type PostFeatureRevisionRecallReviewV2Response struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Resource created
	Object *PostFeatureRevisionRecallReviewV2ResponseBody
}

func (p PostFeatureRevisionRecallReviewV2Response) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostFeatureRevisionRecallReviewV2Response) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostFeatureRevisionRecallReviewV2Response) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostFeatureRevisionRecallReviewV2Response) GetObject() *PostFeatureRevisionRecallReviewV2ResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}

// #region class-body-postfeaturerevisionrecallreviewv2response
// #endregion class-body-postfeaturerevisionrecallreviewv2response
