// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

type PostConfigRevisionRequestReviewRequestBody struct {
	AutoPublishOnApproval *bool `json:"autoPublishOnApproval,omitzero"`
}

func (p *PostConfigRevisionRequestReviewRequestBody) GetAutoPublishOnApproval() *bool {
	if p == nil {
		return nil
	}
	return p.AutoPublishOnApproval
}

type PostConfigRevisionRequestReviewRequest struct {
	Key     string                                     `pathParam:"style=simple,explode=false,name=key"`
	Version string                                     `pathParam:"style=simple,explode=false,name=version"`
	Body    PostConfigRevisionRequestReviewRequestBody `request:"mediaType=application/json"`
}

func (p *PostConfigRevisionRequestReviewRequest) GetKey() string {
	if p == nil {
		return ""
	}
	return p.Key
}

func (p *PostConfigRevisionRequestReviewRequest) GetVersion() string {
	if p == nil {
		return ""
	}
	return p.Version
}

func (p *PostConfigRevisionRequestReviewRequest) GetBody() PostConfigRevisionRequestReviewRequestBody {
	if p == nil {
		return PostConfigRevisionRequestReviewRequestBody{}
	}
	return p.Body
}

// PostConfigRevisionRequestReviewResponseBody - Resource created
type PostConfigRevisionRequestReviewResponseBody struct {
	Revision components.ConfigRevision `json:"revision"`
}

func (p *PostConfigRevisionRequestReviewResponseBody) GetRevision() components.ConfigRevision {
	if p == nil {
		return components.ConfigRevision{}
	}
	return p.Revision
}

type PostConfigRevisionRequestReviewResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Resource created
	Object *PostConfigRevisionRequestReviewResponseBody
}

func (p PostConfigRevisionRequestReviewResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostConfigRevisionRequestReviewResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostConfigRevisionRequestReviewResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostConfigRevisionRequestReviewResponse) GetObject() *PostConfigRevisionRequestReviewResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
