// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3391ad305b24

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

type PostNamespaceStatus string

const (
	PostNamespaceStatusActive   PostNamespaceStatus = "active"
	PostNamespaceStatusInactive PostNamespaceStatus = "inactive"
)

func (e PostNamespaceStatus) ToPointer() *PostNamespaceStatus {
	return &e
}
func (e *PostNamespaceStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "active":
		fallthrough
	case "inactive":
		*e = PostNamespaceStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostNamespaceStatus: %v", v)
	}
}

// PostNamespaceFormat - Namespace format. Defaults to 'multiRange', which supports multiple ranges per experiment and a configurable hash attribute.
type PostNamespaceFormat string

const (
	PostNamespaceFormatLegacy     PostNamespaceFormat = "legacy"
	PostNamespaceFormatMultiRange PostNamespaceFormat = "multiRange"
)

func (e PostNamespaceFormat) ToPointer() *PostNamespaceFormat {
	return &e
}
func (e *PostNamespaceFormat) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "legacy":
		fallthrough
	case "multiRange":
		*e = PostNamespaceFormat(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostNamespaceFormat: %v", v)
	}
}

type PostNamespaceRequest struct {
	// Human-readable display name. Must be unique within the organization.
	DisplayName string               `json:"displayName"`
	Description *string              `json:"description,omitzero"`
	Status      *PostNamespaceStatus `json:"status,omitzero"`
	// Namespace format. Defaults to 'multiRange', which supports multiple ranges per experiment and a configurable hash attribute.
	Format *PostNamespaceFormat `json:"format,omitzero"`
	// Required when format is 'multiRange'. The user attribute (e.g. 'id', 'device_id') used to assign users to namespace buckets.
	HashAttribute *string `json:"hashAttribute,omitzero"`
}

func (p *PostNamespaceRequest) GetDisplayName() string {
	if p == nil {
		return ""
	}
	return p.DisplayName
}

func (p *PostNamespaceRequest) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PostNamespaceRequest) GetStatus() *PostNamespaceStatus {
	if p == nil {
		return nil
	}
	return p.Status
}

func (p *PostNamespaceRequest) GetFormat() *PostNamespaceFormat {
	if p == nil {
		return nil
	}
	return p.Format
}

func (p *PostNamespaceRequest) GetHashAttribute() *string {
	if p == nil {
		return nil
	}
	return p.HashAttribute
}

type PostNamespaceResponseBody struct {
	Namespace components.Namespace `json:"namespace"`
}

func (p *PostNamespaceResponseBody) GetNamespace() components.Namespace {
	if p == nil {
		return components.Namespace{}
	}
	return p.Namespace
}

type PostNamespaceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *PostNamespaceResponseBody
}

func (p PostNamespaceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostNamespaceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostNamespaceResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostNamespaceResponse) GetObject() *PostNamespaceResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
