// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a4a6e994f496

package operations

import (
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

// PostProjectSettings - Project stats settings that, when set, override the organization settings.
type PostProjectSettings struct {
	// Stats engine.
	StatsEngine *string `json:"statsEngine,omitzero"`
	// Bayesian chance-to-win threshold (stored as decimal, e.g. 0.95).
	ConfidenceLevel *float64 `json:"confidenceLevel,omitzero"`
	// Frequentist p-value threshold (e.g. 0.05).
	PValueThreshold *float64 `json:"pValueThreshold,omitzero"`
}

func (p *PostProjectSettings) GetStatsEngine() *string {
	if p == nil {
		return nil
	}
	return p.StatsEngine
}

func (p *PostProjectSettings) GetConfidenceLevel() *float64 {
	if p == nil {
		return nil
	}
	return p.ConfidenceLevel
}

func (p *PostProjectSettings) GetPValueThreshold() *float64 {
	if p == nil {
		return nil
	}
	return p.PValueThreshold
}

type PostProjectRequest struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitzero"`
	// URL-safe slug (lowercase letters, numbers, dashes). Auto-generated from name if not provided.
	PublicID *string `json:"publicId,omitzero"`
	// Project stats settings that, when set, override the organization settings.
	Settings *PostProjectSettings `json:"settings,omitzero"`
}

func (p PostProjectRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostProjectRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostProjectRequest) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PostProjectRequest) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PostProjectRequest) GetPublicID() *string {
	if p == nil {
		return nil
	}
	return p.PublicID
}

func (p *PostProjectRequest) GetSettings() *PostProjectSettings {
	if p == nil {
		return nil
	}
	return p.Settings
}

type PostProjectResponseBody struct {
	Project components.Project `json:"project"`
}

func (p *PostProjectResponseBody) GetProject() components.Project {
	if p == nil {
		return components.Project{}
	}
	return p.Project
}

type PostProjectResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *PostProjectResponseBody
}

func (p PostProjectResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostProjectResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostProjectResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostProjectResponse) GetObject() *PostProjectResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
