// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

type PutConfigRevisionProjectionRequestBody struct {
	RevisionTitle   *string `json:"revisionTitle,omitzero"`
	RevisionComment *string `json:"revisionComment,omitzero"`
	// Identifier of the consuming codebase/service this projection belongs to.
	Source string                        `json:"source"`
	Schema components.ConfigSchemaSource `json:"schema"`
	// Whether the resulting object schema permits extra keys (family extensibility).
	AdditionalProperties *bool `json:"additionalProperties,omitzero"`
}

func (p *PutConfigRevisionProjectionRequestBody) GetRevisionTitle() *string {
	if p == nil {
		return nil
	}
	return p.RevisionTitle
}

func (p *PutConfigRevisionProjectionRequestBody) GetRevisionComment() *string {
	if p == nil {
		return nil
	}
	return p.RevisionComment
}

func (p *PutConfigRevisionProjectionRequestBody) GetSource() string {
	if p == nil {
		return ""
	}
	return p.Source
}

func (p *PutConfigRevisionProjectionRequestBody) GetSchema() components.ConfigSchemaSource {
	if p == nil {
		return components.ConfigSchemaSource{}
	}
	return p.Schema
}

func (p *PutConfigRevisionProjectionRequestBody) GetSchemaJSONSchema() *components.ConfigSchemaSourceJSONSchema {
	return p.GetSchema().ConfigSchemaSourceJSONSchema
}

func (p *PutConfigRevisionProjectionRequestBody) GetSchemaTypescript() *components.ConfigSchemaSourceTypescript {
	return p.GetSchema().ConfigSchemaSourceTypescript
}

func (p *PutConfigRevisionProjectionRequestBody) GetSchemaProtobuf() *components.ConfigSchemaSourceProtobuf {
	return p.GetSchema().ConfigSchemaSourceProtobuf
}

func (p *PutConfigRevisionProjectionRequestBody) GetSchemaPython() *components.ConfigSchemaSourcePython {
	return p.GetSchema().ConfigSchemaSourcePython
}

func (p *PutConfigRevisionProjectionRequestBody) GetSchemaGo() *components.ConfigSchemaSourceGo {
	return p.GetSchema().ConfigSchemaSourceGo
}

func (p *PutConfigRevisionProjectionRequestBody) GetSchemaRust() *components.ConfigSchemaSourceRust {
	return p.GetSchema().ConfigSchemaSourceRust
}

func (p *PutConfigRevisionProjectionRequestBody) GetAdditionalProperties() *bool {
	if p == nil {
		return nil
	}
	return p.AdditionalProperties
}

type PutConfigRevisionProjectionRequest struct {
	Key     string `pathParam:"style=simple,explode=false,name=key"`
	Version string `pathParam:"style=simple,explode=false,name=version"`
	// Skip JSON-schema validation of the value(s) being written. Only honored for callers with org-wide bypass authority (the `bypassApprovalChecks` permission on all projects); ignored otherwise. Validation is enforced by default.
	SkipSchemaValidation *bool `queryParam:"style=form,explode=true,name=skipSchemaValidation"`
	// Proceed despite soft validation warnings — e.g. publishing values that don't match the schema when the org has `blockPublishOnSchemaError` disabled (warn mode).
	IgnoreWarnings *bool                                  `queryParam:"style=form,explode=true,name=ignoreWarnings"`
	Body           PutConfigRevisionProjectionRequestBody `request:"mediaType=application/json"`
}

func (p *PutConfigRevisionProjectionRequest) GetKey() string {
	if p == nil {
		return ""
	}
	return p.Key
}

func (p *PutConfigRevisionProjectionRequest) GetVersion() string {
	if p == nil {
		return ""
	}
	return p.Version
}

func (p *PutConfigRevisionProjectionRequest) GetSkipSchemaValidation() *bool {
	if p == nil {
		return nil
	}
	return p.SkipSchemaValidation
}

func (p *PutConfigRevisionProjectionRequest) GetIgnoreWarnings() *bool {
	if p == nil {
		return nil
	}
	return p.IgnoreWarnings
}

func (p *PutConfigRevisionProjectionRequest) GetBody() PutConfigRevisionProjectionRequestBody {
	if p == nil {
		return PutConfigRevisionProjectionRequestBody{}
	}
	return p.Body
}

// PutConfigRevisionProjectionResponseBody - Resource updated
type PutConfigRevisionProjectionResponseBody struct {
	Revision components.ConfigRevision        `json:"revision"`
	Warnings []components.ConfigSchemaWarning `json:"warnings,omitzero"`
}

func (p PutConfigRevisionProjectionResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PutConfigRevisionProjectionResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PutConfigRevisionProjectionResponseBody) GetRevision() components.ConfigRevision {
	if p == nil {
		return components.ConfigRevision{}
	}
	return p.Revision
}

func (p *PutConfigRevisionProjectionResponseBody) GetWarnings() []components.ConfigSchemaWarning {
	if p == nil {
		return nil
	}
	return p.Warnings
}

type PutConfigRevisionProjectionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Resource updated
	Object *PutConfigRevisionProjectionResponseBody
}

func (p PutConfigRevisionProjectionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PutConfigRevisionProjectionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PutConfigRevisionProjectionResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PutConfigRevisionProjectionResponse) GetObject() *PutConfigRevisionProjectionResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
