// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/optionalnullable"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
	"time"
)

// SetMonitoringModeRampScheduleMonitoringModeRequest - `auto` schedules snapshots automatically while allowed by ramp state. `manual` disables agenda updates and relies on manual Update clicks.
type SetMonitoringModeRampScheduleMonitoringModeRequest string

const (
	SetMonitoringModeRampScheduleMonitoringModeRequestAuto   SetMonitoringModeRampScheduleMonitoringModeRequest = "auto"
	SetMonitoringModeRampScheduleMonitoringModeRequestManual SetMonitoringModeRampScheduleMonitoringModeRequest = "manual"
)

func (e SetMonitoringModeRampScheduleMonitoringModeRequest) ToPointer() *SetMonitoringModeRampScheduleMonitoringModeRequest {
	return &e
}
func (e *SetMonitoringModeRampScheduleMonitoringModeRequest) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "auto":
		fallthrough
	case "manual":
		*e = SetMonitoringModeRampScheduleMonitoringModeRequest(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SetMonitoringModeRampScheduleMonitoringModeRequest: %v", v)
	}
}

type SetMonitoringModeRampScheduleRequestBody struct {
	// `auto` schedules snapshots automatically while allowed by ramp state. `manual` disables agenda updates and relies on manual Update clicks.
	MonitoringMode SetMonitoringModeRampScheduleMonitoringModeRequest `json:"monitoringMode"`
}

func (s *SetMonitoringModeRampScheduleRequestBody) GetMonitoringMode() SetMonitoringModeRampScheduleMonitoringModeRequest {
	if s == nil {
		return SetMonitoringModeRampScheduleMonitoringModeRequest("")
	}
	return s.MonitoringMode
}

type SetMonitoringModeRampScheduleRequest struct {
	ID   string                                   `pathParam:"style=simple,explode=false,name=id"`
	Body SetMonitoringModeRampScheduleRequestBody `request:"mediaType=application/json"`
}

func (s *SetMonitoringModeRampScheduleRequest) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SetMonitoringModeRampScheduleRequest) GetBody() SetMonitoringModeRampScheduleRequestBody {
	if s == nil {
		return SetMonitoringModeRampScheduleRequestBody{}
	}
	return s.Body
}

type SetMonitoringModeRampScheduleEntityType string

const (
	SetMonitoringModeRampScheduleEntityTypeFeature SetMonitoringModeRampScheduleEntityType = "feature"
)

func (e SetMonitoringModeRampScheduleEntityType) ToPointer() *SetMonitoringModeRampScheduleEntityType {
	return &e
}
func (e *SetMonitoringModeRampScheduleEntityType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "feature":
		*e = SetMonitoringModeRampScheduleEntityType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SetMonitoringModeRampScheduleEntityType: %v", v)
	}
}

type SetMonitoringModeRampScheduleStatus string

const (
	SetMonitoringModeRampScheduleStatusPending    SetMonitoringModeRampScheduleStatus = "pending"
	SetMonitoringModeRampScheduleStatusReady      SetMonitoringModeRampScheduleStatus = "ready"
	SetMonitoringModeRampScheduleStatusRunning    SetMonitoringModeRampScheduleStatus = "running"
	SetMonitoringModeRampScheduleStatusPaused     SetMonitoringModeRampScheduleStatus = "paused"
	SetMonitoringModeRampScheduleStatusCompleted  SetMonitoringModeRampScheduleStatus = "completed"
	SetMonitoringModeRampScheduleStatusRolledBack SetMonitoringModeRampScheduleStatus = "rolled-back"
)

func (e SetMonitoringModeRampScheduleStatus) ToPointer() *SetMonitoringModeRampScheduleStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SetMonitoringModeRampScheduleStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "pending", "ready", "running", "paused", "completed", "rolled-back":
			return true
		}
	}
	return false
}

type SetMonitoringModeRampScheduleMonitoringConfigMonitoringMode string

const (
	SetMonitoringModeRampScheduleMonitoringConfigMonitoringModeAuto   SetMonitoringModeRampScheduleMonitoringConfigMonitoringMode = "auto"
	SetMonitoringModeRampScheduleMonitoringConfigMonitoringModeManual SetMonitoringModeRampScheduleMonitoringConfigMonitoringMode = "manual"
)

func (e SetMonitoringModeRampScheduleMonitoringConfigMonitoringMode) ToPointer() *SetMonitoringModeRampScheduleMonitoringConfigMonitoringMode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SetMonitoringModeRampScheduleMonitoringConfigMonitoringMode) IsExact() bool {
	if e != nil {
		switch *e {
		case "auto", "manual":
			return true
		}
	}
	return false
}

type SetMonitoringModeRampScheduleSrmAction string

const (
	SetMonitoringModeRampScheduleSrmActionRollback SetMonitoringModeRampScheduleSrmAction = "rollback"
	SetMonitoringModeRampScheduleSrmActionHold     SetMonitoringModeRampScheduleSrmAction = "hold"
	SetMonitoringModeRampScheduleSrmActionWarn     SetMonitoringModeRampScheduleSrmAction = "warn"
)

func (e SetMonitoringModeRampScheduleSrmAction) ToPointer() *SetMonitoringModeRampScheduleSrmAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SetMonitoringModeRampScheduleSrmAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "rollback", "hold", "warn":
			return true
		}
	}
	return false
}

type SetMonitoringModeRampScheduleNoTrafficAction string

const (
	SetMonitoringModeRampScheduleNoTrafficActionRollback SetMonitoringModeRampScheduleNoTrafficAction = "rollback"
	SetMonitoringModeRampScheduleNoTrafficActionHold     SetMonitoringModeRampScheduleNoTrafficAction = "hold"
	SetMonitoringModeRampScheduleNoTrafficActionWarn     SetMonitoringModeRampScheduleNoTrafficAction = "warn"
)

func (e SetMonitoringModeRampScheduleNoTrafficAction) ToPointer() *SetMonitoringModeRampScheduleNoTrafficAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SetMonitoringModeRampScheduleNoTrafficAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "rollback", "hold", "warn":
			return true
		}
	}
	return false
}

type SetMonitoringModeRampScheduleMultipleExposureAction string

const (
	SetMonitoringModeRampScheduleMultipleExposureActionRollback SetMonitoringModeRampScheduleMultipleExposureAction = "rollback"
	SetMonitoringModeRampScheduleMultipleExposureActionHold     SetMonitoringModeRampScheduleMultipleExposureAction = "hold"
	SetMonitoringModeRampScheduleMultipleExposureActionWarn     SetMonitoringModeRampScheduleMultipleExposureAction = "warn"
)

func (e SetMonitoringModeRampScheduleMultipleExposureAction) ToPointer() *SetMonitoringModeRampScheduleMultipleExposureAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SetMonitoringModeRampScheduleMultipleExposureAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "rollback", "hold", "warn":
			return true
		}
	}
	return false
}

type SetMonitoringModeRampScheduleMonitoringConfig struct {
	DatasourceID          string                                                       `json:"datasourceId"`
	ExposureQueryID       string                                                       `json:"exposureQueryId"`
	GuardrailMetricIds    []string                                                     `json:"guardrailMetricIds"`
	SignalMetricIds       []string                                                     `json:"signalMetricIds,omitzero"`
	UpdateScheduleMinutes optionalnullable.OptionalNullable[float64]                   `json:"updateScheduleMinutes,omitzero"`
	MonitoringMode        *SetMonitoringModeRampScheduleMonitoringConfigMonitoringMode `json:"monitoringMode,omitzero"`
	AutoUpdate            *bool                                                        `json:"autoUpdate,omitzero"`
	SrmAction             *SetMonitoringModeRampScheduleSrmAction                      `json:"srmAction,omitzero"`
	NoTrafficAction       *SetMonitoringModeRampScheduleNoTrafficAction                `json:"noTrafficAction,omitzero"`
	// How long to wait for traffic before applying `noTrafficAction`. Defaults to 24 hours when null or not set.
	NoTrafficGracePeriodHours optionalnullable.OptionalNullable[float64]           `json:"noTrafficGracePeriodHours,omitzero"`
	MultipleExposureAction    *SetMonitoringModeRampScheduleMultipleExposureAction `json:"multipleExposureAction,omitzero"`
}

func (s SetMonitoringModeRampScheduleMonitoringConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SetMonitoringModeRampScheduleMonitoringConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SetMonitoringModeRampScheduleMonitoringConfig) GetDatasourceID() string {
	if s == nil {
		return ""
	}
	return s.DatasourceID
}

func (s *SetMonitoringModeRampScheduleMonitoringConfig) GetExposureQueryID() string {
	if s == nil {
		return ""
	}
	return s.ExposureQueryID
}

func (s *SetMonitoringModeRampScheduleMonitoringConfig) GetGuardrailMetricIds() []string {
	if s == nil {
		return []string{}
	}
	return s.GuardrailMetricIds
}

func (s *SetMonitoringModeRampScheduleMonitoringConfig) GetSignalMetricIds() []string {
	if s == nil {
		return nil
	}
	return s.SignalMetricIds
}

func (s *SetMonitoringModeRampScheduleMonitoringConfig) GetUpdateScheduleMinutes() optionalnullable.OptionalNullable[float64] {
	if s == nil {
		return nil
	}
	return s.UpdateScheduleMinutes
}

func (s *SetMonitoringModeRampScheduleMonitoringConfig) GetMonitoringMode() *SetMonitoringModeRampScheduleMonitoringConfigMonitoringMode {
	if s == nil {
		return nil
	}
	return s.MonitoringMode
}

func (s *SetMonitoringModeRampScheduleMonitoringConfig) GetAutoUpdate() *bool {
	if s == nil {
		return nil
	}
	return s.AutoUpdate
}

func (s *SetMonitoringModeRampScheduleMonitoringConfig) GetSrmAction() *SetMonitoringModeRampScheduleSrmAction {
	if s == nil {
		return nil
	}
	return s.SrmAction
}

func (s *SetMonitoringModeRampScheduleMonitoringConfig) GetNoTrafficAction() *SetMonitoringModeRampScheduleNoTrafficAction {
	if s == nil {
		return nil
	}
	return s.NoTrafficAction
}

func (s *SetMonitoringModeRampScheduleMonitoringConfig) GetNoTrafficGracePeriodHours() optionalnullable.OptionalNullable[float64] {
	if s == nil {
		return nil
	}
	return s.NoTrafficGracePeriodHours
}

func (s *SetMonitoringModeRampScheduleMonitoringConfig) GetMultipleExposureAction() *SetMonitoringModeRampScheduleMultipleExposureAction {
	if s == nil {
		return nil
	}
	return s.MultipleExposureAction
}

type SetMonitoringModeRampScheduleExperimentHealthAction string

const (
	SetMonitoringModeRampScheduleExperimentHealthActionRollback SetMonitoringModeRampScheduleExperimentHealthAction = "rollback"
	SetMonitoringModeRampScheduleExperimentHealthActionHold     SetMonitoringModeRampScheduleExperimentHealthAction = "hold"
	SetMonitoringModeRampScheduleExperimentHealthActionWarn     SetMonitoringModeRampScheduleExperimentHealthAction = "warn"
)

func (e SetMonitoringModeRampScheduleExperimentHealthAction) ToPointer() *SetMonitoringModeRampScheduleExperimentHealthAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SetMonitoringModeRampScheduleExperimentHealthAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "rollback", "hold", "warn":
			return true
		}
	}
	return false
}

// SetMonitoringModeRampScheduleContext - Surface through which the approval was granted.
type SetMonitoringModeRampScheduleContext string

const (
	SetMonitoringModeRampScheduleContextUI  SetMonitoringModeRampScheduleContext = "ui"
	SetMonitoringModeRampScheduleContextAPI SetMonitoringModeRampScheduleContext = "api"
)

func (e SetMonitoringModeRampScheduleContext) ToPointer() *SetMonitoringModeRampScheduleContext {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SetMonitoringModeRampScheduleContext) IsExact() bool {
	if e != nil {
		switch *e {
		case "ui", "api":
			return true
		}
	}
	return false
}

type SetMonitoringModeRampScheduleStepApproval struct {
	// Index of the step that was approved.
	StepIndex int64 `json:"stepIndex"`
	// When the approval was granted.
	ApprovedAt time.Time `json:"approvedAt"`
	// User ID of the approver.
	ApprovedBy string `json:"approvedBy"`
	// Surface through which the approval was granted.
	Context SetMonitoringModeRampScheduleContext `json:"context"`
}

func (s SetMonitoringModeRampScheduleStepApproval) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SetMonitoringModeRampScheduleStepApproval) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SetMonitoringModeRampScheduleStepApproval) GetStepIndex() int64 {
	if s == nil {
		return 0
	}
	return s.StepIndex
}

func (s *SetMonitoringModeRampScheduleStepApproval) GetApprovedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.ApprovedAt
}

func (s *SetMonitoringModeRampScheduleStepApproval) GetApprovedBy() string {
	if s == nil {
		return ""
	}
	return s.ApprovedBy
}

func (s *SetMonitoringModeRampScheduleStepApproval) GetContext() SetMonitoringModeRampScheduleContext {
	if s == nil {
		return SetMonitoringModeRampScheduleContext("")
	}
	return s.Context
}

// SetMonitoringModeRampScheduleMonitoringStatusMonitoringMode - User-selected monitoring mode. `auto` schedules snapshots automatically; `manual` requires clicking Update.
type SetMonitoringModeRampScheduleMonitoringStatusMonitoringMode string

const (
	SetMonitoringModeRampScheduleMonitoringStatusMonitoringModeAuto   SetMonitoringModeRampScheduleMonitoringStatusMonitoringMode = "auto"
	SetMonitoringModeRampScheduleMonitoringStatusMonitoringModeManual SetMonitoringModeRampScheduleMonitoringStatusMonitoringMode = "manual"
)

func (e SetMonitoringModeRampScheduleMonitoringStatusMonitoringMode) ToPointer() *SetMonitoringModeRampScheduleMonitoringStatusMonitoringMode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SetMonitoringModeRampScheduleMonitoringStatusMonitoringMode) IsExact() bool {
	if e != nil {
		switch *e {
		case "auto", "manual":
			return true
		}
	}
	return false
}

type SetMonitoringModeRampScheduleMonitoringStatus struct {
	SafeRolloutID optionalnullable.OptionalNullable[string] `json:"safeRolloutId,omitzero"`
	// User-selected monitoring mode. `auto` schedules snapshots automatically; `manual` requires clicking Update.
	MonitoringMode SetMonitoringModeRampScheduleMonitoringStatusMonitoringMode `json:"monitoringMode"`
	// Legacy alias for auto-update behavior. Prefer `monitoringMode` (`auto` means true, `manual` means false).
	AutoUpdate bool `json:"autoUpdate"`
	// Computed runtime flag. True only when monitoring mode is auto and schedule state allows automatic snapshot scheduling.
	EffectiveAutoUpdate bool `json:"effectiveAutoUpdate"`
	// When `effectiveAutoUpdate` is false, this describes the computed reason auto-updates are currently blocked.
	BlockedReason optionalnullable.OptionalNullable[string] `json:"blockedReason,omitzero"`
	// When the next automatic snapshot query will run
	NextSnapshotAt optionalnullable.OptionalNullable[time.Time] `json:"nextSnapshotAt,omitzero"`
	// Whether the step at currentStepIndex has monitoring enabled
	CurrentStepMonitored bool `json:"currentStepMonitored"`
}

func (s SetMonitoringModeRampScheduleMonitoringStatus) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SetMonitoringModeRampScheduleMonitoringStatus) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SetMonitoringModeRampScheduleMonitoringStatus) GetSafeRolloutID() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.SafeRolloutID
}

func (s *SetMonitoringModeRampScheduleMonitoringStatus) GetMonitoringMode() SetMonitoringModeRampScheduleMonitoringStatusMonitoringMode {
	if s == nil {
		return SetMonitoringModeRampScheduleMonitoringStatusMonitoringMode("")
	}
	return s.MonitoringMode
}

func (s *SetMonitoringModeRampScheduleMonitoringStatus) GetAutoUpdate() bool {
	if s == nil {
		return false
	}
	return s.AutoUpdate
}

func (s *SetMonitoringModeRampScheduleMonitoringStatus) GetEffectiveAutoUpdate() bool {
	if s == nil {
		return false
	}
	return s.EffectiveAutoUpdate
}

func (s *SetMonitoringModeRampScheduleMonitoringStatus) GetBlockedReason() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.BlockedReason
}

func (s *SetMonitoringModeRampScheduleMonitoringStatus) GetNextSnapshotAt() optionalnullable.OptionalNullable[time.Time] {
	if s == nil {
		return nil
	}
	return s.NextSnapshotAt
}

func (s *SetMonitoringModeRampScheduleMonitoringStatus) GetCurrentStepMonitored() bool {
	if s == nil {
		return false
	}
	return s.CurrentStepMonitored
}

// SetMonitoringModeRampScheduleResponseBody - Resource created
type SetMonitoringModeRampScheduleResponseBody struct {
	// Unique identifier (rs_ prefix)
	ID          string                                  `json:"id"`
	DateCreated time.Time                               `json:"dateCreated"`
	DateUpdated time.Time                               `json:"dateUpdated"`
	Name        string                                  `json:"name"`
	EntityType  SetMonitoringModeRampScheduleEntityType `json:"entityType"`
	EntityID    string                                  `json:"entityId"`
	// Controlled entity references
	Targets []components.Targets `json:"targets"`
	// Actions that restore controlled rules to their pre-ramp state. Applied when rolling back or jumping to start.
	StartActions []components.StartActions `json:"startActions,omitzero"`
	// Ordered ramp steps
	Steps []components.Steps `json:"steps"`
	// Actions applied on top of all step patches when the ramp completes. Represents the final desired rule state.
	EndActions []components.StartActions `json:"endActions,omitzero"`
	// When the ramp fires. Absent/null means immediately on publish; set to a future datetime to delay start and keep the rule disabled until that time.
	StartDate optionalnullable.OptionalNullable[time.Time] `json:"startDate,omitzero"`
	// Rule-level kill date. When reached, the ramp is completed and the rule is disabled (enabled=false). Use for time-boxed rules that must stop serving on a fixed date regardless of ramp progress. Set to null to clear.
	CutoffDate optionalnullable.OptionalNullable[time.Time] `json:"cutoffDate,omitzero"`
	Status     SetMonitoringModeRampScheduleStatus          `json:"status"`
	// Index of current step; -1 = not yet started
	CurrentStepIndex int64                                        `json:"currentStepIndex"`
	StartedAt        optionalnullable.OptionalNullable[time.Time] `json:"startedAt,omitzero"`
	// Anchor for cumulative interval timing; resets after each approval gate is satisfied
	PhaseStartedAt optionalnullable.OptionalNullable[time.Time] `json:"phaseStartedAt,omitzero"`
	PausedAt       optionalnullable.OptionalNullable[time.Time] `json:"pausedAt,omitzero"`
	// When the current step's time gate elapses; null for steps with no interval (pure approval gates) and terminal states
	NextStepAt    *time.Time                                   `json:"nextStepAt"`
	NextProcessAt optionalnullable.OptionalNullable[time.Time] `json:"nextProcessAt,omitzero"`
	// Milliseconds since startedAt (computed at response time, not stored)
	ElapsedMs              optionalnullable.OptionalNullable[int64]                                         `json:"elapsedMs,omitzero"`
	LockdownConfig         *components.LockdownConfig                                                       `json:"lockdownConfig,omitzero"`
	MonitoringConfig       optionalnullable.OptionalNullable[SetMonitoringModeRampScheduleMonitoringConfig] `json:"monitoringConfig,omitzero"`
	ExperimentHealthAction *SetMonitoringModeRampScheduleExperimentHealthAction                             `json:"experimentHealthAction,omitzero"`
	CurrentStepEnteredAt   optionalnullable.OptionalNullable[time.Time]                                     `json:"currentStepEnteredAt,omitzero"`
	// Approval record for the current step. Valid only while `stepApproval.stepIndex === currentStepIndex`.
	StepApproval optionalnullable.OptionalNullable[SetMonitoringModeRampScheduleStepApproval] `json:"stepApproval,omitzero"`
	// When the monitored section most recently started (first monitored step entered). Used for no-traffic grace period gating.
	MonitoringStartDate optionalnullable.OptionalNullable[time.Time] `json:"monitoringStartDate,omitzero"`
	LastRollbackAt      optionalnullable.OptionalNullable[time.Time] `json:"lastRollbackAt,omitzero"`
	LastRollbackReason  optionalnullable.OptionalNullable[string]    `json:"lastRollbackReason,omitzero"`
	// Read-only monitoring status. Present when monitoringConfig is set.
	MonitoringStatus optionalnullable.OptionalNullable[SetMonitoringModeRampScheduleMonitoringStatus] `json:"monitoringStatus,omitzero"`
}

func (s SetMonitoringModeRampScheduleResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SetMonitoringModeRampScheduleResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetDateCreated() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.DateCreated
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetDateUpdated() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.DateUpdated
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetEntityType() SetMonitoringModeRampScheduleEntityType {
	if s == nil {
		return SetMonitoringModeRampScheduleEntityType("")
	}
	return s.EntityType
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetEntityID() string {
	if s == nil {
		return ""
	}
	return s.EntityID
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetTargets() []components.Targets {
	if s == nil {
		return []components.Targets{}
	}
	return s.Targets
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetStartActions() []components.StartActions {
	if s == nil {
		return nil
	}
	return s.StartActions
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetSteps() []components.Steps {
	if s == nil {
		return []components.Steps{}
	}
	return s.Steps
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetEndActions() []components.StartActions {
	if s == nil {
		return nil
	}
	return s.EndActions
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetStartDate() optionalnullable.OptionalNullable[time.Time] {
	if s == nil {
		return nil
	}
	return s.StartDate
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetCutoffDate() optionalnullable.OptionalNullable[time.Time] {
	if s == nil {
		return nil
	}
	return s.CutoffDate
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetStatus() SetMonitoringModeRampScheduleStatus {
	if s == nil {
		return SetMonitoringModeRampScheduleStatus("")
	}
	return s.Status
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetCurrentStepIndex() int64 {
	if s == nil {
		return 0
	}
	return s.CurrentStepIndex
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetStartedAt() optionalnullable.OptionalNullable[time.Time] {
	if s == nil {
		return nil
	}
	return s.StartedAt
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetPhaseStartedAt() optionalnullable.OptionalNullable[time.Time] {
	if s == nil {
		return nil
	}
	return s.PhaseStartedAt
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetPausedAt() optionalnullable.OptionalNullable[time.Time] {
	if s == nil {
		return nil
	}
	return s.PausedAt
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetNextStepAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.NextStepAt
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetNextProcessAt() optionalnullable.OptionalNullable[time.Time] {
	if s == nil {
		return nil
	}
	return s.NextProcessAt
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetElapsedMs() optionalnullable.OptionalNullable[int64] {
	if s == nil {
		return nil
	}
	return s.ElapsedMs
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetLockdownConfig() *components.LockdownConfig {
	if s == nil {
		return nil
	}
	return s.LockdownConfig
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetMonitoringConfig() optionalnullable.OptionalNullable[SetMonitoringModeRampScheduleMonitoringConfig] {
	if s == nil {
		return nil
	}
	return s.MonitoringConfig
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetExperimentHealthAction() *SetMonitoringModeRampScheduleExperimentHealthAction {
	if s == nil {
		return nil
	}
	return s.ExperimentHealthAction
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetCurrentStepEnteredAt() optionalnullable.OptionalNullable[time.Time] {
	if s == nil {
		return nil
	}
	return s.CurrentStepEnteredAt
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetStepApproval() optionalnullable.OptionalNullable[SetMonitoringModeRampScheduleStepApproval] {
	if s == nil {
		return nil
	}
	return s.StepApproval
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetMonitoringStartDate() optionalnullable.OptionalNullable[time.Time] {
	if s == nil {
		return nil
	}
	return s.MonitoringStartDate
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetLastRollbackAt() optionalnullable.OptionalNullable[time.Time] {
	if s == nil {
		return nil
	}
	return s.LastRollbackAt
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetLastRollbackReason() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.LastRollbackReason
}

func (s *SetMonitoringModeRampScheduleResponseBody) GetMonitoringStatus() optionalnullable.OptionalNullable[SetMonitoringModeRampScheduleMonitoringStatus] {
	if s == nil {
		return nil
	}
	return s.MonitoringStatus
}

type SetMonitoringModeRampScheduleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Resource created
	Object *SetMonitoringModeRampScheduleResponseBody
}

func (s SetMonitoringModeRampScheduleResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SetMonitoringModeRampScheduleResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SetMonitoringModeRampScheduleResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SetMonitoringModeRampScheduleResponse) GetObject() *SetMonitoringModeRampScheduleResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
