// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b95f36b15fa2

package operations

import (
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

type ToggleFeatureRequestBody struct {
	Reason       *string        `json:"reason,omitzero"`
	Environments map[string]any `json:"environments"`
}

func (t *ToggleFeatureRequestBody) GetReason() *string {
	if t == nil {
		return nil
	}
	return t.Reason
}

func (t *ToggleFeatureRequestBody) GetEnvironments() map[string]any {
	if t == nil {
		return map[string]any{}
	}
	return t.Environments
}

type ToggleFeatureRequest struct {
	// The id of the requested resource
	ID   string                   `pathParam:"style=simple,explode=false,name=id"`
	Body ToggleFeatureRequestBody `request:"mediaType=application/json"`
}

func (t *ToggleFeatureRequest) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *ToggleFeatureRequest) GetBody() ToggleFeatureRequestBody {
	if t == nil {
		return ToggleFeatureRequestBody{}
	}
	return t.Body
}

type ToggleFeatureResponseBody struct {
	Feature components.Feature `json:"feature"`
}

func (t *ToggleFeatureResponseBody) GetFeature() components.Feature {
	if t == nil {
		return components.Feature{}
	}
	return t.Feature
}

type ToggleFeatureResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *ToggleFeatureResponseBody
}

func (t ToggleFeatureResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *ToggleFeatureResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *ToggleFeatureResponse) GetHTTPMeta() components.HTTPMetadata {
	if t == nil {
		return components.HTTPMetadata{}
	}
	return t.HTTPMeta
}

func (t *ToggleFeatureResponse) GetObject() *ToggleFeatureResponseBody {
	if t == nil {
		return nil
	}
	return t.Object
}
