// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/growthbook/cli/v2/internal/sdk/models/components"
	"github.com/growthbook/cli/v2/internal/sdk/sdkinternal/utils"
)

type UpdateSavedGroupRequestBody struct {
	// The display name of the Saved Group
	Name *string `json:"name,omitzero"`
	// When type = 'condition', this is the JSON-encoded condition for the group
	Condition *string `json:"condition,omitzero"`
	// When type = 'list', this is the list of values for the attribute key
	Values []string `json:"values,omitzero"`
	// The userId or email address of the owner. If an email address is provided, it will be used to look up the userId of the matching organization member. If an ID is provided, it will be validated as existing in the organization.
	Owner    *string  `json:"owner,omitzero"`
	Projects []string `json:"projects,omitzero"`
	// Set to true to update the live Saved Group without approval. The caller must have Bypass draft approvals access in every current and destination Project. This field has no effect when approval is not required.
	BypassApproval *bool `json:"bypassApproval,omitzero"`
}

func (u UpdateSavedGroupRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateSavedGroupRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateSavedGroupRequestBody) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateSavedGroupRequestBody) GetCondition() *string {
	if u == nil {
		return nil
	}
	return u.Condition
}

func (u *UpdateSavedGroupRequestBody) GetValues() []string {
	if u == nil {
		return nil
	}
	return u.Values
}

func (u *UpdateSavedGroupRequestBody) GetOwner() *string {
	if u == nil {
		return nil
	}
	return u.Owner
}

func (u *UpdateSavedGroupRequestBody) GetProjects() []string {
	if u == nil {
		return nil
	}
	return u.Projects
}

func (u *UpdateSavedGroupRequestBody) GetBypassApproval() *bool {
	if u == nil {
		return nil
	}
	return u.BypassApproval
}

type UpdateSavedGroupRequest struct {
	// The id of the requested resource
	ID   string                      `pathParam:"style=simple,explode=false,name=id"`
	Body UpdateSavedGroupRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateSavedGroupRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateSavedGroupRequest) GetBody() UpdateSavedGroupRequestBody {
	if u == nil {
		return UpdateSavedGroupRequestBody{}
	}
	return u.Body
}

// UpdateSavedGroupResponseBody - Resource created
type UpdateSavedGroupResponseBody struct {
	SavedGroup components.SavedGroup `json:"savedGroup"`
	// Gates that would have blocked this publish but were bypassed by the caller's authority. Present only when at least one gate was bypassed.
	BypassedGates []components.BypassedGates `json:"bypassedGates,omitzero"`
}

func (u UpdateSavedGroupResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateSavedGroupResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateSavedGroupResponseBody) GetSavedGroup() components.SavedGroup {
	if u == nil {
		return components.SavedGroup{}
	}
	return u.SavedGroup
}

func (u *UpdateSavedGroupResponseBody) GetBypassedGates() []components.BypassedGates {
	if u == nil {
		return nil
	}
	return u.BypassedGates
}

type UpdateSavedGroupResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Resource created
	Object *UpdateSavedGroupResponseBody
}

func (u UpdateSavedGroupResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateSavedGroupResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateSavedGroupResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateSavedGroupResponse) GetObject() *UpdateSavedGroupResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
