// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/growthbook/cli/v2/internal/sdk/models/components"
	"github.com/growthbook/cli/v2/internal/sdk/sdkinternal/utils"
)

type UpdateMemberRoleAdditionalRole struct {
	Role                     string   `json:"role"`
	Environments             []string `json:"environments"`
	LimitAccessByEnvironment *bool    `json:"limitAccessByEnvironment,omitzero"`
}

func (u *UpdateMemberRoleAdditionalRole) GetRole() string {
	if u == nil {
		return ""
	}
	return u.Role
}

func (u *UpdateMemberRoleAdditionalRole) GetEnvironments() []string {
	if u == nil {
		return []string{}
	}
	return u.Environments
}

func (u *UpdateMemberRoleAdditionalRole) GetLimitAccessByEnvironment() *bool {
	if u == nil {
		return nil
	}
	return u.LimitAccessByEnvironment
}

type UpdateMemberRoleProjectRoleAdditionalRole struct {
	Role                     string   `json:"role"`
	Environments             []string `json:"environments"`
	LimitAccessByEnvironment *bool    `json:"limitAccessByEnvironment,omitzero"`
}

func (u *UpdateMemberRoleProjectRoleAdditionalRole) GetRole() string {
	if u == nil {
		return ""
	}
	return u.Role
}

func (u *UpdateMemberRoleProjectRoleAdditionalRole) GetEnvironments() []string {
	if u == nil {
		return []string{}
	}
	return u.Environments
}

func (u *UpdateMemberRoleProjectRoleAdditionalRole) GetLimitAccessByEnvironment() *bool {
	if u == nil {
		return nil
	}
	return u.LimitAccessByEnvironment
}

type UpdateMemberRoleProjectRole struct {
	Project                  string   `json:"project"`
	Role                     string   `json:"role"`
	Environments             []string `json:"environments"`
	LimitAccessByEnvironment *bool    `json:"limitAccessByEnvironment,omitzero"`
	// Additional roles granted alongside this one, in the same scope. Each is granted independently and environment access is the union across them.
	AdditionalRoles []UpdateMemberRoleProjectRoleAdditionalRole `json:"additionalRoles,omitzero"`
}

func (u UpdateMemberRoleProjectRole) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateMemberRoleProjectRole) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateMemberRoleProjectRole) GetProject() string {
	if u == nil {
		return ""
	}
	return u.Project
}

func (u *UpdateMemberRoleProjectRole) GetRole() string {
	if u == nil {
		return ""
	}
	return u.Role
}

func (u *UpdateMemberRoleProjectRole) GetEnvironments() []string {
	if u == nil {
		return []string{}
	}
	return u.Environments
}

func (u *UpdateMemberRoleProjectRole) GetLimitAccessByEnvironment() *bool {
	if u == nil {
		return nil
	}
	return u.LimitAccessByEnvironment
}

func (u *UpdateMemberRoleProjectRole) GetAdditionalRoles() []UpdateMemberRoleProjectRoleAdditionalRole {
	if u == nil {
		return nil
	}
	return u.AdditionalRoles
}

type Member struct {
	Role         *string  `json:"role,omitzero"`
	Environments []string `json:"environments,omitzero"`
	// Additional roles granted alongside this one, in the same scope. Each is granted independently and environment access is the union across them.
	AdditionalRoles []UpdateMemberRoleAdditionalRole `json:"additionalRoles,omitzero"`
	ProjectRoles    []UpdateMemberRoleProjectRole    `json:"projectRoles,omitzero"`
}

func (m Member) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *Member) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *Member) GetRole() *string {
	if m == nil {
		return nil
	}
	return m.Role
}

func (m *Member) GetEnvironments() []string {
	if m == nil {
		return nil
	}
	return m.Environments
}

func (m *Member) GetAdditionalRoles() []UpdateMemberRoleAdditionalRole {
	if m == nil {
		return nil
	}
	return m.AdditionalRoles
}

func (m *Member) GetProjectRoles() []UpdateMemberRoleProjectRole {
	if m == nil {
		return nil
	}
	return m.ProjectRoles
}

type UpdateMemberRoleRequestBody struct {
	Member Member `json:"member"`
}

func (u *UpdateMemberRoleRequestBody) GetMember() Member {
	if u == nil {
		return Member{}
	}
	return u.Member
}

type UpdateMemberRoleRequest struct {
	// The id of the requested resource
	ID   string                      `pathParam:"style=simple,explode=false,name=id"`
	Body UpdateMemberRoleRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateMemberRoleRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateMemberRoleRequest) GetBody() UpdateMemberRoleRequestBody {
	if u == nil {
		return UpdateMemberRoleRequestBody{}
	}
	return u.Body
}

// UpdateMemberRoleResponseBody - Resource created
type UpdateMemberRoleResponseBody struct {
	UpdatedMember components.UpdatedMember `json:"updatedMember"`
}

func (u *UpdateMemberRoleResponseBody) GetUpdatedMember() components.UpdatedMember {
	if u == nil {
		return components.UpdatedMember{}
	}
	return u.UpdatedMember
}

type UpdateMemberRoleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Resource created
	Object *UpdateMemberRoleResponseBody
}

func (u UpdateMemberRoleResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateMemberRoleResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateMemberRoleResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateMemberRoleResponse) GetObject() *UpdateMemberRoleResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
