// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/growthbook/cli/v2/internal/sdk/models/components"
	"github.com/growthbook/cli/v2/internal/sdk/optionalnullable"
	"github.com/growthbook/cli/v2/internal/sdk/sdkinternal/utils"
)

type UpdateContextualBanditLinkedFeatureVariation struct {
	// Id of the Contextual Bandit variation.
	VariationID string `json:"variationId"`
	// Feature value served for this variation.
	Value string `json:"value"`
	// Key of the config backing this value, or null when the value is not config-backed. The config supplies the base JSON (and its schema); the value is an override patch merged on top.
	Config optionalnullable.OptionalNullable[string] `json:"config,omitzero"`
}

func (u *UpdateContextualBanditLinkedFeatureVariation) GetVariationID() string {
	if u == nil {
		return ""
	}
	return u.VariationID
}

func (u *UpdateContextualBanditLinkedFeatureVariation) GetValue() string {
	if u == nil {
		return ""
	}
	return u.Value
}

func (u *UpdateContextualBanditLinkedFeatureVariation) GetConfig() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.Config
}

type UpdateContextualBanditLinkedFeatureRequestBody struct {
	// One entry per Contextual Bandit variation. Every variation must be covered exactly once.
	Variations  []UpdateContextualBanditLinkedFeatureVariation `json:"variations"`
	Description *string                                        `json:"description,omitzero"`
	Enabled     *bool                                          `json:"enabled,omitzero"`
	// Apply the rule in every environment. Defaults to true.
	AllEnvironments *bool `json:"allEnvironments,omitzero"`
	// Environments to apply the rule in when not all.
	Environments []string `json:"environments,omitzero"`
	AllProjects  *bool    `json:"allProjects,omitzero"`
	Projects     []string `json:"projects,omitzero"`
	// Publish the resulting revision immediately instead of leaving it as a draft.
	AutoPublish *bool `json:"autoPublish,omitzero"`
	// Update the rule on this existing draft revision instead of starting a new one.
	DraftVersion *int64 `json:"draftVersion,omitzero"`
}

func (u UpdateContextualBanditLinkedFeatureRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateContextualBanditLinkedFeatureRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateContextualBanditLinkedFeatureRequestBody) GetVariations() []UpdateContextualBanditLinkedFeatureVariation {
	if u == nil {
		return []UpdateContextualBanditLinkedFeatureVariation{}
	}
	return u.Variations
}

func (u *UpdateContextualBanditLinkedFeatureRequestBody) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateContextualBanditLinkedFeatureRequestBody) GetEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.Enabled
}

func (u *UpdateContextualBanditLinkedFeatureRequestBody) GetAllEnvironments() *bool {
	if u == nil {
		return nil
	}
	return u.AllEnvironments
}

func (u *UpdateContextualBanditLinkedFeatureRequestBody) GetEnvironments() []string {
	if u == nil {
		return nil
	}
	return u.Environments
}

func (u *UpdateContextualBanditLinkedFeatureRequestBody) GetAllProjects() *bool {
	if u == nil {
		return nil
	}
	return u.AllProjects
}

func (u *UpdateContextualBanditLinkedFeatureRequestBody) GetProjects() []string {
	if u == nil {
		return nil
	}
	return u.Projects
}

func (u *UpdateContextualBanditLinkedFeatureRequestBody) GetAutoPublish() *bool {
	if u == nil {
		return nil
	}
	return u.AutoPublish
}

func (u *UpdateContextualBanditLinkedFeatureRequestBody) GetDraftVersion() *int64 {
	if u == nil {
		return nil
	}
	return u.DraftVersion
}

type UpdateContextualBanditLinkedFeatureRequest struct {
	// The Contextual Bandit id
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// The linked feature id
	FeatureID string                                         `pathParam:"style=simple,explode=false,name=featureId"`
	Body      UpdateContextualBanditLinkedFeatureRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateContextualBanditLinkedFeatureRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateContextualBanditLinkedFeatureRequest) GetFeatureID() string {
	if u == nil {
		return ""
	}
	return u.FeatureID
}

func (u *UpdateContextualBanditLinkedFeatureRequest) GetBody() UpdateContextualBanditLinkedFeatureRequestBody {
	if u == nil {
		return UpdateContextualBanditLinkedFeatureRequestBody{}
	}
	return u.Body
}

// UpdateContextualBanditLinkedFeatureResponseBody - Resource updated
type UpdateContextualBanditLinkedFeatureResponseBody struct {
	FeatureID       string   `json:"featureId"`
	RuleIds         []string `json:"ruleIds"`
	RevisionVersion float64  `json:"revisionVersion"`
	Published       bool     `json:"published"`
}

func (u *UpdateContextualBanditLinkedFeatureResponseBody) GetFeatureID() string {
	if u == nil {
		return ""
	}
	return u.FeatureID
}

func (u *UpdateContextualBanditLinkedFeatureResponseBody) GetRuleIds() []string {
	if u == nil {
		return []string{}
	}
	return u.RuleIds
}

func (u *UpdateContextualBanditLinkedFeatureResponseBody) GetRevisionVersion() float64 {
	if u == nil {
		return 0.0
	}
	return u.RevisionVersion
}

func (u *UpdateContextualBanditLinkedFeatureResponseBody) GetPublished() bool {
	if u == nil {
		return false
	}
	return u.Published
}

type UpdateContextualBanditLinkedFeatureResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Resource updated
	Object *UpdateContextualBanditLinkedFeatureResponseBody
}

func (u UpdateContextualBanditLinkedFeatureResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateContextualBanditLinkedFeatureResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateContextualBanditLinkedFeatureResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateContextualBanditLinkedFeatureResponse) GetObject() *UpdateContextualBanditLinkedFeatureResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
