// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"errors"
	"fmt"
	"github.com/growthbook/cli/internal/sdk/models/components"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

type UpdateTeamProjectRole struct {
	Role                     string   `json:"role"`
	LimitAccessByEnvironment bool     `json:"limitAccessByEnvironment"`
	Environments             []string `json:"environments"`
	Teams                    []string `json:"teams,omitzero"`
	Project                  string   `json:"project"`
}

func (u UpdateTeamProjectRole) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateTeamProjectRole) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateTeamProjectRole) GetRole() string {
	if u == nil {
		return ""
	}
	return u.Role
}

func (u *UpdateTeamProjectRole) GetLimitAccessByEnvironment() bool {
	if u == nil {
		return false
	}
	return u.LimitAccessByEnvironment
}

func (u *UpdateTeamProjectRole) GetEnvironments() []string {
	if u == nil {
		return []string{}
	}
	return u.Environments
}

func (u *UpdateTeamProjectRole) GetTeams() []string {
	if u == nil {
		return nil
	}
	return u.Teams
}

func (u *UpdateTeamProjectRole) GetProject() string {
	if u == nil {
		return ""
	}
	return u.Project
}

type UpdateTeamManagedByVercel struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_      string `const:"vercel" json:"type"`
	ResourceID string `json:"resourceId"`
}

func (u UpdateTeamManagedByVercel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateTeamManagedByVercel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateTeamManagedByVercel) GetType() string {
	return "vercel"
}

func (u *UpdateTeamManagedByVercel) GetResourceID() string {
	if u == nil {
		return ""
	}
	return u.ResourceID
}

type UpdateTeamManagedByUnionType string

const (
	UpdateTeamManagedByUnionTypeUpdateTeamManagedByVercel UpdateTeamManagedByUnionType = "updateTeam_managedBy_Vercel"
)

type UpdateTeamManagedByUnion struct {
	UpdateTeamManagedByVercel *UpdateTeamManagedByVercel `queryParam:"inline" union:"member"`

	Type UpdateTeamManagedByUnionType
}

func CreateUpdateTeamManagedByUnionUpdateTeamManagedByVercel(updateTeamManagedByVercel UpdateTeamManagedByVercel) UpdateTeamManagedByUnion {
	typ := UpdateTeamManagedByUnionTypeUpdateTeamManagedByVercel

	return UpdateTeamManagedByUnion{
		UpdateTeamManagedByVercel: &updateTeamManagedByVercel,
		Type:                      typ,
	}
}

func (u *UpdateTeamManagedByUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var updateTeamManagedByVercel UpdateTeamManagedByVercel = UpdateTeamManagedByVercel{}
	if err := utils.UnmarshalJSON(data, &updateTeamManagedByVercel, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  UpdateTeamManagedByUnionTypeUpdateTeamManagedByVercel,
			Value: &updateTeamManagedByVercel,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpdateTeamManagedByUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpdateTeamManagedByUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(UpdateTeamManagedByUnionType)
	switch best.Type {
	case UpdateTeamManagedByUnionTypeUpdateTeamManagedByVercel:
		u.UpdateTeamManagedByVercel = best.Value.(*UpdateTeamManagedByVercel)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpdateTeamManagedByUnion", string(data))
}

func (u UpdateTeamManagedByUnion) MarshalJSON() ([]byte, error) {
	if u.UpdateTeamManagedByVercel != nil {
		return utils.MarshalJSON(u.UpdateTeamManagedByVercel, "", true)
	}

	return nil, errors.New("could not marshal union type UpdateTeamManagedByUnion: all fields are null")
}

type UpdateTeamRequestBody struct {
	Name        *string `json:"name,omitzero"`
	CreatedBy   *string `json:"createdBy,omitzero"`
	Description *string `json:"description,omitzero"`
	// The global role for members of this team
	Role                     *string `json:"role,omitzero"`
	LimitAccessByEnvironment *bool   `json:"limitAccessByEnvironment,omitzero"`
	// An empty array means 'all environments'
	Environments   []string                  `json:"environments,omitzero"`
	ProjectRoles   []UpdateTeamProjectRole   `json:"projectRoles,omitzero"`
	ManagedBy      *UpdateTeamManagedByUnion `json:"managedBy,omitzero"`
	DefaultProject *string                   `json:"defaultProject,omitzero"`
}

func (u UpdateTeamRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateTeamRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateTeamRequestBody) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateTeamRequestBody) GetCreatedBy() *string {
	if u == nil {
		return nil
	}
	return u.CreatedBy
}

func (u *UpdateTeamRequestBody) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateTeamRequestBody) GetRole() *string {
	if u == nil {
		return nil
	}
	return u.Role
}

func (u *UpdateTeamRequestBody) GetLimitAccessByEnvironment() *bool {
	if u == nil {
		return nil
	}
	return u.LimitAccessByEnvironment
}

func (u *UpdateTeamRequestBody) GetEnvironments() []string {
	if u == nil {
		return nil
	}
	return u.Environments
}

func (u *UpdateTeamRequestBody) GetProjectRoles() []UpdateTeamProjectRole {
	if u == nil {
		return nil
	}
	return u.ProjectRoles
}

func (u *UpdateTeamRequestBody) GetManagedBy() *UpdateTeamManagedByUnion {
	if u == nil {
		return nil
	}
	return u.ManagedBy
}

func (u *UpdateTeamRequestBody) GetDefaultProject() *string {
	if u == nil {
		return nil
	}
	return u.DefaultProject
}

type UpdateTeamRequest struct {
	ID   string                `pathParam:"style=simple,explode=false,name=id"`
	Body UpdateTeamRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateTeamRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateTeamRequest) GetBody() UpdateTeamRequestBody {
	if u == nil {
		return UpdateTeamRequestBody{}
	}
	return u.Body
}

type UpdateTeamResponseBody struct {
	Team components.Team `json:"team"`
}

func (u *UpdateTeamResponseBody) GetTeam() components.Team {
	if u == nil {
		return components.Team{}
	}
	return u.Team
}

type UpdateTeamResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *UpdateTeamResponseBody
}

func (u UpdateTeamResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateTeamResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateTeamResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateTeamResponse) GetObject() *UpdateTeamResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
