// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package configrevisions

import (
	"fmt"
	"github.com/growthbook/cli/v2/internal/client"
	"github.com/growthbook/cli/v2/internal/flagutil"
	"github.com/growthbook/cli/v2/internal/interactive"
	"github.com/growthbook/cli/v2/internal/output"
	"github.com/growthbook/cli/v2/internal/sdk"
	"github.com/growthbook/cli/v2/internal/sdk/models/operations"
	"github.com/growthbook/cli/v2/internal/usage"
	"github.com/spf13/cobra"
)

var setPropertyCmdMeta = []flagutil.FlagMeta{
	{FlagName: "key", Shorthand: "k", FieldPath: "Key", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "version-param", FieldPath: "Version", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "revision-title", FieldPath: "Body.RevisionTitle", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "revision-comment", FieldPath: "Body.RevisionComment", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "property", Shorthand: "p", FieldPath: "Body.Property", Kind: flagutil.FlagKindString, Required: true, Description: "Name of the property to set in this config's own value. [required]"},
	{FlagName: "value", FieldPath: "Body.Value", Kind: flagutil.FlagKindJSON, Required: true, Annotations: `json:"value"`, Description: "The property's new value. `null` sets it to null. [required]"},
	{FlagName: "ignore-warnings", Shorthand: "i", FieldPath: "Body.IgnoreWarnings", Kind: flagutil.FlagKindBool, Optional: true, Description: "Set to true to acknowledge the warnings listed in a blocked response and continue. This covers experiment guards, locked dependents, and references affected by an archive. When the organization treats schema failures as warnings, it also covers schema and invariant warnings. It never bypasses a rejected Custom Hook. On revision publish endpoints, it can also force-publish an out-of-date draft when the caller has Bypass draft approvals access."},
	{FlagName: "skip-schema-validation", FieldPath: "Body.SkipSchemaValidation", Kind: flagutil.FlagKindBool, Optional: true, Description: "Set to true to publish despite schema validation errors, failed invariants, or schema changes that invalidate dependent resources. This does not bypass a rejected Custom Hook; use `skipHooks` for that. The caller must have Bypass draft approvals access for Feature Flags, Configs, and Constants in every Project. Otherwise, this field is ignored."},
	{FlagName: "skip-hooks", FieldPath: "Body.SkipHooks", Kind: flagutil.FlagKindBool, Optional: true, Description: "Set to true to publish despite a Custom Hook rejection. This does not bypass schema validation; use `skipSchemaValidation` for that. The caller must have Bypass draft approvals access for Feature Flags, Configs, and Constants in every Project. Otherwise, this field is ignored."},
}

// initSetPropertyCmd initializes the set-property command.
func initSetPropertyCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "set-property",
		Short:   "Set one property of a config draft revision's value",
		Long:    "Stages a single property of this config's own value on the draft, leaving every other property untouched. Prefer this over `PUT .../value` when changing one field: a whole-value write from a stale read silently drops properties someone else added in the meantime.\n\n`null` is a value (it does not remove the property) — use `DELETE .../property` to remove one. Pass `version: \"new\"` to auto-create a draft.",
		Example: "  growthbook config-revisions set-property --key <key> --version-param <value> --property <value> --value <value>",
		RunE:    runSetPropertyCmd,
		Aliases: []string{"spro"},
	}
	flagutil.RegisterFlags(cmd, setPropertyCmdMeta)
	if err := flagutil.ValidateMeta[operations.PutConfigRevisionPropertyRequest](setPropertyCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for set-property: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runSetPropertyCmd executes the set-property command.
func runSetPropertyCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, setPropertyCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, setPropertyCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PutConfigRevisionPropertyRequest](cmd, setPropertyCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.ConfigRevisions.SetProperty(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
