// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package savedgroups

import (
	"fmt"
	"github.com/growthbook/cli/v2/internal/client"
	"github.com/growthbook/cli/v2/internal/flagutil"
	"github.com/growthbook/cli/v2/internal/interactive"
	"github.com/growthbook/cli/v2/internal/output"
	"github.com/growthbook/cli/v2/internal/sdk"
	"github.com/growthbook/cli/v2/internal/sdk/models/operations"
	"github.com/growthbook/cli/v2/internal/usage"
	"github.com/spf13/cobra"
)

var archiveSavedGroupCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "The id of the requested resource [required]"},
	{FlagName: "ignore-warnings", FieldPath: "Body.IgnoreWarnings", Kind: flagutil.FlagKindBool, Optional: true, Description: "Set to true to acknowledge the warnings listed in a blocked response and continue. This covers experiment guards, locked dependents, and references affected by an archive. When the organization treats schema failures as warnings, it also covers schema and invariant warnings. It never bypasses a rejected Custom Hook. On revision publish endpoints, it can also force-publish an out-of-date draft when the caller has Bypass draft approvals access."},
}

// initArchiveSavedGroupCmd initializes the archive-saved-group command.
func initArchiveSavedGroupCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "archive",
		Short:   "Archive a single saved group",
		Long:    "Archives a Saved Group. If it is still referenced by a Feature Flag, experiment, or another Saved Group, the API returns 422 with the affected references. Send `\"ignoreWarnings\": true` to acknowledge those references and continue. When approval is required, create and publish an archive revision instead, or use a caller with Bypass draft approvals access. A successful response lists any skipped gates in `bypassedGates`.",
		Example: "  growthbook saved-groups archive --id <id>",
		RunE:    runArchiveSavedGroupCmd,
	}
	flagutil.RegisterFlags(cmd, archiveSavedGroupCmdMeta)
	if err := flagutil.ValidateMeta[operations.ArchiveSavedGroupRequest](archiveSavedGroupCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for archive-saved-group: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runArchiveSavedGroupCmd executes the archive-saved-group command.
func runArchiveSavedGroupCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, archiveSavedGroupCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, archiveSavedGroupCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ArchiveSavedGroupRequest](cmd, archiveSavedGroupCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.SavedGroups.ArchiveSavedGroup(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
