// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f0309a57bffc

package savedgroups

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var listSavedGroupsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "limit", Shorthand: "l", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 10, Description: "The number of items to return"},
	{FlagName: "offset", FieldPath: "Offset", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, Description: "How many items to skip (use in conjunction with limit for pagination)"},
}

// initListSavedGroupsCmd initializes the list-saved-groups command.
func initListSavedGroupsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list",
		Short:   "Get all saved group",
		Long:    "Get all saved group",
		Example: "  growthbook saved-groups list",
		RunE:    runListSavedGroupsCmd,
	}
	flagutil.RegisterFlags(cmd, listSavedGroupsCmdMeta)
	if err := flagutil.ValidateMeta[operations.ListSavedGroupsRequest](listSavedGroupsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list-saved-groups: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListSavedGroupsCmd executes the list-saved-groups command.
func runListSavedGroupsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, listSavedGroupsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, listSavedGroupsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ListSavedGroupsRequest](cmd, listSavedGroupsCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.SavedGroups.ListSavedGroups(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
