// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package savedgroups

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var unarchiveSavedGroupCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "The id of the requested resource [required]"},
}

// initUnarchiveSavedGroupCmd initializes the unarchive-saved-group command.
func initUnarchiveSavedGroupCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "unarchive",
		Short:   "Unarchive a single saved group",
		Long:    "Unarchive a single saved group",
		Example: "  growthbook saved-groups unarchive --id <id>",
		RunE:    runUnarchiveSavedGroupCmd,
	}
	flagutil.RegisterFlags(cmd, unarchiveSavedGroupCmdMeta)
	if err := flagutil.ValidateMeta[operations.UnarchiveSavedGroupRequest](unarchiveSavedGroupCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for unarchive-saved-group: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runUnarchiveSavedGroupCmd executes the unarchive-saved-group command.
func runUnarchiveSavedGroupCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, unarchiveSavedGroupCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, unarchiveSavedGroupCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.UnarchiveSavedGroupRequest](cmd, unarchiveSavedGroupCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.SavedGroups.UnarchiveSavedGroup(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
