// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package attributes

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var updateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "property", FieldPath: "Property", Kind: flagutil.FlagKindString, Required: true, Description: "The attribute property [required]"},
	{FlagName: "datatype", FieldPath: "Body.Datatype", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"boolean", "string", "number", "secureString", "enum", "string[]", "number[]", "secureString[]"}, Description: "The attribute datatype (options: boolean, string, number, secureString, enum, string[], number[], secureString[])"},
	{FlagName: "description", FieldPath: "Body.Description", Kind: flagutil.FlagKindString, Optional: true, Description: "The description of the new attribute"},
	{FlagName: "archived", Shorthand: "a", FieldPath: "Body.Archived", Kind: flagutil.FlagKindBool, Optional: true, Description: "The attribute is archived"},
	{FlagName: "hash-attribute", FieldPath: "Body.HashAttribute", Kind: flagutil.FlagKindBool, Optional: true, Description: "Shall the attribute be hashed"},
	{FlagName: "enum", Shorthand: "e", FieldPath: "Body.Enum", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "format-param", Shorthand: "f", FieldPath: "Body.Format", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"", "version", "date", "isoCountryCode"}, Description: "The attribute's format (options: , version, date, isoCountryCode)"},
	{FlagName: "projects", FieldPath: "Body.Projects", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "list of values"},
	{FlagName: "tags", Shorthand: "t", FieldPath: "Body.Tags", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "list of values"},
}

// initUpdateCmd initializes the update command.
func initUpdateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "update",
		Short:   "Update an attribute",
		Long:    "Update an attribute",
		Example: "  growthbook attributes update --property <value>",
		RunE:    runUpdateCmd,
	}
	flagutil.RegisterFlags(cmd, updateCmdMeta)
	if err := flagutil.ValidateMeta[operations.PutAttributeRequest](updateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for update: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runUpdateCmd executes the update command.
func runUpdateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, updateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, updateCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PutAttributeRequest](cmd, updateCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Attributes.Update(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
