// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package autoruns

import (
	"github.com/growthbook/cli/v2/internal/client"
	"github.com/growthbook/cli/v2/internal/output"
	"github.com/growthbook/cli/v2/internal/sdk"
	"github.com/growthbook/cli/v2/internal/sdk/models/operations"
	"github.com/growthbook/cli/v2/internal/usage"
	"github.com/spf13/cobra"
)

// initListAutoRunsCmd initializes the list-auto-runs command.
func initListAutoRunsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list",
		Short:   "Get all autoRuns",
		Long:    "Get all autoRuns",
		Example: "  growthbook auto-runs list",
		RunE:    runListAutoRunsCmd,
	}
	parent.AddCommand(cmd)
	return nil
}

// runListAutoRunsCmd executes the list-auto-runs command.
func runListAutoRunsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.AutoRuns.ListAutoRuns(cmd.Context(), sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
