// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package autoruns

import (
	"github.com/growthbook/cli/v2/internal/usage"
	"github.com/spf13/cobra"
)

func InitAutoRunsRoot(parent *cobra.Command) error {
	var AutoRunsCmd = &cobra.Command{
		Use:   "auto-runs",
		Short: "Operations for auto-runs",
		Long:  "Operations for auto-runs",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
		Aliases: []string{"ar"},
	}

	if err := initCreateAutoRunCmd(AutoRunsCmd); err != nil {
		return err
	}

	if err := initListAutoRunsCmd(AutoRunsCmd); err != nil {
		return err
	}

	if err := initGetAutoRunCmd(AutoRunsCmd); err != nil {
		return err
	}

	if err := initUpdateAutoRunCmd(AutoRunsCmd); err != nil {
		return err
	}

	if err := initAppendAutoRunArtifactCmd(AutoRunsCmd); err != nil {
		return err
	}

	parent.AddCommand(AutoRunsCmd)
	return nil
}
