// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package constantrevisions

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var getConstantRevisionMergeStatusCmdMeta = []flagutil.FlagMeta{
	{FlagName: "key", Shorthand: "k", FieldPath: "Key", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "version-param", Shorthand: "v", FieldPath: "Version", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initGetConstantRevisionMergeStatusCmd initializes the get-constant-revision-merge-status command.
func initGetConstantRevisionMergeStatusCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-constant-revision-merge-status",
		Short:   "Get merge status for a draft revision",
		Long:    "Runs a dry-run merge of the draft against the current live constant and returns any conflicts. Use this before publishing to preview changes and detect conflicting edits.",
		Example: "  growthbook constant-revisions get-constant-revision-merge-status --key <key> --version-param <value>",
		RunE:    runGetConstantRevisionMergeStatusCmd,
		Aliases: []string{"gcrms"},
	}
	flagutil.RegisterFlags(cmd, getConstantRevisionMergeStatusCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetConstantRevisionMergeStatusRequest](getConstantRevisionMergeStatusCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-constant-revision-merge-status: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetConstantRevisionMergeStatusCmd executes the get-constant-revision-merge-status command.
func runGetConstantRevisionMergeStatusCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getConstantRevisionMergeStatusCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getConstantRevisionMergeStatusCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetConstantRevisionMergeStatusRequest](cmd, getConstantRevisionMergeStatusCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.ConstantRevisions.GetConstantRevisionMergeStatus(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
