// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package constantrevisions

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var getConstantRevisionLatestCmdMeta = []flagutil.FlagMeta{
	{FlagName: "key", Shorthand: "k", FieldPath: "Key", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "mine", Shorthand: "m", FieldPath: "Mine", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=mine"`, Description: "If true, return only the most recent active draft authored by the calling user. Requires a user-scoped API key."},
}

// initGetConstantRevisionLatestCmd initializes the get-constant-revision-latest command.
func initGetConstantRevisionLatestCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-constant-revision-latest",
		Short:   "Get the most recent active draft revision",
		Long:    "Returns the most recently updated open (non-merged, non-discarded) revision for the constant. Returns 404 if there is no active draft. Pass `mine=true` to restrict to drafts authored by the calling user (requires a user-scoped API key).",
		Example: "  growthbook constant-revisions get-constant-revision-latest --key <key>",
		RunE:    runGetConstantRevisionLatestCmd,
		Aliases: []string{"gcrl"},
	}
	flagutil.RegisterFlags(cmd, getConstantRevisionLatestCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetConstantRevisionLatestRequest](getConstantRevisionLatestCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-constant-revision-latest: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetConstantRevisionLatestCmd executes the get-constant-revision-latest command.
func runGetConstantRevisionLatestCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getConstantRevisionLatestCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getConstantRevisionLatestCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetConstantRevisionLatestRequest](cmd, getConstantRevisionLatestCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.ConstantRevisions.GetConstantRevisionLatest(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
