// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package constantrevisions

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var setValueCmdMeta = []flagutil.FlagMeta{
	{FlagName: "key", Shorthand: "k", FieldPath: "Key", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "version-param", FieldPath: "Version", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "revision-title", FieldPath: "Body.RevisionTitle", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "revision-comment", FieldPath: "Body.RevisionComment", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "value", FieldPath: "Body.Value", Kind: flagutil.FlagKindString, Optional: true, Description: "The default value (raw string for `string` constants, JSON-encoded for `json` constants)"},
	{FlagName: "environment-values", Shorthand: "e", FieldPath: "Body.EnvironmentValues", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"environmentValues,omitempty"`, Description: "Per-environment value overrides (environment id → value)"},
}

// initSetValueCmd initializes the set-value command.
func initSetValueCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "set-value",
		Short:   "Update the value of a constant draft revision",
		Long:    "Stages a new default `value` and/or per-environment `environmentValues` on the draft. At least one must be supplied. Pass `version: \"new\"` to auto-create a draft. The value must match the constant's type (valid JSON for `json` constants).",
		Example: "  growthbook constant-revisions set-value --key <key> --version-param <value>",
		RunE:    runSetValueCmd,
		Aliases: []string{"sv"},
	}
	flagutil.RegisterFlags(cmd, setValueCmdMeta)
	if err := flagutil.ValidateMeta[operations.PutConstantRevisionValueRequest](setValueCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for set-value: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runSetValueCmd executes the set-value command.
func runSetValueCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, setValueCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, setValueCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PutConstantRevisionValueRequest](cmd, setValueCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.ConstantRevisions.SetValue(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
