// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 260aaa8845ef

package visualchangesets

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var listVisualChangesetsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "The experiment id the visual changesets belong to [required]"},
}

// initListVisualChangesetsCmd initializes the list-visual-changesets command.
func initListVisualChangesetsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list",
		Short:   "Get all visual changesets",
		Long:    "Get all visual changesets",
		Example: "  growthbook visual-changesets list --id <id>",
		RunE:    runListVisualChangesetsCmd,
	}
	flagutil.RegisterFlags(cmd, listVisualChangesetsCmdMeta)
	if err := flagutil.ValidateMeta[operations.ListVisualChangesetsRequest](listVisualChangesetsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list-visual-changesets: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListVisualChangesetsCmd executes the list-visual-changesets command.
func runListVisualChangesetsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, listVisualChangesetsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, listVisualChangesetsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ListVisualChangesetsRequest](cmd, listVisualChangesetsCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.VisualChangesets.ListVisualChangesets(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
