// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package visualchangesets

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var updateVisualChangeCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "The id of the requested resource [required]"},
	{FlagName: "visual-change-id", FieldPath: "VisualChangeID", Kind: flagutil.FlagKindString, Required: true, Description: "Specify a specific visual change [required]"},
	{FlagName: "description", FieldPath: "Body.Description", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "css", Shorthand: "c", FieldPath: "Body.CSS", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "js", Shorthand: "j", FieldPath: "Body.Js", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "variation", FieldPath: "Body.Variation", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "dom-mutations", FieldPath: "Body.DomMutations", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"domMutations,omitempty"`, Description: "list of values"},
	{FlagName: "additional-properties", Shorthand: "a", FieldPath: "Body.AdditionalProperties", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `additionalProperties:"true" json:"-"`, Description: "value"},
}

// initUpdateVisualChangeCmd initializes the update-visual-change command.
func initUpdateVisualChangeCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "update-visual-change",
		Short:   "Update a visual change for a visual changeset",
		Long:    "Update a visual change for a visual changeset",
		Example: "  growthbook visual-changesets update-visual-change --id <id> --visual-change-id <id>",
		RunE:    runUpdateVisualChangeCmd,
		Aliases: []string{"uvc"},
	}
	flagutil.RegisterFlags(cmd, updateVisualChangeCmdMeta)
	if err := flagutil.ValidateMeta[operations.PutVisualChangeRequest](updateVisualChangeCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for update-visual-change: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runUpdateVisualChangeCmd executes the update-visual-change command.
func runUpdateVisualChangeCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, updateVisualChangeCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, updateVisualChangeCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PutVisualChangeRequest](cmd, updateVisualChangeCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.VisualChangesets.UpdateVisualChange(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
