// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package featuresv2

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var postFeatureV2CmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "A unique key name for the feature. Feature keys can only include letters, numbers, hyphens, and underscores. [required]"},
	{FlagName: "archived", Shorthand: "a", FieldPath: "Archived", Kind: flagutil.FlagKindBool, Optional: true, Description: "boolean flag"},
	{FlagName: "description", FieldPath: "Description", Kind: flagutil.FlagKindString, Optional: true, Description: "Description of the feature"},
	{FlagName: "owner", FieldPath: "Owner", Kind: flagutil.FlagKindString, Optional: true, Description: "The userId or email address of the owner. If an email address is provided, it will be used to look up the userId of the matching organization member. If an ID is provided, it will be validated as existing in the organization. When omitted, it defaults to the user associated with the request's Personal Access Token (PAT), if one is being used."},
	{FlagName: "project", FieldPath: "Project", Kind: flagutil.FlagKindString, Optional: true, Description: "An associated project ID"},
	{FlagName: "value-type", Shorthand: "v", FieldPath: "ValueType", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"boolean", "string", "number", "json"}, Description: "The data type of the feature payload. Boolean by default. (options: boolean, string, number, json) [required]"},
	{FlagName: "default-value", FieldPath: "DefaultValue", Kind: flagutil.FlagKindString, Required: true, Description: "Default value when feature is enabled. Type must match `valueType`. [required]"},
	{FlagName: "tags", Shorthand: "t", FieldPath: "Tags", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "List of associated tags"},
	{FlagName: "rules", Shorthand: "r", FieldPath: "Rules", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"rules,omitempty"`, Description: "Feature rules. Each rule carries its own environment scope via `allEnvironments` / `environments`."},
	{FlagName: "environments", Shorthand: "e", FieldPath: "Environments", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"environments,omitempty"`, Description: "Per-environment enabled state. V2 rules are specified on the top-level `rules` field."},
	{FlagName: "prerequisites", FieldPath: "Prerequisites", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Feature IDs. Each feature must evaluate to `true`"},
	{FlagName: "json-schema", Shorthand: "j", FieldPath: "JSONSchema", Kind: flagutil.FlagKindString, Optional: true, Description: "Use JSON schema to validate the payload of a JSON-type feature value (enterprise only)."},
	{FlagName: "custom-fields", Shorthand: "c", FieldPath: "CustomFields", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"customFields,omitempty"`, Description: "value"},
}

// initPostFeatureV2Cmd initializes the post-feature-v2 command.
func initPostFeatureV2Cmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "post-feature-v2",
		Short:   "Create a single feature",
		Long:    "Creates a new feature. Rules are supplied as a top-level `rules` array; each rule includes `allEnvironments` / `environments` scope fields.",
		Example: "  growthbook features-v2 post-feature-v2 --id <id> --value-type number --default-value <value>",
		RunE:    runPostFeatureV2Cmd,
		Aliases: []string{"pfv"},
	}
	flagutil.RegisterFlags(cmd, postFeatureV2CmdMeta)
	if err := flagutil.ValidateMeta[operations.PostFeatureV2Request](postFeatureV2CmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for post-feature-v2: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runPostFeatureV2Cmd executes the post-feature-v2 command.
func runPostFeatureV2Cmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, postFeatureV2CmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, postFeatureV2CmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[operations.PostFeatureV2Request](cmd, postFeatureV2CmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.FeaturesV2.PostFeatureV2(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
