// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7d9fdb8efa40

package facttables

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var getAggregatedFactTablesCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "The id of the requested resource [required]"},
}

// initGetAggregatedFactTablesCmd initializes the get-aggregated-fact-tables command.
func initGetAggregatedFactTablesCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-aggregated",
		Short:   "Get the materialization status of a fact table's shared daily aggregated tables",
		Long:    "Get the materialization status of a fact table's shared daily aggregated tables",
		Example: "  growthbook fact-tables get-aggregated --id <id>",
		RunE:    runGetAggregatedFactTablesCmd,
		Aliases: []string{"ga"},
	}
	flagutil.RegisterFlags(cmd, getAggregatedFactTablesCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetAggregatedFactTablesRequest](getAggregatedFactTablesCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-aggregated-fact-tables: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetAggregatedFactTablesCmd executes the get-aggregated-fact-tables command.
func runGetAggregatedFactTablesCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getAggregatedFactTablesCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getAggregatedFactTablesCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetAggregatedFactTablesRequest](cmd, getAggregatedFactTablesCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.FactTables.GetAggregatedFactTables(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
