// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4ffdd13b8e55

package facttables

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var postFactTableFilterCmdMeta = []flagutil.FlagMeta{
	{FlagName: "fact-table-id", Shorthand: "f", FieldPath: "FactTableID", Kind: flagutil.FlagKindString, Required: true, Description: "Specify a specific fact table [required]"},
	{FlagName: "name", Shorthand: "n", FieldPath: "Body.Name", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "description", FieldPath: "Body.Description", Kind: flagutil.FlagKindString, Optional: true, Description: "Description of the fact table filter"},
	{FlagName: "value", Shorthand: "v", FieldPath: "Body.Value", Kind: flagutil.FlagKindString, Required: true, Description: "The SQL expression for this filter. [required]"},
	{FlagName: "managed-by", Shorthand: "m", FieldPath: "Body.ManagedBy", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"", "api"}, Description: "Set this to \"api\" to disable editing in the GrowthBook UI. Before you do this, the Fact Table itself must also be marked as \"api\" (options: , api)"},
}

// initPostFactTableFilterCmd initializes the post-fact-table-filter command.
func initPostFactTableFilterCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "post-fact-table-filter",
		Short:   "Create a single fact table filter",
		Long:    "Create a single fact table filter",
		Example: "  growthbook fact-tables post-fact-table-filter --fact-table-id <id> --name <value> --value country = 'US'",
		RunE:    runPostFactTableFilterCmd,
		Aliases: []string{"pftf"},
	}
	flagutil.RegisterFlags(cmd, postFactTableFilterCmdMeta)
	if err := flagutil.ValidateMeta[operations.PostFactTableFilterRequest](postFactTableFilterCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for post-fact-table-filter: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runPostFactTableFilterCmd executes the post-fact-table-filter command.
func runPostFactTableFilterCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, postFactTableFilterCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, postFactTableFilterCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PostFactTableFilterRequest](cmd, postFactTableFilterCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.FactTables.PostFactTableFilter(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
