// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package main

import (
	"fmt"
	"os"

	"github.com/growthbook/cli/internal/cli"
	"github.com/growthbook/cli/internal/output"
)

// version and buildTime can be set at build time using Go linker flags:
//
//	go build -ldflags "-X main.version=x.y.z -X main.buildTime=$(date -u +%Y-%m-%dT%H:%M:%SZ)" ./cmd/growthbook
var version string
var buildTime string

func main() {
	if version != "" {
		cli.Version = version
	}
	if buildTime != "" {
		cli.BuildTime = buildTime
	}

	if err := cli.Execute(); err != nil {
		// output.Error already prints a formatted message for the errors it
		// handles; only print here for errors that weren't already surfaced.
		if !output.IsDisplayed(err) {
			fmt.Fprintln(os.Stderr, err)
		}
		os.Exit(1)
	}
}
