// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package contextualbandits

import (
	"fmt"
	"github.com/growthbook/cli/v2/internal/client"
	"github.com/growthbook/cli/v2/internal/flagutil"
	"github.com/growthbook/cli/v2/internal/interactive"
	"github.com/growthbook/cli/v2/internal/output"
	"github.com/growthbook/cli/v2/internal/sdk"
	"github.com/growthbook/cli/v2/internal/sdk/models/operations"
	"github.com/growthbook/cli/v2/internal/usage"
	"github.com/spf13/cobra"
)

var deleteLinkedFeatureCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "The Contextual Bandit id [required]"},
	{FlagName: "feature-id", Shorthand: "f", FieldPath: "FeatureID", Kind: flagutil.FlagKindString, Required: true, Description: "The linked feature id [required]"},
	{FlagName: "auto-publish", Shorthand: "a", FieldPath: "AutoPublish", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=autoPublish"`, Description: "Publish the resulting revision immediately instead of leaving it as a draft."},
	{FlagName: "draft-version", FieldPath: "DraftVersion", Kind: flagutil.FlagKindInt64, Optional: true, Description: "Remove the rule from this existing draft revision instead of live. Required when the rule hasn't been published yet — omitting it targets the live revision, which has nothing to remove."},
}

// initDeleteLinkedFeatureCmd initializes the delete-linked-feature command.
func initDeleteLinkedFeatureCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "delete-linked-feature",
		Short:   "Unlink a feature from a Contextual Bandit",
		Long:    "Removes every `contextual-bandit-ref` rule pointing at this contextual bandit from the feature and drops the feature from the bandit's linked-feature list. The rule removal lands in a draft revision unless `autoPublish` is set. When the feature has no such rule left, only the linkage is cleared.",
		Example: "  growthbook contextual-bandits delete-linked-feature --id <id> --feature-id <id>",
		RunE:    runDeleteLinkedFeatureCmd,
		Aliases: []string{"dlf"},
	}
	flagutil.RegisterFlags(cmd, deleteLinkedFeatureCmdMeta)
	if err := flagutil.ValidateMeta[operations.DeleteContextualBanditLinkedFeatureRequest](deleteLinkedFeatureCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for delete-linked-feature: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runDeleteLinkedFeatureCmd executes the delete-linked-feature command.
func runDeleteLinkedFeatureCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, deleteLinkedFeatureCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, deleteLinkedFeatureCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.DeleteContextualBanditLinkedFeatureRequest](cmd, deleteLinkedFeatureCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.ContextualBandits.DeleteLinkedFeature(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
