// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package contextualbandits

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var getContextualBanditSnapshotCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "The Contextual Bandit id [required]"},
	{FlagName: "snapshot-id", Shorthand: "s", FieldPath: "SnapshotID", Kind: flagutil.FlagKindString, Required: true, Description: "The snapshot id [required]"},
}

// initGetContextualBanditSnapshotCmd initializes the get-contextual-bandit-snapshot command.
func initGetContextualBanditSnapshotCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-contextual-bandit-snapshot",
		Short:   "Get a single Contextual Bandit snapshot",
		Long:    "Get a single Contextual Bandit snapshot",
		Example: "  growthbook contextual-bandits get-contextual-bandit-snapshot --id <id> --snapshot-id <id>",
		RunE:    runGetContextualBanditSnapshotCmd,
		Aliases: []string{"gcbs"},
	}
	flagutil.RegisterFlags(cmd, getContextualBanditSnapshotCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetContextualBanditSnapshotRequest](getContextualBanditSnapshotCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-contextual-bandit-snapshot: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetContextualBanditSnapshotCmd executes the get-contextual-bandit-snapshot command.
func runGetContextualBanditSnapshotCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getContextualBanditSnapshotCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getContextualBanditSnapshotCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetContextualBanditSnapshotRequest](cmd, getContextualBanditSnapshotCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.ContextualBandits.GetContextualBanditSnapshot(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
