// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package contextualbandits

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var listContextualBanditsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "project-id", Shorthand: "p", FieldPath: "ProjectID", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "datasource-id", FieldPath: "DatasourceID", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "tracking-key", Shorthand: "t", FieldPath: "TrackingKey", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
}

// initListContextualBanditsCmd initializes the list-contextual-bandits command.
func initListContextualBanditsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list",
		Short:   "Get all contextualBandits",
		Long:    "Get all contextualBandits",
		Example: "  growthbook contextual-bandits list",
		RunE:    runListContextualBanditsCmd,
	}
	flagutil.RegisterFlags(cmd, listContextualBanditsCmdMeta)
	if err := flagutil.ValidateMeta[operations.ListContextualBanditsRequest](listContextualBanditsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list-contextual-bandits: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListContextualBanditsCmd executes the list-contextual-bandits command.
func runListContextualBanditsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, listContextualBanditsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, listContextualBanditsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ListContextualBanditsRequest](cmd, listContextualBanditsCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.ContextualBandits.ListContextualBandits(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
