// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package featurerevisions

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var getFeatureRevisionDiffCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "version-param", Shorthand: "v", FieldPath: "Version", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "format-param", Shorthand: "f", FieldPath: "Format", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"minimal", "full"}, Description: "`minimal` (default) returns only what changed, with id-keyed arrays bucketed into added/removed/modified items. `full` returns the complete before/after content of the revision. (options: minimal, full)"},
	{FlagName: "base", Shorthand: "b", FieldPath: "Base", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=base"`, Description: "Compare against: `baseVersion` (default — the revision's own `baseVersion`, matches the in-app review view), `live` (the currently-live revision), or an integer version (an arbitrary historical revision)."},
}

// initGetFeatureRevisionDiffCmd initializes the get-feature-revision-diff command.
func initGetFeatureRevisionDiffCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-feature-revision-diff",
		Short:   "Diff a revision against another revision",
		Long:    "Returns a schema-keyed JSON diff between this revision and a baseline. The same shapes the in-app review surface produces under `Copy as → Minimal JSON` / `Full JSON`: `minimal` lists only what changed (with id-keyed arrays bucketed into added/removed/modified items and reorder detection), while `full` returns the complete before/after content of the revision. Lifecycle fields (version, status, comment, date, createdBy, publishedBy) are excluded from the diff body and echoed via `from` / `to` instead. Defaults to diffing against the revision's own `baseVersion`; pass `?base=live` to diff against the current live revision, or `?base=<version>` for an arbitrary historical one.",
		Example: "  growthbook feature-revisions get-feature-revision-diff --id <id> --version-param <value>",
		RunE:    runGetFeatureRevisionDiffCmd,
		Aliases: []string{"gfrd"},
	}
	flagutil.RegisterFlags(cmd, getFeatureRevisionDiffCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetFeatureRevisionDiffV2Request](getFeatureRevisionDiffCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-feature-revision-diff: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetFeatureRevisionDiffCmd executes the get-feature-revision-diff command.
func runGetFeatureRevisionDiffCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getFeatureRevisionDiffCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getFeatureRevisionDiffCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetFeatureRevisionDiffV2Request](cmd, getFeatureRevisionDiffCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.FeatureRevisions.GetFeatureRevisionDiff(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
