// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a2aa8779a1fb

package featurerevisions

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var postFeatureRevisionRebaseCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "version-param", Shorthand: "v", FieldPath: "Version", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "conflict-resolutions", Shorthand: "c", FieldPath: "Body.ConflictResolutions", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"conflictResolutions,omitempty"`, Description: "value"},
}

// initPostFeatureRevisionRebaseCmd initializes the post-feature-revision-rebase command.
func initPostFeatureRevisionRebaseCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "post-feature-revision-rebase",
		Short:   "Rebase a draft revision onto the current live version",
		Long:    "DEPRECATED: This will be removed in a future release, please migrate away from it as soon as possible\n\n**Deprecated.** Use [POST /v2/features/:id/revisions/:version/rebase](#operation/postFeatureRevisionRebaseV2) instead.\n\nUpdates the draft's base revision to match the currently-live revision, applying the draft's changes on top. Supply `conflictResolutions` to resolve any conflicting fields.\n\n**Conflict key format changed for v1 clients.** Rules now merge as a single flat array, so the per-rule `envName.ruleId` keys used by older clients are no longer recognized. Valid keys: `defaultValue`, `rules`, `prerequisites`, `archived`, `holdout`, and `environmentsEnabled.<env>`. Unrecognized keys are ignored; unresolved conflicts respond with `409`.",
		Example: "  growthbook feature-revisions post-feature-revision-rebase --id <id> --version-param 287768",
		RunE:    runPostFeatureRevisionRebaseCmd,
		Aliases: []string{"pfrr"},
	}
	flagutil.RegisterFlags(cmd, postFeatureRevisionRebaseCmdMeta)
	if err := flagutil.ValidateMeta[operations.PostFeatureRevisionRebaseRequest](postFeatureRevisionRebaseCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for post-feature-revision-rebase: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runPostFeatureRevisionRebaseCmd executes the post-feature-revision-rebase command.
func runPostFeatureRevisionRebaseCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, postFeatureRevisionRebaseCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, postFeatureRevisionRebaseCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PostFeatureRevisionRebaseRequest](cmd, postFeatureRevisionRebaseCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.FeatureRevisions.PostFeatureRevisionRebase(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
