// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package featurerevisions

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var postFeatureRevisionCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "override-draft-limit", FieldPath: "OverrideDraftLimit", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=overrideDraftLimit"`, Description: "If the organization caps concurrent drafts per feature (`maxConcurrentDrafts` setting), requests at or over the cap are rejected with a 409. Pass `true` to create the draft anyway."},
	{FlagName: "comment", Shorthand: "c", FieldPath: "Body.Comment", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "title", Shorthand: "t", FieldPath: "Body.Title", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
}

// initPostFeatureRevisionCmd initializes the post-feature-revision command.
func initPostFeatureRevisionCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "post",
		Short:   "Create a draft revision",
		Long:    "DEPRECATED: This will be removed in a future release, please migrate away from it as soon as possible\n\n**Deprecated.** Use [POST /v2/features/:id/revisions](#operation/postFeatureRevisionV2) instead.\n\nCreates a new draft revision branched from the current live revision. A feature can have multiple concurrent drafts; use this to start an isolated line of edits.",
		Example: "  growthbook feature-revisions post --id <id>",
		RunE:    runPostFeatureRevisionCmd,
	}
	flagutil.RegisterFlags(cmd, postFeatureRevisionCmdMeta)
	if err := flagutil.ValidateMeta[operations.PostFeatureRevisionRequest](postFeatureRevisionCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for post-feature-revision: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runPostFeatureRevisionCmd executes the post-feature-revision command.
func runPostFeatureRevisionCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, postFeatureRevisionCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, postFeatureRevisionCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PostFeatureRevisionRequest](cmd, postFeatureRevisionCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.FeatureRevisions.PostFeatureRevision(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
