// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package featurerevisions

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var putFeatureRevisionDefaultValueCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "version-param", Shorthand: "v", FieldPath: "Version", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "default-value", FieldPath: "Body.DefaultValue", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "revision-title", FieldPath: "Body.RevisionTitle", Kind: flagutil.FlagKindString, Optional: true, Description: "Title for a newly created draft. Only used when version is \"new\"; ignored for existing revisions."},
	{FlagName: "revision-comment", FieldPath: "Body.RevisionComment", Kind: flagutil.FlagKindString, Optional: true, Description: "Comment for a newly created draft. Only used when version is \"new\"; ignored for existing revisions."},
}

// initPutFeatureRevisionDefaultValueCmd initializes the put-feature-revision-default-value command.
func initPutFeatureRevisionDefaultValueCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "put-feature-revision-default-value",
		Short:   "Set the default value in a draft revision",
		Long:    "Set the default value in a draft revision",
		Example: "  growthbook feature-revisions put-feature-revision-default-value --id <id> --version-param <value> --default-value <value>",
		RunE:    runPutFeatureRevisionDefaultValueCmd,
		Aliases: []string{"pfrdv"},
	}
	flagutil.RegisterFlags(cmd, putFeatureRevisionDefaultValueCmdMeta)
	if err := flagutil.ValidateMeta[operations.PutFeatureRevisionDefaultValueV2Request](putFeatureRevisionDefaultValueCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for put-feature-revision-default-value: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runPutFeatureRevisionDefaultValueCmd executes the put-feature-revision-default-value command.
func runPutFeatureRevisionDefaultValueCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, putFeatureRevisionDefaultValueCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, putFeatureRevisionDefaultValueCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PutFeatureRevisionDefaultValueV2Request](cmd, putFeatureRevisionDefaultValueCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.FeatureRevisions.PutFeatureRevisionDefaultValue(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
