// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package featurerevisions

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var updateRuleCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "version-param", Shorthand: "v", FieldPath: "Version", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "rule-id", FieldPath: "RuleID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "skip-schema-validation", FieldPath: "SkipSchemaValidation", Kind: flagutil.FlagKindBool, Optional: true, Description: "Skip JSON-schema validation of the value(s) being written. Only honored for callers with org-wide bypass authority (the `bypassApprovalChecks` permission on all projects); ignored otherwise. Validation is enforced by default."},
	{FlagName: "ignore-warnings", FieldPath: "IgnoreWarnings", Kind: flagutil.FlagKindBool, Optional: true, Description: "Proceed despite soft validation warnings — e.g. publishing values that don't match the schema when the org has `blockPublishOnSchemaError` disabled (warn mode)."},
	{FlagName: "rule", FieldPath: "Body.Rule", Kind: flagutil.FlagKindJSON, Required: true, Annotations: `json:"rule"`, Description: "[required]"},
	{FlagName: "ramp-schedule", FieldPath: "Body.RampSchedule", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"rampSchedule,omitempty"`, Description: "Multi-step ramp schedule for force/rollout rules. Not supported for experiment-ref or safe-rollout rules. Mutually exclusive with `schedule`."},
	{FlagName: "schedule", FieldPath: "Body.Schedule", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"schedule,omitempty"`, Description: "Simple start/end date window. For force/rollout rules this manages a standalone ramp action; for experiment-ref/safe-rollout rules this updates legacy schedule fields on the rule. Mutually exclusive with `rampSchedule`."},
	{FlagName: "revision-title", FieldPath: "Body.RevisionTitle", Kind: flagutil.FlagKindString, Optional: true, Description: "Title for a newly created draft. Only used when version is \"new\"; ignored for existing revisions."},
	{FlagName: "revision-comment", FieldPath: "Body.RevisionComment", Kind: flagutil.FlagKindString, Optional: true, Description: "Comment for a newly created draft. Only used when version is \"new\"; ignored for existing revisions."},
}

// initUpdateRuleCmd initializes the update-rule command.
func initUpdateRuleCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "update-rule",
		Short:   "Update a rule in a draft revision",
		Long:    "Patches fields on an existing rule (identified by `ruleId`). The rule `type` cannot be changed. Scope can be updated via `allEnvironments` / `environments` patch fields.\n\n**Scheduling:** For `force` and `rollout` rules, update the schedule via `rampSchedule` (multi-step ramp) or `schedule` (simple start/end window) — these manage standalone ramp actions and set `pendingRamp: \"create\"` on the rule. For `experiment-ref` and `safe-rollout` rules, only `schedule` is supported and updates legacy schedule fields on the rule itself (`rampSchedule` is not available for these rule types).",
		Example: "  growthbook feature-revisions update-rule --id <id> --version-param <value> --rule-id <id> --rule '{}'",
		RunE:    runUpdateRuleCmd,
		Aliases: []string{"uru"},
	}
	flagutil.RegisterFlags(cmd, updateRuleCmdMeta)
	if err := flagutil.ValidateMeta[operations.PutFeatureRevisionRuleV2Request](updateRuleCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for update-rule: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runUpdateRuleCmd executes the update-rule command.
func runUpdateRuleCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, updateRuleCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, updateRuleCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PutFeatureRevisionRuleV2Request](cmd, updateRuleCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.FeatureRevisions.UpdateRule(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
