// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package customhooks

import (
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitCustomHooksRoot(parent *cobra.Command) error {
	var CustomHooksCmd = &cobra.Command{
		Use:   "custom-hooks",
		Short: "Sandboxed JavaScript validation hooks that run when features, configs, or their revisions are saved or published",
		Long:  "Sandboxed JavaScript validation hooks that run when features, configs, or their revisions are saved or published. Throwing an Error blocks the save; `addWarning(msg)` raises a soft warning. Hooks are scoped by projects, or pinned to a single feature/config via `entityType`/`entityId`; a config-scoped hook also runs for every config inheriting from it (its whole descendant lineage). Scope can be retargeted on update (or cleared with nulls). Requires an enterprise plan; not available on GrowthBook Cloud.",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
		Aliases: []string{"ch"},
	}

	if err := initListCustomHooksCmd(CustomHooksCmd); err != nil {
		return err
	}

	if err := initPostCustomHookCmd(CustomHooksCmd); err != nil {
		return err
	}

	if err := initTestCustomHookCmd(CustomHooksCmd); err != nil {
		return err
	}

	if err := initGetCustomHookCmd(CustomHooksCmd); err != nil {
		return err
	}

	if err := initUpdateCustomHookCmd(CustomHooksCmd); err != nil {
		return err
	}

	if err := initDeleteCustomHookCmd(CustomHooksCmd); err != nil {
		return err
	}

	if err := initListCustomHookHistoryCmd(CustomHooksCmd); err != nil {
		return err
	}

	if err := initRevertCustomHookCmd(CustomHooksCmd); err != nil {
		return err
	}

	parent.AddCommand(CustomHooksCmd)
	return nil
}
