// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4e644d3c0a16

package cli

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var postVisualEditorAddVariantCmdMeta = []flagutil.FlagMeta{
	{FlagName: "visual-changeset-id", Shorthand: "v", FieldPath: "VisualChangesetID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "name", Shorthand: "n", FieldPath: "Name", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
}

// initPostVisualEditorAddVariantCmd initializes the post-visual-editor-add-variant command.
func initPostVisualEditorAddVariantCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "post-visual-editor-add-variant",
		Short:   "Post Visual Editor Add Variant",
		Long:    "Post Visual Editor Add Variant",
		Example: "  growthbook growthbook post-visual-editor-add-variant --visual-changeset-id <id>",
		RunE:    runPostVisualEditorAddVariantCmd,
		Aliases: []string{"pveav"},
	}
	flagutil.RegisterFlags(cmd, postVisualEditorAddVariantCmdMeta)
	if err := flagutil.ValidateMeta[operations.PostVisualEditorAddVariantRequest](postVisualEditorAddVariantCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for post-visual-editor-add-variant: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runPostVisualEditorAddVariantCmd executes the post-visual-editor-add-variant command.
func runPostVisualEditorAddVariantCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, postVisualEditorAddVariantCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, postVisualEditorAddVariantCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[operations.PostVisualEditorAddVariantRequest](cmd, postVisualEditorAddVariantCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.PostVisualEditorAddVariant(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
