// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package rampschedules

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var approveStepRampScheduleCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initApproveStepRampScheduleCmd initializes the approve-step-ramp-schedule command.
func initApproveStepRampScheduleCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "approve-step",
		Short:   "Approve the current pending-approval step",
		Long:    "Approves the current step on a schedule in `pending-approval` status and\nadvances to the next step. Requires the caller to have feature review\npermissions for the associated feature.",
		Example: "  growthbook ramp-schedules approve-step --id <id>",
		RunE:    runApproveStepRampScheduleCmd,
		Aliases: []string{"as"},
	}
	flagutil.RegisterFlags(cmd, approveStepRampScheduleCmdMeta)
	if err := flagutil.ValidateMeta[operations.ApproveStepRampScheduleRequest](approveStepRampScheduleCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for approve-step-ramp-schedule: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runApproveStepRampScheduleCmd executes the approve-step-ramp-schedule command.
func runApproveStepRampScheduleCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, approveStepRampScheduleCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, approveStepRampScheduleCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ApproveStepRampScheduleRequest](cmd, approveStepRampScheduleCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.RampSchedules.ApproveStepRampSchedule(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
