// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package rampschedules

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var completeRampScheduleCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initCompleteRampScheduleCmd initializes the complete-ramp-schedule command.
func initCompleteRampScheduleCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "complete",
		Short:   "Complete a ramp schedule immediately",
		Long:    "Applies end actions and marks the schedule as `completed`, regardless of\nhow many steps remain.",
		Example: "  growthbook ramp-schedules complete --id <id>",
		RunE:    runCompleteRampScheduleCmd,
	}
	flagutil.RegisterFlags(cmd, completeRampScheduleCmdMeta)
	if err := flagutil.ValidateMeta[operations.CompleteRampScheduleRequest](completeRampScheduleCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for complete-ramp-schedule: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runCompleteRampScheduleCmd executes the complete-ramp-schedule command.
func runCompleteRampScheduleCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, completeRampScheduleCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, completeRampScheduleCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.CompleteRampScheduleRequest](cmd, completeRampScheduleCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.RampSchedules.CompleteRampSchedule(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
