// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ae3ff37c42a2

package codereferences

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var listCodeRefsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "limit", Shorthand: "l", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 10, Description: "The number of items to return"},
	{FlagName: "offset", FieldPath: "Offset", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, Description: "How many items to skip (use in conjunction with limit for pagination)"},
}

// initListCodeRefsCmd initializes the list-code-refs command.
func initListCodeRefsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list-code-refs",
		Short:   "Get list of all code references for the current organization",
		Long:    "Get list of all code references for the current organization",
		Example: "  growthbook code-references list-code-refs",
		RunE:    runListCodeRefsCmd,
		Aliases: []string{"lcr"},
	}
	flagutil.RegisterFlags(cmd, listCodeRefsCmdMeta)
	if err := flagutil.ValidateMeta[operations.ListCodeRefsRequest](listCodeRefsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list-code-refs: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListCodeRefsCmd executes the list-code-refs command.
func runListCodeRefsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, listCodeRefsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, listCodeRefsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ListCodeRefsRequest](cmd, listCodeRefsCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.CodeReferences.ListCodeRefs(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
