// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: cd4fa25d601e

package codereferences

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var postCodeRefsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "delete-missing", FieldPath: "DeleteMissing", Kind: flagutil.FlagKindEnum, Optional: true, HasDefault: true, DefaultStr: "false", EnumValues: []string{"true", "false"}, Description: "Whether to delete code references that are no longer present in the submitted data (options: true, false)"},
	{FlagName: "branch", Shorthand: "b", FieldPath: "Body.Branch", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "repo-name", FieldPath: "Body.RepoName", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "refs", FieldPath: "Body.Refs", Kind: flagutil.FlagKindJSON, Required: true, Annotations: `json:"refs"`, Description: "[required]"},
}

// initPostCodeRefsCmd initializes the post-code-refs command.
func initPostCodeRefsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "post-code-refs",
		Short:   "Submit list of code references",
		Long:    "Submit list of code references",
		Example: "  growthbook code-references post-code-refs --branch <value> --repo-name <value> --refs '[{\"filePath\":\"/bin/shameful_sans_till.xlw\",\"startingLineNumber\":873333,\"lines\":\"<value>\",\"flagKey\":\"<value>\",\"contentHash\":\"<value>\"}]'",
		RunE:    runPostCodeRefsCmd,
		Aliases: []string{"pcr"},
	}
	flagutil.RegisterFlags(cmd, postCodeRefsCmdMeta)
	if err := flagutil.ValidateMeta[operations.PostCodeRefsRequest](postCodeRefsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for post-code-refs: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runPostCodeRefsCmd executes the post-code-refs command.
func runPostCodeRefsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, postCodeRefsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, postCodeRefsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PostCodeRefsRequest](cmd, postCodeRefsCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.CodeReferences.PostCodeRefs(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
