// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package analyticsexplorations

import (
	"fmt"
	"github.com/growthbook/cli/v2/internal/client"
	"github.com/growthbook/cli/v2/internal/flagutil"
	"github.com/growthbook/cli/v2/internal/interactive"
	"github.com/growthbook/cli/v2/internal/output"
	"github.com/growthbook/cli/v2/internal/sdk"
	"github.com/growthbook/cli/v2/internal/sdk/models/operations"
	"github.com/growthbook/cli/v2/internal/usage"
	"github.com/spf13/cobra"
)

var getColumnsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "source", Shorthand: "s", FieldPath: "Source", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"fact_table", "metric"}, Description: "options: fact_table, metric [required]"},
	{FlagName: "fact-table-id", Shorthand: "f", FieldPath: "FactTableID", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "metric-ids", Shorthand: "m", FieldPath: "MetricIds", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "list of values"},
}

// initGetColumnsCmd initializes the get-columns command.
func initGetColumnsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-columns",
		Short:   "List columns available to a Product Analytics exploration",
		Long:    "List columns available to a Product Analytics exploration",
		Example: "  growthbook analytics-explorations get-columns --source metric",
		RunE:    runGetColumnsCmd,
		Aliases: []string{"gc"},
	}
	flagutil.RegisterFlags(cmd, getColumnsCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetProductAnalyticsColumnsRequest](getColumnsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-columns: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetColumnsCmd executes the get-columns command.
func runGetColumnsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getColumnsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getColumnsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetProductAnalyticsColumnsRequest](cmd, getColumnsCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.AnalyticsExplorations.GetColumns(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
