// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package analyticsexplorations

import (
	"fmt"
	"github.com/growthbook/cli/v2/internal/client"
	"github.com/growthbook/cli/v2/internal/flagutil"
	"github.com/growthbook/cli/v2/internal/interactive"
	"github.com/growthbook/cli/v2/internal/output"
	"github.com/growthbook/cli/v2/internal/sdk"
	"github.com/growthbook/cli/v2/internal/sdk/models/operations"
	"github.com/growthbook/cli/v2/internal/usage"
	"github.com/spf13/cobra"
)

var postSQLExplorationCmdMeta = []flagutil.FlagMeta{
	{FlagName: "cache", FieldPath: "Cache", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"preferred", "required", "never"}, Description: "Controls cache behavior for this exploration: `preferred` (default) returns a cached result if one exists, otherwise runs a new query; `never` always runs a new query, ignoring any cached results; `required` only returns a cached result, if none exists returns exploration: null with a message (options: preferred, required, never)"},
	{FlagName: "datasource", FieldPath: "Body.Datasource", Kind: flagutil.FlagKindString, Required: true, Description: "ID of the datasource to query [required]"},
	{FlagName: "dimensions", FieldPath: "Body.Dimensions", Kind: flagutil.FlagKindJSON, Required: true, Annotations: `json:"dimensions"`, Description: "[required]"},
	{FlagName: "chart-type", FieldPath: "Body.ChartType", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"line", "area", "timeseries-table", "table", "bar", "stackedBar", "horizontalBar", "stackedHorizontalBar", "bigNumber"}, Description: "options: line, area, timeseries-table, table, bar, stackedBar, horizontalBar, stackedHorizontalBar, bigNumber [required]"},
	{FlagName: "date-range", FieldPath: "Body.DateRange", Kind: flagutil.FlagKindJSON, Required: true, Annotations: `json:"dateRange"`, Description: "[required]"},
	{FlagName: "show-as", Shorthand: "s", FieldPath: "Body.ShowAs", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"total", "per_unit"}, Description: "options: total, per_unit"},
	{FlagName: "dataset", FieldPath: "Body.Dataset", Kind: flagutil.FlagKindJSON, Required: true, Annotations: `json:"dataset"`, Description: "[required]"},
}

// initPostSqlExplorationCmd initializes the post-sql-exploration command.
func initPostSqlExplorationCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "post-sql-exploration",
		Short:   "Create a SQL based visualization",
		Long:    "Create a SQL based visualization",
		Example: "  growthbook analytics-explorations post-sql-exploration --datasource <value> --dimensions '[]' --chart-type bar --date-range '{\"predefined\":\"last12Months\"}' --dataset '{\"type\":\"sql\",\"sql\":\"<value>\",\"timestampColumn\":null,\"columnTypes\":{\"key\":\"other\"},\"values\":[{\"name\":\"<value>\",\"rowFilters\":[{\"operator\":\"contains\"}],\"type\":\"sql\",\"valueType\":\"sum\",\"valueColumn\":\"<value>\",\"unit\":\"hertz\"}]}'",
		RunE:    runPostSqlExplorationCmd,
		Aliases: []string{"pse"},
	}
	flagutil.RegisterFlags(cmd, postSQLExplorationCmdMeta)
	if err := flagutil.ValidateMeta[operations.PostSQLExplorationRequest](postSQLExplorationCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for post-sql-exploration: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runPostSqlExplorationCmd executes the post-sql-exploration command.
func runPostSqlExplorationCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, postSQLExplorationCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, postSQLExplorationCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PostSQLExplorationRequest](cmd, postSQLExplorationCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.AnalyticsExplorations.PostSQLExploration(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
