// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package featurerevisionsv1

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var getFeatureRevisionMergeStatusCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "version-param", Shorthand: "v", FieldPath: "Version", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initGetFeatureRevisionMergeStatusCmd initializes the get-feature-revision-merge-status command.
func initGetFeatureRevisionMergeStatusCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-feature-revision-merge-status",
		Short:   "Get merge status for a draft revision",
		Long:    "DEPRECATED: This will be removed in a future release, please migrate away from it as soon as possible\n\n**Deprecated.** Use [GET /v2/features/:id/revisions/:version/merge-status](#operation/getFeatureRevisionMergeStatusV2) instead.\n\nRuns a dry-run merge of the draft against the current live revision and returns any conflicts. Use this before publishing to preview changes and detect conflicting edits.",
		Example: "  growthbook feature-revisions-v1 get-feature-revision-merge-status --id <id> --version-param 48151",
		RunE:    runGetFeatureRevisionMergeStatusCmd,
		Aliases: []string{"gfrms"},
	}
	flagutil.RegisterFlags(cmd, getFeatureRevisionMergeStatusCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetFeatureRevisionMergeStatusRequest](getFeatureRevisionMergeStatusCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-feature-revision-merge-status: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetFeatureRevisionMergeStatusCmd executes the get-feature-revision-merge-status command.
func runGetFeatureRevisionMergeStatusCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getFeatureRevisionMergeStatusCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getFeatureRevisionMergeStatusCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetFeatureRevisionMergeStatusRequest](cmd, getFeatureRevisionMergeStatusCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.FeatureRevisionsV1.GetFeatureRevisionMergeStatus(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
