// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package featurerevisionsv1

import (
	"fmt"
	"github.com/growthbook/cli/v2/internal/client"
	"github.com/growthbook/cli/v2/internal/flagutil"
	"github.com/growthbook/cli/v2/internal/interactive"
	"github.com/growthbook/cli/v2/internal/output"
	"github.com/growthbook/cli/v2/internal/sdk"
	"github.com/growthbook/cli/v2/internal/sdk/models/operations"
	"github.com/growthbook/cli/v2/internal/usage"
	"github.com/spf13/cobra"
)

var postFeatureRevisionToggleCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "version-param", Shorthand: "v", FieldPath: "Version", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "environment", FieldPath: "Body.Environment", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "enabled", FieldPath: "Body.Enabled", Kind: flagutil.FlagKindBool, Required: true, Description: "[required]"},
	{FlagName: "revision-title", FieldPath: "Body.RevisionTitle", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "revision-comment", FieldPath: "Body.RevisionComment", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "ignore-warnings", FieldPath: "Body.IgnoreWarnings", Kind: flagutil.FlagKindBool, Optional: true, Description: "Set to true to acknowledge the warnings listed in a blocked response and continue. This covers experiment guards, locked dependents, and references affected by an archive. When the organization treats schema failures as warnings, it also covers schema and invariant warnings. It never bypasses a rejected Custom Hook. On revision publish endpoints, it can also force-publish an out-of-date draft when the caller has Bypass draft approvals access."},
}

// initPostFeatureRevisionToggleCmd initializes the post-feature-revision-toggle command.
func initPostFeatureRevisionToggleCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "post-feature-revision-toggle",
		Short:   "Toggle an environment on/off in a draft revision",
		Long:    "DEPRECATED: This will be removed in a future release, please migrate away from it as soon as possible\n\n**Deprecated.** Use [POST /v2/features/:id/revisions/:version/toggle](#operation/postFeatureRevisionToggleV2) instead.\n\nSets whether the feature is enabled in the given environment as part of the draft. Takes effect on publish.",
		Example: "  growthbook feature-revisions-v1 post-feature-revision-toggle --id <id> --version-param <value> --environment <value> --enabled true",
		RunE:    runPostFeatureRevisionToggleCmd,
		Aliases: []string{"pfrt"},
	}
	flagutil.RegisterFlags(cmd, postFeatureRevisionToggleCmdMeta)
	if err := flagutil.ValidateMeta[operations.PostFeatureRevisionToggleRequest](postFeatureRevisionToggleCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for post-feature-revision-toggle: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runPostFeatureRevisionToggleCmd executes the post-feature-revision-toggle command.
func runPostFeatureRevisionToggleCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, postFeatureRevisionToggleCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, postFeatureRevisionToggleCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PostFeatureRevisionToggleRequest](cmd, postFeatureRevisionToggleCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.FeatureRevisionsV1.PostFeatureRevisionToggle(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
