// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package metrics

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var createCmdMeta = []flagutil.FlagMeta{
	{FlagName: "datasource-id", FieldPath: "DatasourceID", Kind: flagutil.FlagKindString, Required: true, Description: "ID for the [DataSource](#tag/DataSource_model) [required]"},
	{FlagName: "managed-by", FieldPath: "ManagedBy", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"", "api"}, Description: "Where this metric must be managed from. If not set (empty string), it can be managed from anywhere. If set to \"api\", it can be managed via the API only. (options: , api)"},
	{FlagName: "owner", FieldPath: "Owner", Kind: flagutil.FlagKindString, Optional: true, Description: "The userId or email address of the owner. If an email address is provided, it will be used to look up the userId of the matching organization member. If an ID is provided, it will be validated as existing in the organization."},
	{FlagName: "name", Shorthand: "n", FieldPath: "Name", Kind: flagutil.FlagKindString, Required: true, Description: "Name of the metric [required]"},
	{FlagName: "description", FieldPath: "Description", Kind: flagutil.FlagKindString, Optional: true, Description: "Description of the metric"},
	{FlagName: "type", FieldPath: "Type", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"binomial", "count", "duration", "revenue"}, Description: "Type of metric. See [Metrics documentation](/app/metrics/legacy) (options: binomial, count, duration, revenue) [required]"},
	{FlagName: "tags", FieldPath: "Tags", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "List of tags"},
	{FlagName: "projects", Shorthand: "p", FieldPath: "Projects", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "List of project IDs for projects that can access this metric"},
	{FlagName: "archived", Shorthand: "a", FieldPath: "Archived", Kind: flagutil.FlagKindBool, Optional: true, Description: "boolean flag"},
	{FlagName: "behavior", Shorthand: "b", FieldPath: "Behavior", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"behavior,omitempty"`, Description: "JSON object"},
	{FlagName: "sql", FieldPath: "SQL", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"sql,omitempty"`, Description: "Preferred way to define SQL. Only one of `sql`, `sqlBuilder` or `mixpanel` allowed, and at least one must be specified."},
	{FlagName: "sql-builder", FieldPath: "SQLBuilder", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"sqlBuilder,omitempty"`, Description: "An alternative way to specify a SQL metric, rather than a full query. Using `sql` is preferred to `sqlBuilder`. Only one of `sql`, `sqlBuilder` or `mixpanel` allowed, and at least one must be specified."},
	{FlagName: "mixpanel", FieldPath: "Mixpanel", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"mixpanel,omitempty"`, Description: "Only use for MixPanel (non-SQL) Data Sources. Only one of `sql`, `sqlBuilder` or `mixpanel` allowed, and at least one must be specified."},
}

// initCreateCmd initializes the create command.
func initCreateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create",
		Short:   "Create a single metric",
		Long:    "Create a single metric",
		Example: "  growthbook metrics create --datasource-id <id> --name <value> --type count",
		RunE:    runCreateCmd,
	}
	flagutil.RegisterFlags(cmd, createCmdMeta)
	if err := flagutil.ValidateMeta[operations.PostMetricRequest](createCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCreateCmd executes the create command.
func runCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, createCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, createCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[operations.PostMetricRequest](cmd, createCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Metrics.Create(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
