workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    GrowthBook REST API:
        inputs:
            - location: ../growthbook/packages/back-end/generated/spec.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/growthbook/growthbook/growth-book-rest-api
targets:
    growthbook:
        target: cli
        source: GrowthBook REST API
