// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package featurerevisionsv2

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var getFeatureRevisionsV2CmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "The id of the requested resource [required]"},
	{FlagName: "limit", Shorthand: "l", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 10, Description: "The number of items to return"},
	{FlagName: "offset", FieldPath: "Offset", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, Description: "How many items to skip (use in conjunction with limit for pagination)"},
	{FlagName: "skip-pagination", FieldPath: "SkipPagination", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=skipPagination"`, Description: "If true, return all matching items and ignore limit/offset.\nSelf-hosted only. Has no effect unless API_ALLOW_SKIP_PAGINATION is set to true or 1."},
	{FlagName: "status", FieldPath: "Status", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, Optional: true, TypeDescription: "JSON value (one of: string | array of string)"}},
	{FlagName: "author", FieldPath: "Author", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "mine", Shorthand: "m", FieldPath: "Mine", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=form,explode=true,name=mine"`, Description: "If true, return only revisions authored by or contributed to by the calling user. Requires a user-scoped API key. Mutually exclusive with `author`."},
}

// initGetFeatureRevisionsV2Cmd initializes the get-feature-revisions-v2 command.
func initGetFeatureRevisionsV2Cmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get",
		Short:   "List revisions for a feature",
		Long:    "Returns a paginated list of revisions for this feature, sorted newest-first. Revision `rules` is a flat array with per-rule scope.",
		Example: "  growthbook feature-revisions-v2 get --id <id>",
		RunE:    runGetFeatureRevisionsV2Cmd,
	}
	flagutil.RegisterFlags(cmd, getFeatureRevisionsV2CmdMeta)
	if err := flagutil.ValidateMeta[operations.GetFeatureRevisionsV2Request](getFeatureRevisionsV2CmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-feature-revisions-v2: %w", err)
	}
	cmd.Flags().BoolP("all", "a", false, "Automatically paginate and fetch all results (streams NDJSON for JSON output)")
	cmd.Flags().Int("max-pages", 0, "Maximum number of pages to fetch when using --all (0 = no limit)")
	parent.AddCommand(cmd)
	return nil
}

// runGetFeatureRevisionsV2Cmd executes the get-feature-revisions-v2 command.
func runGetFeatureRevisionsV2Cmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getFeatureRevisionsV2CmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getFeatureRevisionsV2CmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetFeatureRevisionsV2Request](cmd, getFeatureRevisionsV2CmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if allPages, _ := flagutil.GetBoolFlag(cmd, "all"); allPages && !client.IsDryRun(cmd) {
		maxPages, _ := flagutil.GetIntFlag(cmd, "max-pages")
		res, err := s.FeatureRevisionsV2.GetFeatureRevisionsV2(cmd.Context(), *req, sdkOpts...)
		if err != nil {
			return output.Error(cmd, err)
		}
		return output.PaginatedResult(cmd, res, "Object", "Revisions", maxPages)
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.FeatureRevisionsV2.GetFeatureRevisionsV2(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	if output.HasMorePages(res) {
		fmt.Fprintln(cmd.ErrOrStderr(), "Hint: more pages available. Use --all to fetch all results, or use --offset/--limit for manual pagination.")
	}
	return nil
}
