// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package featurerevisionsv2

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var putFeatureRevisionLogCommentV2CmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "version-param", Shorthand: "v", FieldPath: "Version", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "log-id", Shorthand: "l", FieldPath: "LogID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "comment", Shorthand: "c", FieldPath: "Body.Comment", Kind: flagutil.FlagKindString, Required: true, Description: "New comment text. Replaces existing comment text. [required]"},
}

// initPutFeatureRevisionLogCommentV2Cmd initializes the put-feature-revision-log-comment-v2 command.
func initPutFeatureRevisionLogCommentV2Cmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "put-feature-revision-log-comment-v2",
		Short:   "Edit the comment text of an owned log entry",
		Long:    "Author of a `Comment`, `Approved`, or `Requested Changes` log entry can rewrite its comment text. The entry's action and other audit-trail metadata remain immutable; this only mutates `value.comment`. Other audit events (e.g. `Review Requested`, system events) are not editable.",
		Example: "  growthbook feature-revisions-v2 put-feature-revision-log-comment-v2 --id <id> --version-param <value> --log-id <id> --comment The Football Is Good For Training And Recreational Purposes",
		RunE:    runPutFeatureRevisionLogCommentV2Cmd,
		Aliases: []string{"pfrlcv"},
	}
	flagutil.RegisterFlags(cmd, putFeatureRevisionLogCommentV2CmdMeta)
	if err := flagutil.ValidateMeta[operations.PutFeatureRevisionLogCommentV2Request](putFeatureRevisionLogCommentV2CmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for put-feature-revision-log-comment-v2: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runPutFeatureRevisionLogCommentV2Cmd executes the put-feature-revision-log-comment-v2 command.
func runPutFeatureRevisionLogCommentV2Cmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, putFeatureRevisionLogCommentV2CmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, putFeatureRevisionLogCommentV2CmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PutFeatureRevisionLogCommentV2Request](cmd, putFeatureRevisionLogCommentV2CmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.FeatureRevisionsV2.PutFeatureRevisionLogCommentV2(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
