// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/growthbook/cli/v2/internal/sdk/sdkinternal/utils"
)

type APIErrorDimensionAlreadyUpToDateDetails struct {
	OverallResultsAsOf string `json:"overallResultsAsOf"`
}

func (a APIErrorDimensionAlreadyUpToDateDetails) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIErrorDimensionAlreadyUpToDateDetails) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIErrorDimensionAlreadyUpToDateDetails) GetOverallResultsAsOf() string {
	if a == nil {
		return ""
	}
	return a.OverallResultsAsOf
}
