// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: de37c6aaec66

package components

import (
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

type APIErrorInvalidStatusDetails struct {
	CurrentStatus    string   `json:"currentStatus"`
	ExpectedStatuses []string `json:"expectedStatuses"`
}

func (a APIErrorInvalidStatusDetails) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIErrorInvalidStatusDetails) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIErrorInvalidStatusDetails) GetCurrentStatus() string {
	if a == nil {
		return ""
	}
	return a.CurrentStatus
}

func (a *APIErrorInvalidStatusDetails) GetExpectedStatuses() []string {
	if a == nil {
		return []string{}
	}
	return a.ExpectedStatuses
}
