// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// Bandits - When true, return only multi-armed bandits; when false, exclude them
type Bandits string

const (
	BanditsTrue  Bandits = "true"
	BanditsFalse Bandits = "false"
)

func (e Bandits) ToPointer() *Bandits {
	return &e
}
func (e *Bandits) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "true":
		fallthrough
	case "false":
		*e = Bandits(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Bandits: %v", v)
	}
}
