// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/growthbook/cli/v2/internal/sdk/sdkinternal/utils"
)

type ConfigRevisionRef struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	entityType string `const:"config" json:"entityType"`
	// Config key.
	Key string `json:"key"`
	// Revision version to publish.
	Version int64 `json:"version"`
}

func (c ConfigRevisionRef) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConfigRevisionRef) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConfigRevisionRef) GetEntityType() string {
	return "config"
}

func (c *ConfigRevisionRef) GetKey() string {
	if c == nil {
		return ""
	}
	return c.Key
}

func (c *ConfigRevisionRef) GetVersion() int64 {
	if c == nil {
		return 0
	}
	return c.Version
}
