// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/growthbook/cli/internal/sdk/optionalnullable"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
	"time"
)

type ConfigRevisionActivityLogEntryAction string

const (
	ConfigRevisionActivityLogEntryActionCreated                  ConfigRevisionActivityLogEntryAction = "created"
	ConfigRevisionActivityLogEntryActionUpdated                  ConfigRevisionActivityLogEntryAction = "updated"
	ConfigRevisionActivityLogEntryActionReviewed                 ConfigRevisionActivityLogEntryAction = "reviewed"
	ConfigRevisionActivityLogEntryActionApproved                 ConfigRevisionActivityLogEntryAction = "approved"
	ConfigRevisionActivityLogEntryActionRequestedChanges         ConfigRevisionActivityLogEntryAction = "requested-changes"
	ConfigRevisionActivityLogEntryActionCommented                ConfigRevisionActivityLogEntryAction = "commented"
	ConfigRevisionActivityLogEntryActionReviewRequested          ConfigRevisionActivityLogEntryAction = "review-requested"
	ConfigRevisionActivityLogEntryActionReviewRetracted          ConfigRevisionActivityLogEntryAction = "review-retracted"
	ConfigRevisionActivityLogEntryActionMerged                   ConfigRevisionActivityLogEntryAction = "merged"
	ConfigRevisionActivityLogEntryActionDiscarded                ConfigRevisionActivityLogEntryAction = "discarded"
	ConfigRevisionActivityLogEntryActionReopened                 ConfigRevisionActivityLogEntryAction = "reopened"
	ConfigRevisionActivityLogEntryActionScheduledPublish         ConfigRevisionActivityLogEntryAction = "scheduled-publish"
	ConfigRevisionActivityLogEntryActionScheduledPublishUpdated  ConfigRevisionActivityLogEntryAction = "scheduled-publish-updated"
	ConfigRevisionActivityLogEntryActionScheduledPublishCanceled ConfigRevisionActivityLogEntryAction = "scheduled-publish-canceled"
)

func (e ConfigRevisionActivityLogEntryAction) ToPointer() *ConfigRevisionActivityLogEntryAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ConfigRevisionActivityLogEntryAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "created", "updated", "reviewed", "approved", "requested-changes", "commented", "review-requested", "review-retracted", "merged", "discarded", "reopened", "scheduled-publish", "scheduled-publish-updated", "scheduled-publish-canceled":
			return true
		}
	}
	return false
}

type ConfigRevisionActivityLogEntryProposedChangesSnapshotTest struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	op    string `const:"test" json:"op"`
	Path  string `json:"path"`
	Value any    `json:"value"`
}

func (c ConfigRevisionActivityLogEntryProposedChangesSnapshotTest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConfigRevisionActivityLogEntryProposedChangesSnapshotTest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConfigRevisionActivityLogEntryProposedChangesSnapshotTest) GetOp() string {
	return "test"
}

func (c *ConfigRevisionActivityLogEntryProposedChangesSnapshotTest) GetPath() string {
	if c == nil {
		return ""
	}
	return c.Path
}

func (c *ConfigRevisionActivityLogEntryProposedChangesSnapshotTest) GetValue() any {
	if c == nil {
		return nil
	}
	return c.Value
}

type ConfigRevisionActivityLogEntryProposedChangesSnapshotCopy struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	op   string `const:"copy" json:"op"`
	From string `json:"from"`
	Path string `json:"path"`
}

func (c ConfigRevisionActivityLogEntryProposedChangesSnapshotCopy) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConfigRevisionActivityLogEntryProposedChangesSnapshotCopy) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConfigRevisionActivityLogEntryProposedChangesSnapshotCopy) GetOp() string {
	return "copy"
}

func (c *ConfigRevisionActivityLogEntryProposedChangesSnapshotCopy) GetFrom() string {
	if c == nil {
		return ""
	}
	return c.From
}

func (c *ConfigRevisionActivityLogEntryProposedChangesSnapshotCopy) GetPath() string {
	if c == nil {
		return ""
	}
	return c.Path
}

type ConfigRevisionActivityLogEntryProposedChangesSnapshotMove struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	op   string `const:"move" json:"op"`
	From string `json:"from"`
	Path string `json:"path"`
}

func (c ConfigRevisionActivityLogEntryProposedChangesSnapshotMove) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConfigRevisionActivityLogEntryProposedChangesSnapshotMove) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConfigRevisionActivityLogEntryProposedChangesSnapshotMove) GetOp() string {
	return "move"
}

func (c *ConfigRevisionActivityLogEntryProposedChangesSnapshotMove) GetFrom() string {
	if c == nil {
		return ""
	}
	return c.From
}

func (c *ConfigRevisionActivityLogEntryProposedChangesSnapshotMove) GetPath() string {
	if c == nil {
		return ""
	}
	return c.Path
}

type ConfigRevisionActivityLogEntryProposedChangesSnapshotReplace struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	op    string `const:"replace" json:"op"`
	Path  string `json:"path"`
	Value any    `json:"value"`
}

func (c ConfigRevisionActivityLogEntryProposedChangesSnapshotReplace) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConfigRevisionActivityLogEntryProposedChangesSnapshotReplace) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConfigRevisionActivityLogEntryProposedChangesSnapshotReplace) GetOp() string {
	return "replace"
}

func (c *ConfigRevisionActivityLogEntryProposedChangesSnapshotReplace) GetPath() string {
	if c == nil {
		return ""
	}
	return c.Path
}

func (c *ConfigRevisionActivityLogEntryProposedChangesSnapshotReplace) GetValue() any {
	if c == nil {
		return nil
	}
	return c.Value
}

type ConfigRevisionActivityLogEntryProposedChangesSnapshotRemove struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	op   string `const:"remove" json:"op"`
	Path string `json:"path"`
}

func (c ConfigRevisionActivityLogEntryProposedChangesSnapshotRemove) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConfigRevisionActivityLogEntryProposedChangesSnapshotRemove) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConfigRevisionActivityLogEntryProposedChangesSnapshotRemove) GetOp() string {
	return "remove"
}

func (c *ConfigRevisionActivityLogEntryProposedChangesSnapshotRemove) GetPath() string {
	if c == nil {
		return ""
	}
	return c.Path
}

type ConfigRevisionActivityLogEntryProposedChangesSnapshotAdd struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	op    string `const:"add" json:"op"`
	Path  string `json:"path"`
	Value any    `json:"value"`
}

func (c ConfigRevisionActivityLogEntryProposedChangesSnapshotAdd) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConfigRevisionActivityLogEntryProposedChangesSnapshotAdd) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConfigRevisionActivityLogEntryProposedChangesSnapshotAdd) GetOp() string {
	return "add"
}

func (c *ConfigRevisionActivityLogEntryProposedChangesSnapshotAdd) GetPath() string {
	if c == nil {
		return ""
	}
	return c.Path
}

func (c *ConfigRevisionActivityLogEntryProposedChangesSnapshotAdd) GetValue() any {
	if c == nil {
		return nil
	}
	return c.Value
}

type ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionType string

const (
	ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionTypeAdd     ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionType = "add"
	ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionTypeRemove  ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionType = "remove"
	ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionTypeReplace ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionType = "replace"
	ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionTypeMove    ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionType = "move"
	ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionTypeCopy    ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionType = "copy"
	ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionTypeTest    ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionType = "test"
	ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionTypeUnknown ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionType = "UNKNOWN"
)

type ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion struct {
	ConfigRevisionActivityLogEntryProposedChangesSnapshotAdd     *ConfigRevisionActivityLogEntryProposedChangesSnapshotAdd     `queryParam:"inline" union:"member"`
	ConfigRevisionActivityLogEntryProposedChangesSnapshotRemove  *ConfigRevisionActivityLogEntryProposedChangesSnapshotRemove  `queryParam:"inline" union:"member"`
	ConfigRevisionActivityLogEntryProposedChangesSnapshotReplace *ConfigRevisionActivityLogEntryProposedChangesSnapshotReplace `queryParam:"inline" union:"member"`
	ConfigRevisionActivityLogEntryProposedChangesSnapshotMove    *ConfigRevisionActivityLogEntryProposedChangesSnapshotMove    `queryParam:"inline" union:"member"`
	ConfigRevisionActivityLogEntryProposedChangesSnapshotCopy    *ConfigRevisionActivityLogEntryProposedChangesSnapshotCopy    `queryParam:"inline" union:"member"`
	ConfigRevisionActivityLogEntryProposedChangesSnapshotTest    *ConfigRevisionActivityLogEntryProposedChangesSnapshotTest    `queryParam:"inline" union:"member"`
	UnknownRaw                                                   json.RawMessage                                               `json:"-" union:"unknown"`

	Type ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionType
}

func CreateConfigRevisionActivityLogEntryProposedChangesSnapshotUnionAdd(add ConfigRevisionActivityLogEntryProposedChangesSnapshotAdd) ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion {
	typ := ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionTypeAdd

	return ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion{
		ConfigRevisionActivityLogEntryProposedChangesSnapshotAdd: &add,
		Type: typ,
	}
}

func CreateConfigRevisionActivityLogEntryProposedChangesSnapshotUnionRemove(remove ConfigRevisionActivityLogEntryProposedChangesSnapshotRemove) ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion {
	typ := ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionTypeRemove

	return ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion{
		ConfigRevisionActivityLogEntryProposedChangesSnapshotRemove: &remove,
		Type: typ,
	}
}

func CreateConfigRevisionActivityLogEntryProposedChangesSnapshotUnionReplace(replace ConfigRevisionActivityLogEntryProposedChangesSnapshotReplace) ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion {
	typ := ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionTypeReplace

	return ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion{
		ConfigRevisionActivityLogEntryProposedChangesSnapshotReplace: &replace,
		Type: typ,
	}
}

func CreateConfigRevisionActivityLogEntryProposedChangesSnapshotUnionMove(move ConfigRevisionActivityLogEntryProposedChangesSnapshotMove) ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion {
	typ := ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionTypeMove

	return ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion{
		ConfigRevisionActivityLogEntryProposedChangesSnapshotMove: &move,
		Type: typ,
	}
}

func CreateConfigRevisionActivityLogEntryProposedChangesSnapshotUnionCopy(copy ConfigRevisionActivityLogEntryProposedChangesSnapshotCopy) ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion {
	typ := ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionTypeCopy

	return ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion{
		ConfigRevisionActivityLogEntryProposedChangesSnapshotCopy: &copy,
		Type: typ,
	}
}

func CreateConfigRevisionActivityLogEntryProposedChangesSnapshotUnionTest(test ConfigRevisionActivityLogEntryProposedChangesSnapshotTest) ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion {
	typ := ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionTypeTest

	return ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion{
		ConfigRevisionActivityLogEntryProposedChangesSnapshotTest: &test,
		Type: typ,
	}
}

func CreateConfigRevisionActivityLogEntryProposedChangesSnapshotUnionUnknown(raw json.RawMessage) ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion {
	return ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion{
		UnknownRaw: raw,
		Type:       ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionTypeUnknown,
	}
}

func (u ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion) IsUnknown() bool {
	return u.Type == ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionTypeUnknown
}

func (u *ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Op string `json:"op"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionTypeUnknown
		return nil
	}

	switch dis.Op {
	case "add":
		configRevisionActivityLogEntryProposedChangesSnapshotAdd := new(ConfigRevisionActivityLogEntryProposedChangesSnapshotAdd)
		if err := utils.UnmarshalJSON(data, &configRevisionActivityLogEntryProposedChangesSnapshotAdd, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Op == add) type ConfigRevisionActivityLogEntryProposedChangesSnapshotAdd within ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion: %w", string(data), err)
		}

		u.ConfigRevisionActivityLogEntryProposedChangesSnapshotAdd = configRevisionActivityLogEntryProposedChangesSnapshotAdd
		u.Type = ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionTypeAdd
		return nil
	case "remove":
		configRevisionActivityLogEntryProposedChangesSnapshotRemove := new(ConfigRevisionActivityLogEntryProposedChangesSnapshotRemove)
		if err := utils.UnmarshalJSON(data, &configRevisionActivityLogEntryProposedChangesSnapshotRemove, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Op == remove) type ConfigRevisionActivityLogEntryProposedChangesSnapshotRemove within ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion: %w", string(data), err)
		}

		u.ConfigRevisionActivityLogEntryProposedChangesSnapshotRemove = configRevisionActivityLogEntryProposedChangesSnapshotRemove
		u.Type = ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionTypeRemove
		return nil
	case "replace":
		configRevisionActivityLogEntryProposedChangesSnapshotReplace := new(ConfigRevisionActivityLogEntryProposedChangesSnapshotReplace)
		if err := utils.UnmarshalJSON(data, &configRevisionActivityLogEntryProposedChangesSnapshotReplace, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Op == replace) type ConfigRevisionActivityLogEntryProposedChangesSnapshotReplace within ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion: %w", string(data), err)
		}

		u.ConfigRevisionActivityLogEntryProposedChangesSnapshotReplace = configRevisionActivityLogEntryProposedChangesSnapshotReplace
		u.Type = ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionTypeReplace
		return nil
	case "move":
		configRevisionActivityLogEntryProposedChangesSnapshotMove := new(ConfigRevisionActivityLogEntryProposedChangesSnapshotMove)
		if err := utils.UnmarshalJSON(data, &configRevisionActivityLogEntryProposedChangesSnapshotMove, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Op == move) type ConfigRevisionActivityLogEntryProposedChangesSnapshotMove within ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion: %w", string(data), err)
		}

		u.ConfigRevisionActivityLogEntryProposedChangesSnapshotMove = configRevisionActivityLogEntryProposedChangesSnapshotMove
		u.Type = ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionTypeMove
		return nil
	case "copy":
		configRevisionActivityLogEntryProposedChangesSnapshotCopy := new(ConfigRevisionActivityLogEntryProposedChangesSnapshotCopy)
		if err := utils.UnmarshalJSON(data, &configRevisionActivityLogEntryProposedChangesSnapshotCopy, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Op == copy) type ConfigRevisionActivityLogEntryProposedChangesSnapshotCopy within ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion: %w", string(data), err)
		}

		u.ConfigRevisionActivityLogEntryProposedChangesSnapshotCopy = configRevisionActivityLogEntryProposedChangesSnapshotCopy
		u.Type = ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionTypeCopy
		return nil
	case "test":
		configRevisionActivityLogEntryProposedChangesSnapshotTest := new(ConfigRevisionActivityLogEntryProposedChangesSnapshotTest)
		if err := utils.UnmarshalJSON(data, &configRevisionActivityLogEntryProposedChangesSnapshotTest, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Op == test) type ConfigRevisionActivityLogEntryProposedChangesSnapshotTest within ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion: %w", string(data), err)
		}

		u.ConfigRevisionActivityLogEntryProposedChangesSnapshotTest = configRevisionActivityLogEntryProposedChangesSnapshotTest
		u.Type = ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionTypeTest
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ConfigRevisionActivityLogEntryProposedChangesSnapshotUnionTypeUnknown
		return nil
	}

}

func (u ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion) MarshalJSON() ([]byte, error) {
	if u.ConfigRevisionActivityLogEntryProposedChangesSnapshotAdd != nil {
		return utils.MarshalJSON(u.ConfigRevisionActivityLogEntryProposedChangesSnapshotAdd, "", true)
	}

	if u.ConfigRevisionActivityLogEntryProposedChangesSnapshotRemove != nil {
		return utils.MarshalJSON(u.ConfigRevisionActivityLogEntryProposedChangesSnapshotRemove, "", true)
	}

	if u.ConfigRevisionActivityLogEntryProposedChangesSnapshotReplace != nil {
		return utils.MarshalJSON(u.ConfigRevisionActivityLogEntryProposedChangesSnapshotReplace, "", true)
	}

	if u.ConfigRevisionActivityLogEntryProposedChangesSnapshotMove != nil {
		return utils.MarshalJSON(u.ConfigRevisionActivityLogEntryProposedChangesSnapshotMove, "", true)
	}

	if u.ConfigRevisionActivityLogEntryProposedChangesSnapshotCopy != nil {
		return utils.MarshalJSON(u.ConfigRevisionActivityLogEntryProposedChangesSnapshotCopy, "", true)
	}

	if u.ConfigRevisionActivityLogEntryProposedChangesSnapshotTest != nil {
		return utils.MarshalJSON(u.ConfigRevisionActivityLogEntryProposedChangesSnapshotTest, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion: all fields are null")
}

type ConfigRevisionActivityLogEntry struct {
	ID                      string                                                       `json:"id"`
	UserID                  string                                                       `json:"userId"`
	Action                  ConfigRevisionActivityLogEntryAction                         `json:"action"`
	Description             optionalnullable.OptionalNullable[string]                    `json:"description,omitzero"`
	ProposedChangesSnapshot []ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion `json:"proposedChangesSnapshot,omitzero"`
	TargetSnapshot          any                                                          `json:"targetSnapshot,omitzero"`
	DateCreated             time.Time                                                    `json:"dateCreated"`
}

func (c ConfigRevisionActivityLogEntry) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConfigRevisionActivityLogEntry) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConfigRevisionActivityLogEntry) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *ConfigRevisionActivityLogEntry) GetUserID() string {
	if c == nil {
		return ""
	}
	return c.UserID
}

func (c *ConfigRevisionActivityLogEntry) GetAction() ConfigRevisionActivityLogEntryAction {
	if c == nil {
		return ConfigRevisionActivityLogEntryAction("")
	}
	return c.Action
}

func (c *ConfigRevisionActivityLogEntry) GetDescription() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *ConfigRevisionActivityLogEntry) GetProposedChangesSnapshot() []ConfigRevisionActivityLogEntryProposedChangesSnapshotUnion {
	if c == nil {
		return nil
	}
	return c.ProposedChangesSnapshot
}

func (c *ConfigRevisionActivityLogEntry) GetTargetSnapshot() any {
	if c == nil {
		return nil
	}
	return c.TargetSnapshot
}

func (c *ConfigRevisionActivityLogEntry) GetDateCreated() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.DateCreated
}
