// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
	"time"
)

type ConstantRevisionStatus string

const (
	ConstantRevisionStatusDraft            ConstantRevisionStatus = "draft"
	ConstantRevisionStatusPendingReview    ConstantRevisionStatus = "pending-review"
	ConstantRevisionStatusApproved         ConstantRevisionStatus = "approved"
	ConstantRevisionStatusChangesRequested ConstantRevisionStatus = "changes-requested"
	ConstantRevisionStatusMerged           ConstantRevisionStatus = "merged"
	ConstantRevisionStatusDiscarded        ConstantRevisionStatus = "discarded"
)

func (e ConstantRevisionStatus) ToPointer() *ConstantRevisionStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ConstantRevisionStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "draft", "pending-review", "approved", "changes-requested", "merged", "discarded":
			return true
		}
	}
	return false
}

type ConstantRevisionAction string

const (
	ConstantRevisionActionMerged    ConstantRevisionAction = "merged"
	ConstantRevisionActionDiscarded ConstantRevisionAction = "discarded"
)

func (e ConstantRevisionAction) ToPointer() *ConstantRevisionAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ConstantRevisionAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "merged", "discarded":
			return true
		}
	}
	return false
}

type ConstantRevisionResolution struct {
	Action      ConstantRevisionAction `json:"action"`
	UserID      string                 `json:"userId"`
	DateCreated time.Time              `json:"dateCreated"`
}

func (c ConstantRevisionResolution) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConstantRevisionResolution) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConstantRevisionResolution) GetAction() ConstantRevisionAction {
	if c == nil {
		return ConstantRevisionAction("")
	}
	return c.Action
}

func (c *ConstantRevisionResolution) GetUserID() string {
	if c == nil {
		return ""
	}
	return c.UserID
}

func (c *ConstantRevisionResolution) GetDateCreated() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.DateCreated
}

type ConstantRevisionProposedChangeTest struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	op    string `const:"test" json:"op"`
	Path  string `json:"path"`
	Value any    `json:"value"`
}

func (c ConstantRevisionProposedChangeTest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConstantRevisionProposedChangeTest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConstantRevisionProposedChangeTest) GetOp() string {
	return "test"
}

func (c *ConstantRevisionProposedChangeTest) GetPath() string {
	if c == nil {
		return ""
	}
	return c.Path
}

func (c *ConstantRevisionProposedChangeTest) GetValue() any {
	if c == nil {
		return nil
	}
	return c.Value
}

type ConstantRevisionProposedChangeCopy struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	op   string `const:"copy" json:"op"`
	From string `json:"from"`
	Path string `json:"path"`
}

func (c ConstantRevisionProposedChangeCopy) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConstantRevisionProposedChangeCopy) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConstantRevisionProposedChangeCopy) GetOp() string {
	return "copy"
}

func (c *ConstantRevisionProposedChangeCopy) GetFrom() string {
	if c == nil {
		return ""
	}
	return c.From
}

func (c *ConstantRevisionProposedChangeCopy) GetPath() string {
	if c == nil {
		return ""
	}
	return c.Path
}

type ConstantRevisionProposedChangeMove struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	op   string `const:"move" json:"op"`
	From string `json:"from"`
	Path string `json:"path"`
}

func (c ConstantRevisionProposedChangeMove) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConstantRevisionProposedChangeMove) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConstantRevisionProposedChangeMove) GetOp() string {
	return "move"
}

func (c *ConstantRevisionProposedChangeMove) GetFrom() string {
	if c == nil {
		return ""
	}
	return c.From
}

func (c *ConstantRevisionProposedChangeMove) GetPath() string {
	if c == nil {
		return ""
	}
	return c.Path
}

type ConstantRevisionProposedChangeReplace struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	op    string `const:"replace" json:"op"`
	Path  string `json:"path"`
	Value any    `json:"value"`
}

func (c ConstantRevisionProposedChangeReplace) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConstantRevisionProposedChangeReplace) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConstantRevisionProposedChangeReplace) GetOp() string {
	return "replace"
}

func (c *ConstantRevisionProposedChangeReplace) GetPath() string {
	if c == nil {
		return ""
	}
	return c.Path
}

func (c *ConstantRevisionProposedChangeReplace) GetValue() any {
	if c == nil {
		return nil
	}
	return c.Value
}

type ConstantRevisionProposedChangeRemove struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	op   string `const:"remove" json:"op"`
	Path string `json:"path"`
}

func (c ConstantRevisionProposedChangeRemove) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConstantRevisionProposedChangeRemove) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConstantRevisionProposedChangeRemove) GetOp() string {
	return "remove"
}

func (c *ConstantRevisionProposedChangeRemove) GetPath() string {
	if c == nil {
		return ""
	}
	return c.Path
}

type ConstantRevisionProposedChangeAdd struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	op    string `const:"add" json:"op"`
	Path  string `json:"path"`
	Value any    `json:"value"`
}

func (c ConstantRevisionProposedChangeAdd) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConstantRevisionProposedChangeAdd) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConstantRevisionProposedChangeAdd) GetOp() string {
	return "add"
}

func (c *ConstantRevisionProposedChangeAdd) GetPath() string {
	if c == nil {
		return ""
	}
	return c.Path
}

func (c *ConstantRevisionProposedChangeAdd) GetValue() any {
	if c == nil {
		return nil
	}
	return c.Value
}

type ConstantRevisionProposedChangeUnionType string

const (
	ConstantRevisionProposedChangeUnionTypeAdd     ConstantRevisionProposedChangeUnionType = "add"
	ConstantRevisionProposedChangeUnionTypeRemove  ConstantRevisionProposedChangeUnionType = "remove"
	ConstantRevisionProposedChangeUnionTypeReplace ConstantRevisionProposedChangeUnionType = "replace"
	ConstantRevisionProposedChangeUnionTypeMove    ConstantRevisionProposedChangeUnionType = "move"
	ConstantRevisionProposedChangeUnionTypeCopy    ConstantRevisionProposedChangeUnionType = "copy"
	ConstantRevisionProposedChangeUnionTypeTest    ConstantRevisionProposedChangeUnionType = "test"
	ConstantRevisionProposedChangeUnionTypeUnknown ConstantRevisionProposedChangeUnionType = "UNKNOWN"
)

type ConstantRevisionProposedChangeUnion struct {
	ConstantRevisionProposedChangeAdd     *ConstantRevisionProposedChangeAdd     `queryParam:"inline" union:"member"`
	ConstantRevisionProposedChangeRemove  *ConstantRevisionProposedChangeRemove  `queryParam:"inline" union:"member"`
	ConstantRevisionProposedChangeReplace *ConstantRevisionProposedChangeReplace `queryParam:"inline" union:"member"`
	ConstantRevisionProposedChangeMove    *ConstantRevisionProposedChangeMove    `queryParam:"inline" union:"member"`
	ConstantRevisionProposedChangeCopy    *ConstantRevisionProposedChangeCopy    `queryParam:"inline" union:"member"`
	ConstantRevisionProposedChangeTest    *ConstantRevisionProposedChangeTest    `queryParam:"inline" union:"member"`
	UnknownRaw                            json.RawMessage                        `json:"-" union:"unknown"`

	Type ConstantRevisionProposedChangeUnionType
}

func CreateConstantRevisionProposedChangeUnionAdd(add ConstantRevisionProposedChangeAdd) ConstantRevisionProposedChangeUnion {
	typ := ConstantRevisionProposedChangeUnionTypeAdd

	return ConstantRevisionProposedChangeUnion{
		ConstantRevisionProposedChangeAdd: &add,
		Type:                              typ,
	}
}

func CreateConstantRevisionProposedChangeUnionRemove(remove ConstantRevisionProposedChangeRemove) ConstantRevisionProposedChangeUnion {
	typ := ConstantRevisionProposedChangeUnionTypeRemove

	return ConstantRevisionProposedChangeUnion{
		ConstantRevisionProposedChangeRemove: &remove,
		Type:                                 typ,
	}
}

func CreateConstantRevisionProposedChangeUnionReplace(replace ConstantRevisionProposedChangeReplace) ConstantRevisionProposedChangeUnion {
	typ := ConstantRevisionProposedChangeUnionTypeReplace

	return ConstantRevisionProposedChangeUnion{
		ConstantRevisionProposedChangeReplace: &replace,
		Type:                                  typ,
	}
}

func CreateConstantRevisionProposedChangeUnionMove(move ConstantRevisionProposedChangeMove) ConstantRevisionProposedChangeUnion {
	typ := ConstantRevisionProposedChangeUnionTypeMove

	return ConstantRevisionProposedChangeUnion{
		ConstantRevisionProposedChangeMove: &move,
		Type:                               typ,
	}
}

func CreateConstantRevisionProposedChangeUnionCopy(copy ConstantRevisionProposedChangeCopy) ConstantRevisionProposedChangeUnion {
	typ := ConstantRevisionProposedChangeUnionTypeCopy

	return ConstantRevisionProposedChangeUnion{
		ConstantRevisionProposedChangeCopy: &copy,
		Type:                               typ,
	}
}

func CreateConstantRevisionProposedChangeUnionTest(test ConstantRevisionProposedChangeTest) ConstantRevisionProposedChangeUnion {
	typ := ConstantRevisionProposedChangeUnionTypeTest

	return ConstantRevisionProposedChangeUnion{
		ConstantRevisionProposedChangeTest: &test,
		Type:                               typ,
	}
}

func CreateConstantRevisionProposedChangeUnionUnknown(raw json.RawMessage) ConstantRevisionProposedChangeUnion {
	return ConstantRevisionProposedChangeUnion{
		UnknownRaw: raw,
		Type:       ConstantRevisionProposedChangeUnionTypeUnknown,
	}
}

func (u ConstantRevisionProposedChangeUnion) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u ConstantRevisionProposedChangeUnion) IsUnknown() bool {
	return u.Type == ConstantRevisionProposedChangeUnionTypeUnknown
}

func (u *ConstantRevisionProposedChangeUnion) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Op string `json:"op"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ConstantRevisionProposedChangeUnionTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ConstantRevisionProposedChangeUnionTypeUnknown
		return nil
	}

	switch dis.Op {
	case "add":
		constantRevisionProposedChangeAdd := new(ConstantRevisionProposedChangeAdd)
		if err := utils.UnmarshalJSON(data, &constantRevisionProposedChangeAdd, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Op == add) type ConstantRevisionProposedChangeAdd within ConstantRevisionProposedChangeUnion: %w", string(data), err)
		}

		u.ConstantRevisionProposedChangeAdd = constantRevisionProposedChangeAdd
		u.Type = ConstantRevisionProposedChangeUnionTypeAdd
		return nil
	case "remove":
		constantRevisionProposedChangeRemove := new(ConstantRevisionProposedChangeRemove)
		if err := utils.UnmarshalJSON(data, &constantRevisionProposedChangeRemove, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Op == remove) type ConstantRevisionProposedChangeRemove within ConstantRevisionProposedChangeUnion: %w", string(data), err)
		}

		u.ConstantRevisionProposedChangeRemove = constantRevisionProposedChangeRemove
		u.Type = ConstantRevisionProposedChangeUnionTypeRemove
		return nil
	case "replace":
		constantRevisionProposedChangeReplace := new(ConstantRevisionProposedChangeReplace)
		if err := utils.UnmarshalJSON(data, &constantRevisionProposedChangeReplace, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Op == replace) type ConstantRevisionProposedChangeReplace within ConstantRevisionProposedChangeUnion: %w", string(data), err)
		}

		u.ConstantRevisionProposedChangeReplace = constantRevisionProposedChangeReplace
		u.Type = ConstantRevisionProposedChangeUnionTypeReplace
		return nil
	case "move":
		constantRevisionProposedChangeMove := new(ConstantRevisionProposedChangeMove)
		if err := utils.UnmarshalJSON(data, &constantRevisionProposedChangeMove, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Op == move) type ConstantRevisionProposedChangeMove within ConstantRevisionProposedChangeUnion: %w", string(data), err)
		}

		u.ConstantRevisionProposedChangeMove = constantRevisionProposedChangeMove
		u.Type = ConstantRevisionProposedChangeUnionTypeMove
		return nil
	case "copy":
		constantRevisionProposedChangeCopy := new(ConstantRevisionProposedChangeCopy)
		if err := utils.UnmarshalJSON(data, &constantRevisionProposedChangeCopy, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Op == copy) type ConstantRevisionProposedChangeCopy within ConstantRevisionProposedChangeUnion: %w", string(data), err)
		}

		u.ConstantRevisionProposedChangeCopy = constantRevisionProposedChangeCopy
		u.Type = ConstantRevisionProposedChangeUnionTypeCopy
		return nil
	case "test":
		constantRevisionProposedChangeTest := new(ConstantRevisionProposedChangeTest)
		if err := utils.UnmarshalJSON(data, &constantRevisionProposedChangeTest, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Op == test) type ConstantRevisionProposedChangeTest within ConstantRevisionProposedChangeUnion: %w", string(data), err)
		}

		u.ConstantRevisionProposedChangeTest = constantRevisionProposedChangeTest
		u.Type = ConstantRevisionProposedChangeUnionTypeTest
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ConstantRevisionProposedChangeUnionTypeUnknown
		return nil
	}

}

func (u ConstantRevisionProposedChangeUnion) MarshalJSON() ([]byte, error) {
	if u.ConstantRevisionProposedChangeAdd != nil {
		return utils.MarshalJSON(u.ConstantRevisionProposedChangeAdd, "", true)
	}

	if u.ConstantRevisionProposedChangeRemove != nil {
		return utils.MarshalJSON(u.ConstantRevisionProposedChangeRemove, "", true)
	}

	if u.ConstantRevisionProposedChangeReplace != nil {
		return utils.MarshalJSON(u.ConstantRevisionProposedChangeReplace, "", true)
	}

	if u.ConstantRevisionProposedChangeMove != nil {
		return utils.MarshalJSON(u.ConstantRevisionProposedChangeMove, "", true)
	}

	if u.ConstantRevisionProposedChangeCopy != nil {
		return utils.MarshalJSON(u.ConstantRevisionProposedChangeCopy, "", true)
	}

	if u.ConstantRevisionProposedChangeTest != nil {
		return utils.MarshalJSON(u.ConstantRevisionProposedChangeTest, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type ConstantRevisionProposedChangeUnion: all fields are null")
}

type ConstantRevision struct {
	ID               string                                `json:"id"`
	Version          *int64                                `json:"version,omitzero"`
	Title            *string                               `json:"title,omitzero"`
	Status           ConstantRevisionStatus                `json:"status"`
	AuthorID         string                                `json:"authorId"`
	AuthorEmail      *string                               `json:"authorEmail,omitzero"`
	Contributors     []string                              `json:"contributors,omitzero"`
	RevertedFrom     *string                               `json:"revertedFrom,omitzero"`
	Reviews          []ConstantRevisionReview              `json:"reviews"`
	ActivityLog      []ConstantRevisionActivityLogEntry    `json:"activityLog"`
	Resolution       *ConstantRevisionResolution           `json:"resolution,omitzero"`
	DateCreated      time.Time                             `json:"dateCreated"`
	DateUpdated      time.Time                             `json:"dateUpdated"`
	BaseConstant     Constant                              `json:"baseConstant"`
	ProposedConstant Constant                              `json:"proposedConstant"`
	ProposedChanges  []ConstantRevisionProposedChangeUnion `json:"proposedChanges"`
}

func (c ConstantRevision) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConstantRevision) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConstantRevision) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *ConstantRevision) GetVersion() *int64 {
	if c == nil {
		return nil
	}
	return c.Version
}

func (c *ConstantRevision) GetTitle() *string {
	if c == nil {
		return nil
	}
	return c.Title
}

func (c *ConstantRevision) GetStatus() ConstantRevisionStatus {
	if c == nil {
		return ConstantRevisionStatus("")
	}
	return c.Status
}

func (c *ConstantRevision) GetAuthorID() string {
	if c == nil {
		return ""
	}
	return c.AuthorID
}

func (c *ConstantRevision) GetAuthorEmail() *string {
	if c == nil {
		return nil
	}
	return c.AuthorEmail
}

func (c *ConstantRevision) GetContributors() []string {
	if c == nil {
		return nil
	}
	return c.Contributors
}

func (c *ConstantRevision) GetRevertedFrom() *string {
	if c == nil {
		return nil
	}
	return c.RevertedFrom
}

func (c *ConstantRevision) GetReviews() []ConstantRevisionReview {
	if c == nil {
		return []ConstantRevisionReview{}
	}
	return c.Reviews
}

func (c *ConstantRevision) GetActivityLog() []ConstantRevisionActivityLogEntry {
	if c == nil {
		return []ConstantRevisionActivityLogEntry{}
	}
	return c.ActivityLog
}

func (c *ConstantRevision) GetResolution() *ConstantRevisionResolution {
	if c == nil {
		return nil
	}
	return c.Resolution
}

func (c *ConstantRevision) GetDateCreated() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.DateCreated
}

func (c *ConstantRevision) GetDateUpdated() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.DateUpdated
}

func (c *ConstantRevision) GetBaseConstant() Constant {
	if c == nil {
		return Constant{}
	}
	return c.BaseConstant
}

func (c *ConstantRevision) GetProposedConstant() Constant {
	if c == nil {
		return Constant{}
	}
	return c.ProposedConstant
}

func (c *ConstantRevision) GetProposedChanges() []ConstantRevisionProposedChangeUnion {
	if c == nil {
		return []ConstantRevisionProposedChangeUnion{}
	}
	return c.ProposedChanges
}
