// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ccf424ab80e2

package components

type EventUserType string

const (
	EventUserTypeDashboard EventUserType = "dashboard"
	EventUserTypeAPIKey    EventUserType = "api_key"
	EventUserTypeSystem    EventUserType = "system"
)

func (e EventUserType) ToPointer() *EventUserType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *EventUserType) IsExact() bool {
	if e != nil {
		switch *e {
		case "dashboard", "api_key", "system":
			return true
		}
	}
	return false
}

// EventUser - The user (or automated actor) responsible for an action
type EventUser struct {
	Type  EventUserType `json:"type"`
	ID    *string       `json:"id,omitzero"`
	Name  *string       `json:"name,omitzero"`
	Email *string       `json:"email,omitzero"`
}

func (e *EventUser) GetType() EventUserType {
	if e == nil {
		return EventUserType("")
	}
	return e.Type
}

func (e *EventUser) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *EventUser) GetName() *string {
	if e == nil {
		return nil
	}
	return e.Name
}

func (e *EventUser) GetEmail() *string {
	if e == nil {
		return nil
	}
	return e.Email
}
