// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
)

type FeatureRuleV1Type string

const (
	FeatureRuleV1TypeForce         FeatureRuleV1Type = "force"
	FeatureRuleV1TypeRollout       FeatureRuleV1Type = "rollout"
	FeatureRuleV1TypeExperiment    FeatureRuleV1Type = "experiment"
	FeatureRuleV1TypeExperimentRef FeatureRuleV1Type = "experiment-ref"
	FeatureRuleV1TypeSafeRollout   FeatureRuleV1Type = "safe-rollout"
	FeatureRuleV1TypeUnknown       FeatureRuleV1Type = "UNKNOWN"
)

type FeatureRuleV1 struct {
	FeatureForceRule         *FeatureForceRule         `queryParam:"inline" union:"member"`
	FeatureRolloutRule       *FeatureRolloutRule       `queryParam:"inline" union:"member"`
	FeatureExperimentRule    *FeatureExperimentRule    `queryParam:"inline" union:"member"`
	FeatureExperimentRefRule *FeatureExperimentRefRule `queryParam:"inline" union:"member"`
	FeatureSafeRolloutRule   *FeatureSafeRolloutRule   `queryParam:"inline" union:"member"`
	UnknownRaw               json.RawMessage           `json:"-" union:"unknown"`

	Type FeatureRuleV1Type
}

func CreateFeatureRuleV1Force(force FeatureForceRule) FeatureRuleV1 {
	typ := FeatureRuleV1TypeForce

	return FeatureRuleV1{
		FeatureForceRule: &force,
		Type:             typ,
	}
}

func CreateFeatureRuleV1Rollout(rollout FeatureRolloutRule) FeatureRuleV1 {
	typ := FeatureRuleV1TypeRollout

	return FeatureRuleV1{
		FeatureRolloutRule: &rollout,
		Type:               typ,
	}
}

func CreateFeatureRuleV1Experiment(experiment FeatureExperimentRule) FeatureRuleV1 {
	typ := FeatureRuleV1TypeExperiment

	return FeatureRuleV1{
		FeatureExperimentRule: &experiment,
		Type:                  typ,
	}
}

func CreateFeatureRuleV1ExperimentRef(experimentRef FeatureExperimentRefRule) FeatureRuleV1 {
	typ := FeatureRuleV1TypeExperimentRef

	return FeatureRuleV1{
		FeatureExperimentRefRule: &experimentRef,
		Type:                     typ,
	}
}

func CreateFeatureRuleV1SafeRollout(safeRollout FeatureSafeRolloutRule) FeatureRuleV1 {
	typ := FeatureRuleV1TypeSafeRollout

	return FeatureRuleV1{
		FeatureSafeRolloutRule: &safeRollout,
		Type:                   typ,
	}
}

func CreateFeatureRuleV1Unknown(raw json.RawMessage) FeatureRuleV1 {
	return FeatureRuleV1{
		UnknownRaw: raw,
		Type:       FeatureRuleV1TypeUnknown,
	}
}

func (u FeatureRuleV1) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u FeatureRuleV1) IsUnknown() bool {
	return u.Type == FeatureRuleV1TypeUnknown
}

func (u *FeatureRuleV1) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = FeatureRuleV1TypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = FeatureRuleV1TypeUnknown
		return nil
	}

	switch dis.Type {
	case "force":
		featureForceRule := new(FeatureForceRule)
		if err := utils.UnmarshalJSON(data, &featureForceRule, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == force) type FeatureForceRule within FeatureRuleV1: %w", string(data), err)
		}

		u.FeatureForceRule = featureForceRule
		u.Type = FeatureRuleV1TypeForce
		return nil
	case "rollout":
		featureRolloutRule := new(FeatureRolloutRule)
		if err := utils.UnmarshalJSON(data, &featureRolloutRule, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == rollout) type FeatureRolloutRule within FeatureRuleV1: %w", string(data), err)
		}

		u.FeatureRolloutRule = featureRolloutRule
		u.Type = FeatureRuleV1TypeRollout
		return nil
	case "experiment":
		featureExperimentRule := new(FeatureExperimentRule)
		if err := utils.UnmarshalJSON(data, &featureExperimentRule, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == experiment) type FeatureExperimentRule within FeatureRuleV1: %w", string(data), err)
		}

		u.FeatureExperimentRule = featureExperimentRule
		u.Type = FeatureRuleV1TypeExperiment
		return nil
	case "experiment-ref":
		featureExperimentRefRule := new(FeatureExperimentRefRule)
		if err := utils.UnmarshalJSON(data, &featureExperimentRefRule, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == experiment-ref) type FeatureExperimentRefRule within FeatureRuleV1: %w", string(data), err)
		}

		u.FeatureExperimentRefRule = featureExperimentRefRule
		u.Type = FeatureRuleV1TypeExperimentRef
		return nil
	case "safe-rollout":
		featureSafeRolloutRule := new(FeatureSafeRolloutRule)
		if err := utils.UnmarshalJSON(data, &featureSafeRolloutRule, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == safe-rollout) type FeatureSafeRolloutRule within FeatureRuleV1: %w", string(data), err)
		}

		u.FeatureSafeRolloutRule = featureSafeRolloutRule
		u.Type = FeatureRuleV1TypeSafeRollout
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = FeatureRuleV1TypeUnknown
		return nil
	}

}

func (u FeatureRuleV1) MarshalJSON() ([]byte, error) {
	if u.FeatureForceRule != nil {
		return utils.MarshalJSON(u.FeatureForceRule, "", true)
	}

	if u.FeatureRolloutRule != nil {
		return utils.MarshalJSON(u.FeatureRolloutRule, "", true)
	}

	if u.FeatureExperimentRule != nil {
		return utils.MarshalJSON(u.FeatureExperimentRule, "", true)
	}

	if u.FeatureExperimentRefRule != nil {
		return utils.MarshalJSON(u.FeatureExperimentRefRule, "", true)
	}

	if u.FeatureSafeRolloutRule != nil {
		return utils.MarshalJSON(u.FeatureSafeRolloutRule, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type FeatureRuleV1: all fields are null")
}
