// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/growthbook/cli/internal/sdk/optionalnullable"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
	"time"
)

type FeatureWithRevisionsV1ValueType string

const (
	FeatureWithRevisionsV1ValueTypeBoolean FeatureWithRevisionsV1ValueType = "boolean"
	FeatureWithRevisionsV1ValueTypeString  FeatureWithRevisionsV1ValueType = "string"
	FeatureWithRevisionsV1ValueTypeNumber  FeatureWithRevisionsV1ValueType = "number"
	FeatureWithRevisionsV1ValueTypeJSON    FeatureWithRevisionsV1ValueType = "json"
)

func (e FeatureWithRevisionsV1ValueType) ToPointer() *FeatureWithRevisionsV1ValueType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *FeatureWithRevisionsV1ValueType) IsExact() bool {
	if e != nil {
		switch *e {
		case "boolean", "string", "number", "json":
			return true
		}
	}
	return false
}

type FeatureWithRevisionsV1Revision struct {
	Version     int64     `json:"version"`
	Comment     string    `json:"comment"`
	Date        time.Time `json:"date"`
	CreatedBy   string    `json:"createdBy"`
	PublishedBy string    `json:"publishedBy"`
}

func (f FeatureWithRevisionsV1Revision) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FeatureWithRevisionsV1Revision) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FeatureWithRevisionsV1Revision) GetVersion() int64 {
	if f == nil {
		return 0
	}
	return f.Version
}

func (f *FeatureWithRevisionsV1Revision) GetComment() string {
	if f == nil {
		return ""
	}
	return f.Comment
}

func (f *FeatureWithRevisionsV1Revision) GetDate() time.Time {
	if f == nil {
		return time.Time{}
	}
	return f.Date
}

func (f *FeatureWithRevisionsV1Revision) GetCreatedBy() string {
	if f == nil {
		return ""
	}
	return f.CreatedBy
}

func (f *FeatureWithRevisionsV1Revision) GetPublishedBy() string {
	if f == nil {
		return ""
	}
	return f.PublishedBy
}

// #region class-body-featurewithrevisionsv1revision
// #endregion class-body-featurewithrevisionsv1revision

type FeatureWithRevisionsV1Holdout struct {
	// Holdout ID
	ID string `json:"id"`
	// The feature value assigned to users in the holdout treatment group
	Value string `json:"value"`
}

func (f *FeatureWithRevisionsV1Holdout) GetID() string {
	if f == nil {
		return ""
	}
	return f.ID
}

func (f *FeatureWithRevisionsV1Holdout) GetValue() string {
	if f == nil {
		return ""
	}
	return f.Value
}

// #region class-body-featurewithrevisionsv1holdout
// #endregion class-body-featurewithrevisionsv1holdout

type FeatureWithRevisionsV1 struct {
	ID          string    `json:"id"`
	DateCreated time.Time `json:"dateCreated"`
	DateUpdated time.Time `json:"dateUpdated"`
	Archived    bool      `json:"archived"`
	Description string    `json:"description"`
	// The userId of the owner (or raw owner name/email for legacy records)
	Owner string `json:"owner"`
	// The email address of the owner, when the owner can be resolved to a known user.
	OwnerEmail   *string                         `json:"ownerEmail,omitzero"`
	Project      string                          `json:"project"`
	ValueType    FeatureWithRevisionsV1ValueType `json:"valueType"`
	DefaultValue string                          `json:"defaultValue"`
	// Key of the config backing this flag ("Config mode"), or null. The config supplies the base JSON and schema. The internal `@config:` directive is scrubbed from values; `@const:` references are preserved. (v2 additionally exposes per-rule config fields.)
	BaseConfig optionalnullable.OptionalNullable[string] `json:"baseConfig,omitzero"`
	// Config within `baseConfig`'s family that the default value resolves to (a descendant), or null when the default uses `baseConfig` directly.
	DefaultValueConfig optionalnullable.OptionalNullable[string] `json:"defaultValueConfig,omitzero"`
	Tags               []string                                  `json:"tags"`
	Environments       map[string]FeatureEnvironmentV1           `json:"environments"`
	// Feature IDs. Each feature must evaluate to `true`
	Prerequisites []string                                                         `json:"prerequisites,omitzero"`
	Revision      FeatureWithRevisionsV1Revision                                   `json:"revision"`
	CustomFields  map[string]any                                                   `json:"customFields,omitzero"`
	Holdout       optionalnullable.OptionalNullable[FeatureWithRevisionsV1Holdout] `json:"holdout,omitzero"`
	Revisions     []FeatureRevisionV1                                              `json:"revisions,omitzero"`
}

func (f FeatureWithRevisionsV1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FeatureWithRevisionsV1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FeatureWithRevisionsV1) GetID() string {
	if f == nil {
		return ""
	}
	return f.ID
}

func (f *FeatureWithRevisionsV1) GetDateCreated() time.Time {
	if f == nil {
		return time.Time{}
	}
	return f.DateCreated
}

func (f *FeatureWithRevisionsV1) GetDateUpdated() time.Time {
	if f == nil {
		return time.Time{}
	}
	return f.DateUpdated
}

func (f *FeatureWithRevisionsV1) GetArchived() bool {
	if f == nil {
		return false
	}
	return f.Archived
}

func (f *FeatureWithRevisionsV1) GetDescription() string {
	if f == nil {
		return ""
	}
	return f.Description
}

func (f *FeatureWithRevisionsV1) GetOwner() string {
	if f == nil {
		return ""
	}
	return f.Owner
}

func (f *FeatureWithRevisionsV1) GetOwnerEmail() *string {
	if f == nil {
		return nil
	}
	return f.OwnerEmail
}

func (f *FeatureWithRevisionsV1) GetProject() string {
	if f == nil {
		return ""
	}
	return f.Project
}

func (f *FeatureWithRevisionsV1) GetValueType() FeatureWithRevisionsV1ValueType {
	if f == nil {
		return FeatureWithRevisionsV1ValueType("")
	}
	return f.ValueType
}

func (f *FeatureWithRevisionsV1) GetDefaultValue() string {
	if f == nil {
		return ""
	}
	return f.DefaultValue
}

func (f *FeatureWithRevisionsV1) GetBaseConfig() optionalnullable.OptionalNullable[string] {
	if f == nil {
		return nil
	}
	return f.BaseConfig
}

func (f *FeatureWithRevisionsV1) GetDefaultValueConfig() optionalnullable.OptionalNullable[string] {
	if f == nil {
		return nil
	}
	return f.DefaultValueConfig
}

func (f *FeatureWithRevisionsV1) GetTags() []string {
	if f == nil {
		return []string{}
	}
	return f.Tags
}

func (f *FeatureWithRevisionsV1) GetEnvironments() map[string]FeatureEnvironmentV1 {
	if f == nil {
		return map[string]FeatureEnvironmentV1{}
	}
	return f.Environments
}

func (f *FeatureWithRevisionsV1) GetPrerequisites() []string {
	if f == nil {
		return nil
	}
	return f.Prerequisites
}

func (f *FeatureWithRevisionsV1) GetRevision() FeatureWithRevisionsV1Revision {
	if f == nil {
		return FeatureWithRevisionsV1Revision{}
	}
	return f.Revision
}

func (f *FeatureWithRevisionsV1) GetCustomFields() map[string]any {
	if f == nil {
		return nil
	}
	return f.CustomFields
}

func (f *FeatureWithRevisionsV1) GetHoldout() optionalnullable.OptionalNullable[FeatureWithRevisionsV1Holdout] {
	if f == nil {
		return nil
	}
	return f.Holdout
}

func (f *FeatureWithRevisionsV1) GetRevisions() []FeatureRevisionV1 {
	if f == nil {
		return nil
	}
	return f.Revisions
}

// #region class-body-featurewithrevisionsv1
// #endregion class-body-featurewithrevisionsv1
