// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/growthbook/cli/v2/internal/sdk/optionalnullable"
	"github.com/growthbook/cli/v2/internal/sdk/sdkinternal/utils"
	"time"
)

// HoldoutStage - Lifecycle stage of the Holdout. Use the start, start-analysis, and stop endpoints to move through the lifecycle.
type HoldoutStage string

const (
	HoldoutStageDraft          HoldoutStage = "draft"
	HoldoutStageRunning        HoldoutStage = "running"
	HoldoutStageAnalysisPeriod HoldoutStage = "analysis-period"
	HoldoutStageStopped        HoldoutStage = "stopped"
)

func (e HoldoutStage) ToPointer() *HoldoutStage {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *HoldoutStage) IsExact() bool {
	if e != nil {
		switch *e {
		case "draft", "running", "analysis-period", "stopped":
			return true
		}
	}
	return false
}

type HoldoutMatch string

const (
	HoldoutMatchAll  HoldoutMatch = "all"
	HoldoutMatchNone HoldoutMatch = "none"
	HoldoutMatchAny  HoldoutMatch = "any"
)

func (e HoldoutMatch) ToPointer() *HoldoutMatch {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *HoldoutMatch) IsExact() bool {
	if e != nil {
		switch *e {
		case "all", "none", "any":
			return true
		}
	}
	return false
}

type HoldoutSavedGroupTargeting struct {
	Match HoldoutMatch `json:"match"`
	Ids   []string     `json:"ids"`
}

func (h *HoldoutSavedGroupTargeting) GetMatch() HoldoutMatch {
	if h == nil {
		return HoldoutMatch("")
	}
	return h.Match
}

func (h *HoldoutSavedGroupTargeting) GetIds() []string {
	if h == nil {
		return []string{}
	}
	return h.Ids
}

// HoldoutStatsEngine - Statistics engine used to analyze this Holdout.
type HoldoutStatsEngine string

const (
	HoldoutStatsEngineBayesian    HoldoutStatsEngine = "bayesian"
	HoldoutStatsEngineFrequentist HoldoutStatsEngine = "frequentist"
)

func (e HoldoutStatsEngine) ToPointer() *HoldoutStatsEngine {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *HoldoutStatsEngine) IsExact() bool {
	if e != nil {
		switch *e {
		case "bayesian", "frequentist":
			return true
		}
	}
	return false
}

type HoldoutVariation struct {
	VariationID string  `json:"variationId"`
	Key         string  `json:"key"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitzero"`
}

func (h *HoldoutVariation) GetVariationID() string {
	if h == nil {
		return ""
	}
	return h.VariationID
}

func (h *HoldoutVariation) GetKey() string {
	if h == nil {
		return ""
	}
	return h.Key
}

func (h *HoldoutVariation) GetName() string {
	if h == nil {
		return ""
	}
	return h.Name
}

func (h *HoldoutVariation) GetDescription() *string {
	if h == nil {
		return nil
	}
	return h.Description
}

type Environments struct {
	// Whether the Holdout is active in this environment.
	Enabled bool `json:"enabled"`
}

func (e *Environments) GetEnabled() bool {
	if e == nil {
		return false
	}
	return e.Enabled
}

type LinkedFeature struct {
	ID        string    `json:"id"`
	DateAdded time.Time `json:"dateAdded"`
}

func (l LinkedFeature) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LinkedFeature) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *LinkedFeature) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *LinkedFeature) GetDateAdded() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.DateAdded
}

type LinkedExperiment struct {
	ID        string    `json:"id"`
	DateAdded time.Time `json:"dateAdded"`
}

func (l LinkedExperiment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LinkedExperiment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *LinkedExperiment) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *LinkedExperiment) GetDateAdded() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.DateAdded
}

// HoldoutStatusUpdateSchedule - Automatic stage transitions for the Holdout. Dates must be consecutive: `startAt` before `startAnalysisPeriodAt` before `stopAt`. Send `null` to delete the schedule.
type HoldoutStatusUpdateSchedule struct {
	// ISO datetime to move the Holdout from `draft` to `running`. Must be in the future while the Holdout is still a draft.
	StartAt *time.Time `json:"startAt,omitzero"`
	// ISO datetime to move the Holdout from `running` to `analysis-period`. Requires `startAt` while the Holdout is still a draft.
	StartAnalysisPeriodAt *time.Time `json:"startAnalysisPeriodAt,omitzero"`
	// ISO datetime to stop the Holdout. Requires `startAnalysisPeriodAt` unless the analysis period has already begun.
	StopAt *time.Time `json:"stopAt,omitzero"`
}

func (h HoldoutStatusUpdateSchedule) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HoldoutStatusUpdateSchedule) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *HoldoutStatusUpdateSchedule) GetStartAt() *time.Time {
	if h == nil {
		return nil
	}
	return h.StartAt
}

func (h *HoldoutStatusUpdateSchedule) GetStartAnalysisPeriodAt() *time.Time {
	if h == nil {
		return nil
	}
	return h.StartAnalysisPeriodAt
}

func (h *HoldoutStatusUpdateSchedule) GetStopAt() *time.Time {
	if h == nil {
		return nil
	}
	return h.StopAt
}

type HoldoutType string

const (
	HoldoutTypeStart               HoldoutType = "start"
	HoldoutTypeStartAnalysisPeriod HoldoutType = "startAnalysisPeriod"
	HoldoutTypeStop                HoldoutType = "stop"
)

func (e HoldoutType) ToPointer() *HoldoutType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *HoldoutType) IsExact() bool {
	if e != nil {
		switch *e {
		case "start", "startAnalysisPeriod", "stop":
			return true
		}
	}
	return false
}

// HoldoutNextScheduledStatusUpdate - The next stage transition that will run automatically.
type HoldoutNextScheduledStatusUpdate struct {
	Type HoldoutType `json:"type"`
	Date time.Time   `json:"date"`
}

func (h HoldoutNextScheduledStatusUpdate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HoldoutNextScheduledStatusUpdate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *HoldoutNextScheduledStatusUpdate) GetType() HoldoutType {
	if h == nil {
		return HoldoutType("")
	}
	return h.Type
}

func (h *HoldoutNextScheduledStatusUpdate) GetDate() time.Time {
	if h == nil {
		return time.Time{}
	}
	return h.Date
}

type Holdout struct {
	ID          string    `json:"id"`
	DateCreated time.Time `json:"dateCreated"`
	DateUpdated time.Time `json:"dateUpdated"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	// Project IDs this Holdout applies to. An empty array means All Projects.
	Projects []string `json:"projects"`
	// The userId of the owner (or raw owner name/email for legacy records)
	Owner string `json:"owner"`
	// The email address of the owner, when the owner can be resolved to a known user.
	OwnerEmail *string  `json:"ownerEmail,omitzero"`
	Tags       []string `json:"tags"`
	Archived   bool     `json:"archived"`
	// Lifecycle stage of the Holdout. Use the start, start-analysis, and stop endpoints to move through the lifecycle.
	Stage       HoldoutStage `json:"stage"`
	TrackingKey string       `json:"trackingKey"`
	// ID of the companion experiment that stores this Holdout's analysis. Use it with the experiment results endpoints (e.g. GET /experiments/{experimentId}/results). Pass phase=0 for results across the whole Holdout period, or phase=1 for results limited to the analysis period.
	ExperimentID string `json:"experimentId"`
	// When true, this Holdout is not selected automatically when creating Feature Flags or experiments in Projects assigned to the Holdout.
	SkipAsDefaultHoldout bool `json:"skipAsDefaultHoldout"`
	// Proportion of traffic placed in the holdout group (e.g. 0.05 for 5%). An equally sized comparison group is sampled from the remaining traffic for measurement, so 2× this value enters the holdout experiment in total. Must be greater than 0 and at most 0.5.
	HoldoutSize float64 `json:"holdoutSize"`
	// Attribute used to assign users to the Holdout.
	HashAttribute string `json:"hashAttribute"`
	// Targeting condition as a JSON string.
	TargetingCondition  string                       `json:"targetingCondition"`
	SavedGroupTargeting []HoldoutSavedGroupTargeting `json:"savedGroupTargeting,omitzero"`
	DatasourceID        string                       `json:"datasourceId"`
	AssignmentQueryID   string                       `json:"assignmentQueryId"`
	GoalMetrics         []string                     `json:"goalMetrics"`
	SecondaryMetrics    []string                     `json:"secondaryMetrics"`
	// Statistics engine used to analyze this Holdout.
	StatsEngine *HoldoutStatsEngine `json:"statsEngine,omitzero"`
	Variations  []HoldoutVariation  `json:"variations"`
	// Per-environment state, keyed by environment ID. Environments not present are disabled.
	Environments map[string]Environments `json:"environments"`
	// Feature Flags held out by this Holdout. Manage these through the Feature Flag endpoints.
	LinkedFeatures []LinkedFeature `json:"linkedFeatures"`
	// Experiments held out by this Holdout. Manage these through the experiment endpoints.
	LinkedExperiments []LinkedExperiment `json:"linkedExperiments"`
	DateStarted       *time.Time         `json:"dateStarted,omitzero"`
	// When the Holdout entered its analysis period.
	AnalysisStartDate         *time.Time                                                          `json:"analysisStartDate,omitzero"`
	DateStopped               *time.Time                                                          `json:"dateStopped,omitzero"`
	StatusUpdateSchedule      optionalnullable.OptionalNullable[HoldoutStatusUpdateSchedule]      `json:"statusUpdateSchedule,omitzero"`
	NextScheduledStatusUpdate optionalnullable.OptionalNullable[HoldoutNextScheduledStatusUpdate] `json:"nextScheduledStatusUpdate,omitzero"`
}

func (h Holdout) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *Holdout) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *Holdout) GetID() string {
	if h == nil {
		return ""
	}
	return h.ID
}

func (h *Holdout) GetDateCreated() time.Time {
	if h == nil {
		return time.Time{}
	}
	return h.DateCreated
}

func (h *Holdout) GetDateUpdated() time.Time {
	if h == nil {
		return time.Time{}
	}
	return h.DateUpdated
}

func (h *Holdout) GetName() string {
	if h == nil {
		return ""
	}
	return h.Name
}

func (h *Holdout) GetDescription() string {
	if h == nil {
		return ""
	}
	return h.Description
}

func (h *Holdout) GetProjects() []string {
	if h == nil {
		return []string{}
	}
	return h.Projects
}

func (h *Holdout) GetOwner() string {
	if h == nil {
		return ""
	}
	return h.Owner
}

func (h *Holdout) GetOwnerEmail() *string {
	if h == nil {
		return nil
	}
	return h.OwnerEmail
}

func (h *Holdout) GetTags() []string {
	if h == nil {
		return []string{}
	}
	return h.Tags
}

func (h *Holdout) GetArchived() bool {
	if h == nil {
		return false
	}
	return h.Archived
}

func (h *Holdout) GetStage() HoldoutStage {
	if h == nil {
		return HoldoutStage("")
	}
	return h.Stage
}

func (h *Holdout) GetTrackingKey() string {
	if h == nil {
		return ""
	}
	return h.TrackingKey
}

func (h *Holdout) GetExperimentID() string {
	if h == nil {
		return ""
	}
	return h.ExperimentID
}

func (h *Holdout) GetSkipAsDefaultHoldout() bool {
	if h == nil {
		return false
	}
	return h.SkipAsDefaultHoldout
}

func (h *Holdout) GetHoldoutSize() float64 {
	if h == nil {
		return 0.0
	}
	return h.HoldoutSize
}

func (h *Holdout) GetHashAttribute() string {
	if h == nil {
		return ""
	}
	return h.HashAttribute
}

func (h *Holdout) GetTargetingCondition() string {
	if h == nil {
		return ""
	}
	return h.TargetingCondition
}

func (h *Holdout) GetSavedGroupTargeting() []HoldoutSavedGroupTargeting {
	if h == nil {
		return nil
	}
	return h.SavedGroupTargeting
}

func (h *Holdout) GetDatasourceID() string {
	if h == nil {
		return ""
	}
	return h.DatasourceID
}

func (h *Holdout) GetAssignmentQueryID() string {
	if h == nil {
		return ""
	}
	return h.AssignmentQueryID
}

func (h *Holdout) GetGoalMetrics() []string {
	if h == nil {
		return []string{}
	}
	return h.GoalMetrics
}

func (h *Holdout) GetSecondaryMetrics() []string {
	if h == nil {
		return []string{}
	}
	return h.SecondaryMetrics
}

func (h *Holdout) GetStatsEngine() *HoldoutStatsEngine {
	if h == nil {
		return nil
	}
	return h.StatsEngine
}

func (h *Holdout) GetVariations() []HoldoutVariation {
	if h == nil {
		return []HoldoutVariation{}
	}
	return h.Variations
}

func (h *Holdout) GetEnvironments() map[string]Environments {
	if h == nil {
		return map[string]Environments{}
	}
	return h.Environments
}

func (h *Holdout) GetLinkedFeatures() []LinkedFeature {
	if h == nil {
		return []LinkedFeature{}
	}
	return h.LinkedFeatures
}

func (h *Holdout) GetLinkedExperiments() []LinkedExperiment {
	if h == nil {
		return []LinkedExperiment{}
	}
	return h.LinkedExperiments
}

func (h *Holdout) GetDateStarted() *time.Time {
	if h == nil {
		return nil
	}
	return h.DateStarted
}

func (h *Holdout) GetAnalysisStartDate() *time.Time {
	if h == nil {
		return nil
	}
	return h.AnalysisStartDate
}

func (h *Holdout) GetDateStopped() *time.Time {
	if h == nil {
		return nil
	}
	return h.DateStopped
}

func (h *Holdout) GetStatusUpdateSchedule() optionalnullable.OptionalNullable[HoldoutStatusUpdateSchedule] {
	if h == nil {
		return nil
	}
	return h.StatusUpdateSchedule
}

func (h *Holdout) GetNextScheduledStatusUpdate() optionalnullable.OptionalNullable[HoldoutNextScheduledStatusUpdate] {
	if h == nil {
		return nil
	}
	return h.NextScheduledStatusUpdate
}
