// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3eeae1494f27

package components

import (
	"github.com/growthbook/cli/internal/sdk/optionalnullable"
)

type MonitoringMonitoringMode string

const (
	MonitoringMonitoringModeAuto   MonitoringMonitoringMode = "auto"
	MonitoringMonitoringModeManual MonitoringMonitoringMode = "manual"
)

func (e MonitoringMonitoringMode) ToPointer() *MonitoringMonitoringMode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *MonitoringMonitoringMode) IsExact() bool {
	if e != nil {
		switch *e {
		case "auto", "manual":
			return true
		}
	}
	return false
}

type Monitoring struct {
	Enabled              bool                                      `json:"enabled"`
	MonitoringMode       MonitoringMonitoringMode                  `json:"monitoringMode"`
	AutoUpdate           bool                                      `json:"autoUpdate"`
	EffectiveAutoUpdate  bool                                      `json:"effectiveAutoUpdate"`
	BlockedReason        optionalnullable.OptionalNullable[string] `json:"blockedReason,omitzero"`
	CurrentStepMonitored bool                                      `json:"currentStepMonitored"`
	NextSnapshotAt       optionalnullable.OptionalNullable[string] `json:"nextSnapshotAt,omitzero"`
	// Internal ID of the linked monitoring experiment.
	SafeRolloutID optionalnullable.OptionalNullable[string] `json:"safeRolloutId,omitzero"`
}

func (m *Monitoring) GetEnabled() bool {
	if m == nil {
		return false
	}
	return m.Enabled
}

func (m *Monitoring) GetMonitoringMode() MonitoringMonitoringMode {
	if m == nil {
		return MonitoringMonitoringMode("")
	}
	return m.MonitoringMode
}

func (m *Monitoring) GetAutoUpdate() bool {
	if m == nil {
		return false
	}
	return m.AutoUpdate
}

func (m *Monitoring) GetEffectiveAutoUpdate() bool {
	if m == nil {
		return false
	}
	return m.EffectiveAutoUpdate
}

func (m *Monitoring) GetBlockedReason() optionalnullable.OptionalNullable[string] {
	if m == nil {
		return nil
	}
	return m.BlockedReason
}

func (m *Monitoring) GetCurrentStepMonitored() bool {
	if m == nil {
		return false
	}
	return m.CurrentStepMonitored
}

func (m *Monitoring) GetNextSnapshotAt() optionalnullable.OptionalNullable[string] {
	if m == nil {
		return nil
	}
	return m.NextSnapshotAt
}

func (m *Monitoring) GetSafeRolloutID() optionalnullable.OptionalNullable[string] {
	if m == nil {
		return nil
	}
	return m.SafeRolloutID
}
