// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6bfdd9583561

package components

type NamespaceStatus string

const (
	NamespaceStatusActive   NamespaceStatus = "active"
	NamespaceStatusInactive NamespaceStatus = "inactive"
)

func (e NamespaceStatus) ToPointer() *NamespaceStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *NamespaceStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "active", "inactive":
			return true
		}
	}
	return false
}

// NamespaceFormat - Namespace format. 'multiRange' supports multiple ranges per experiment and a configurable hash attribute.
type NamespaceFormat string

const (
	NamespaceFormatLegacy     NamespaceFormat = "legacy"
	NamespaceFormatMultiRange NamespaceFormat = "multiRange"
)

func (e NamespaceFormat) ToPointer() *NamespaceFormat {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *NamespaceFormat) IsExact() bool {
	if e != nil {
		switch *e {
		case "legacy", "multiRange":
			return true
		}
	}
	return false
}

type Namespace struct {
	// The unique internal identifier for the namespace (e.g. 'ns-abc123').
	ID string `json:"id"`
	// Human-readable display name.
	DisplayName string          `json:"displayName"`
	Description string          `json:"description"`
	Status      NamespaceStatus `json:"status"`
	// Namespace format. 'multiRange' supports multiple ranges per experiment and a configurable hash attribute.
	Format NamespaceFormat `json:"format"`
	// The user attribute used to assign bucket membership. Only present on multiRange namespaces.
	HashAttribute *string `json:"hashAttribute,omitzero"`
	// The seed used for bucket hashing. Changing this re-randomizes which traffic is eligible for which experiment. Use the rotateSeed endpoint to change it.
	Seed *string `json:"seed,omitzero"`
}

func (n *Namespace) GetID() string {
	if n == nil {
		return ""
	}
	return n.ID
}

func (n *Namespace) GetDisplayName() string {
	if n == nil {
		return ""
	}
	return n.DisplayName
}

func (n *Namespace) GetDescription() string {
	if n == nil {
		return ""
	}
	return n.Description
}

func (n *Namespace) GetStatus() NamespaceStatus {
	if n == nil {
		return NamespaceStatus("")
	}
	return n.Status
}

func (n *Namespace) GetFormat() NamespaceFormat {
	if n == nil {
		return NamespaceFormat("")
	}
	return n.Format
}

func (n *Namespace) GetHashAttribute() *string {
	if n == nil {
		return nil
	}
	return n.HashAttribute
}

func (n *Namespace) GetSeed() *string {
	if n == nil {
		return nil
	}
	return n.Seed
}
