// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/growthbook/cli/v2/internal/sdk/sdkinternal/utils"
)

type RequireReviewRuleInput struct {
	RequireReviewOn                 bool     `json:"requireReviewOn"`
	Projects                        []string `json:"projects,omitzero"`
	ResetReviewOnChange             *bool    `json:"resetReviewOnChange,omitzero"`
	Environments                    []string `json:"environments,omitzero"`
	FeatureRequireEnvironmentReview *bool    `json:"featureRequireEnvironmentReview,omitzero"`
	FeatureRequireMetadataReview    *bool    `json:"featureRequireMetadataReview,omitzero"`
	BlockSelfApproval               *bool    `json:"blockSelfApproval,omitzero"`
	AutopublishOnApproval           *bool    `json:"autopublishOnApproval,omitzero"`
	RequiredApproverTeams           []string `json:"requiredApproverTeams,omitzero"`
}

func (r RequireReviewRuleInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RequireReviewRuleInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RequireReviewRuleInput) GetRequireReviewOn() bool {
	if r == nil {
		return false
	}
	return r.RequireReviewOn
}

func (r *RequireReviewRuleInput) GetProjects() []string {
	if r == nil {
		return nil
	}
	return r.Projects
}

func (r *RequireReviewRuleInput) GetResetReviewOnChange() *bool {
	if r == nil {
		return nil
	}
	return r.ResetReviewOnChange
}

func (r *RequireReviewRuleInput) GetEnvironments() []string {
	if r == nil {
		return nil
	}
	return r.Environments
}

func (r *RequireReviewRuleInput) GetFeatureRequireEnvironmentReview() *bool {
	if r == nil {
		return nil
	}
	return r.FeatureRequireEnvironmentReview
}

func (r *RequireReviewRuleInput) GetFeatureRequireMetadataReview() *bool {
	if r == nil {
		return nil
	}
	return r.FeatureRequireMetadataReview
}

func (r *RequireReviewRuleInput) GetBlockSelfApproval() *bool {
	if r == nil {
		return nil
	}
	return r.BlockSelfApproval
}

func (r *RequireReviewRuleInput) GetAutopublishOnApproval() *bool {
	if r == nil {
		return nil
	}
	return r.AutopublishOnApproval
}

func (r *RequireReviewRuleInput) GetRequiredApproverTeams() []string {
	if r == nil {
		return nil
	}
	return r.RequiredApproverTeams
}
