// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
	"time"
)

type SavedGroupRevisionReviewDecision string

const (
	SavedGroupRevisionReviewDecisionApprove        SavedGroupRevisionReviewDecision = "approve"
	SavedGroupRevisionReviewDecisionRequestChanges SavedGroupRevisionReviewDecision = "request-changes"
	SavedGroupRevisionReviewDecisionComment        SavedGroupRevisionReviewDecision = "comment"
)

func (e SavedGroupRevisionReviewDecision) ToPointer() *SavedGroupRevisionReviewDecision {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SavedGroupRevisionReviewDecision) IsExact() bool {
	if e != nil {
		switch *e {
		case "approve", "request-changes", "comment":
			return true
		}
	}
	return false
}

type SavedGroupRevisionReview struct {
	ID       string                           `json:"id"`
	UserID   string                           `json:"userId"`
	Decision SavedGroupRevisionReviewDecision `json:"decision"`
	Comment  *string                          `json:"comment,omitzero"`
	// True if a later review cycle (re-submit, approval reset, recall, or reopen) superseded this verdict. Stale verdicts are kept for attribution but no longer count as an active approval or change-request.
	Stale       *bool     `json:"stale,omitzero"`
	DateCreated time.Time `json:"dateCreated"`
}

func (s SavedGroupRevisionReview) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SavedGroupRevisionReview) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SavedGroupRevisionReview) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SavedGroupRevisionReview) GetUserID() string {
	if s == nil {
		return ""
	}
	return s.UserID
}

func (s *SavedGroupRevisionReview) GetDecision() SavedGroupRevisionReviewDecision {
	if s == nil {
		return SavedGroupRevisionReviewDecision("")
	}
	return s.Decision
}

func (s *SavedGroupRevisionReview) GetComment() *string {
	if s == nil {
		return nil
	}
	return s.Comment
}

func (s *SavedGroupRevisionReview) GetStale() *bool {
	if s == nil {
		return nil
	}
	return s.Stale
}

func (s *SavedGroupRevisionReview) GetDateCreated() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.DateCreated
}
