// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/growthbook/cli/v2/internal/sdk/sdkinternal/utils"
)

type SavedGroupRevisionRef struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	entityType string `const:"saved-group" json:"entityType"`
	// Saved Group id.
	ID string `json:"id"`
	// Revision version to publish.
	Version int64 `json:"version"`
}

func (s SavedGroupRevisionRef) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SavedGroupRevisionRef) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SavedGroupRevisionRef) GetEntityType() string {
	return "saved-group"
}

func (s *SavedGroupRevisionRef) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SavedGroupRevisionRef) GetVersion() int64 {
	if s == nil {
		return 0
	}
	return s.Version
}
