// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/growthbook/cli/internal/sdk/sdkinternal/utils"
	"time"
)

type SavedGroupRevisionStatus string

const (
	SavedGroupRevisionStatusDraft            SavedGroupRevisionStatus = "draft"
	SavedGroupRevisionStatusPendingReview    SavedGroupRevisionStatus = "pending-review"
	SavedGroupRevisionStatusApproved         SavedGroupRevisionStatus = "approved"
	SavedGroupRevisionStatusChangesRequested SavedGroupRevisionStatus = "changes-requested"
	SavedGroupRevisionStatusMerged           SavedGroupRevisionStatus = "merged"
	SavedGroupRevisionStatusDiscarded        SavedGroupRevisionStatus = "discarded"
)

func (e SavedGroupRevisionStatus) ToPointer() *SavedGroupRevisionStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SavedGroupRevisionStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "draft", "pending-review", "approved", "changes-requested", "merged", "discarded":
			return true
		}
	}
	return false
}

type SavedGroupRevisionAction string

const (
	SavedGroupRevisionActionMerged    SavedGroupRevisionAction = "merged"
	SavedGroupRevisionActionDiscarded SavedGroupRevisionAction = "discarded"
)

func (e SavedGroupRevisionAction) ToPointer() *SavedGroupRevisionAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SavedGroupRevisionAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "merged", "discarded":
			return true
		}
	}
	return false
}

type SavedGroupRevisionResolution struct {
	Action      SavedGroupRevisionAction `json:"action"`
	UserID      string                   `json:"userId"`
	DateCreated time.Time                `json:"dateCreated"`
}

func (s SavedGroupRevisionResolution) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SavedGroupRevisionResolution) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SavedGroupRevisionResolution) GetAction() SavedGroupRevisionAction {
	if s == nil {
		return SavedGroupRevisionAction("")
	}
	return s.Action
}

func (s *SavedGroupRevisionResolution) GetUserID() string {
	if s == nil {
		return ""
	}
	return s.UserID
}

func (s *SavedGroupRevisionResolution) GetDateCreated() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.DateCreated
}

type SavedGroupRevisionProposedChangeTest struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	op    string `const:"test" json:"op"`
	Path  string `json:"path"`
	Value any    `json:"value"`
}

func (s SavedGroupRevisionProposedChangeTest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SavedGroupRevisionProposedChangeTest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SavedGroupRevisionProposedChangeTest) GetOp() string {
	return "test"
}

func (s *SavedGroupRevisionProposedChangeTest) GetPath() string {
	if s == nil {
		return ""
	}
	return s.Path
}

func (s *SavedGroupRevisionProposedChangeTest) GetValue() any {
	if s == nil {
		return nil
	}
	return s.Value
}

type SavedGroupRevisionProposedChangeCopy struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	op   string `const:"copy" json:"op"`
	From string `json:"from"`
	Path string `json:"path"`
}

func (s SavedGroupRevisionProposedChangeCopy) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SavedGroupRevisionProposedChangeCopy) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SavedGroupRevisionProposedChangeCopy) GetOp() string {
	return "copy"
}

func (s *SavedGroupRevisionProposedChangeCopy) GetFrom() string {
	if s == nil {
		return ""
	}
	return s.From
}

func (s *SavedGroupRevisionProposedChangeCopy) GetPath() string {
	if s == nil {
		return ""
	}
	return s.Path
}

type SavedGroupRevisionProposedChangeMove struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	op   string `const:"move" json:"op"`
	From string `json:"from"`
	Path string `json:"path"`
}

func (s SavedGroupRevisionProposedChangeMove) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SavedGroupRevisionProposedChangeMove) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SavedGroupRevisionProposedChangeMove) GetOp() string {
	return "move"
}

func (s *SavedGroupRevisionProposedChangeMove) GetFrom() string {
	if s == nil {
		return ""
	}
	return s.From
}

func (s *SavedGroupRevisionProposedChangeMove) GetPath() string {
	if s == nil {
		return ""
	}
	return s.Path
}

type SavedGroupRevisionProposedChangeReplace struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	op    string `const:"replace" json:"op"`
	Path  string `json:"path"`
	Value any    `json:"value"`
}

func (s SavedGroupRevisionProposedChangeReplace) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SavedGroupRevisionProposedChangeReplace) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SavedGroupRevisionProposedChangeReplace) GetOp() string {
	return "replace"
}

func (s *SavedGroupRevisionProposedChangeReplace) GetPath() string {
	if s == nil {
		return ""
	}
	return s.Path
}

func (s *SavedGroupRevisionProposedChangeReplace) GetValue() any {
	if s == nil {
		return nil
	}
	return s.Value
}

type SavedGroupRevisionProposedChangeRemove struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	op   string `const:"remove" json:"op"`
	Path string `json:"path"`
}

func (s SavedGroupRevisionProposedChangeRemove) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SavedGroupRevisionProposedChangeRemove) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SavedGroupRevisionProposedChangeRemove) GetOp() string {
	return "remove"
}

func (s *SavedGroupRevisionProposedChangeRemove) GetPath() string {
	if s == nil {
		return ""
	}
	return s.Path
}

type SavedGroupRevisionProposedChangeAdd struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	op    string `const:"add" json:"op"`
	Path  string `json:"path"`
	Value any    `json:"value"`
}

func (s SavedGroupRevisionProposedChangeAdd) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SavedGroupRevisionProposedChangeAdd) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SavedGroupRevisionProposedChangeAdd) GetOp() string {
	return "add"
}

func (s *SavedGroupRevisionProposedChangeAdd) GetPath() string {
	if s == nil {
		return ""
	}
	return s.Path
}

func (s *SavedGroupRevisionProposedChangeAdd) GetValue() any {
	if s == nil {
		return nil
	}
	return s.Value
}

type SavedGroupRevisionProposedChangeUnionType string

const (
	SavedGroupRevisionProposedChangeUnionTypeAdd     SavedGroupRevisionProposedChangeUnionType = "add"
	SavedGroupRevisionProposedChangeUnionTypeRemove  SavedGroupRevisionProposedChangeUnionType = "remove"
	SavedGroupRevisionProposedChangeUnionTypeReplace SavedGroupRevisionProposedChangeUnionType = "replace"
	SavedGroupRevisionProposedChangeUnionTypeMove    SavedGroupRevisionProposedChangeUnionType = "move"
	SavedGroupRevisionProposedChangeUnionTypeCopy    SavedGroupRevisionProposedChangeUnionType = "copy"
	SavedGroupRevisionProposedChangeUnionTypeTest    SavedGroupRevisionProposedChangeUnionType = "test"
	SavedGroupRevisionProposedChangeUnionTypeUnknown SavedGroupRevisionProposedChangeUnionType = "UNKNOWN"
)

type SavedGroupRevisionProposedChangeUnion struct {
	SavedGroupRevisionProposedChangeAdd     *SavedGroupRevisionProposedChangeAdd     `queryParam:"inline" union:"member"`
	SavedGroupRevisionProposedChangeRemove  *SavedGroupRevisionProposedChangeRemove  `queryParam:"inline" union:"member"`
	SavedGroupRevisionProposedChangeReplace *SavedGroupRevisionProposedChangeReplace `queryParam:"inline" union:"member"`
	SavedGroupRevisionProposedChangeMove    *SavedGroupRevisionProposedChangeMove    `queryParam:"inline" union:"member"`
	SavedGroupRevisionProposedChangeCopy    *SavedGroupRevisionProposedChangeCopy    `queryParam:"inline" union:"member"`
	SavedGroupRevisionProposedChangeTest    *SavedGroupRevisionProposedChangeTest    `queryParam:"inline" union:"member"`
	UnknownRaw                              json.RawMessage                          `json:"-" union:"unknown"`

	Type SavedGroupRevisionProposedChangeUnionType
}

func CreateSavedGroupRevisionProposedChangeUnionAdd(add SavedGroupRevisionProposedChangeAdd) SavedGroupRevisionProposedChangeUnion {
	typ := SavedGroupRevisionProposedChangeUnionTypeAdd

	return SavedGroupRevisionProposedChangeUnion{
		SavedGroupRevisionProposedChangeAdd: &add,
		Type:                                typ,
	}
}

func CreateSavedGroupRevisionProposedChangeUnionRemove(remove SavedGroupRevisionProposedChangeRemove) SavedGroupRevisionProposedChangeUnion {
	typ := SavedGroupRevisionProposedChangeUnionTypeRemove

	return SavedGroupRevisionProposedChangeUnion{
		SavedGroupRevisionProposedChangeRemove: &remove,
		Type:                                   typ,
	}
}

func CreateSavedGroupRevisionProposedChangeUnionReplace(replace SavedGroupRevisionProposedChangeReplace) SavedGroupRevisionProposedChangeUnion {
	typ := SavedGroupRevisionProposedChangeUnionTypeReplace

	return SavedGroupRevisionProposedChangeUnion{
		SavedGroupRevisionProposedChangeReplace: &replace,
		Type:                                    typ,
	}
}

func CreateSavedGroupRevisionProposedChangeUnionMove(move SavedGroupRevisionProposedChangeMove) SavedGroupRevisionProposedChangeUnion {
	typ := SavedGroupRevisionProposedChangeUnionTypeMove

	return SavedGroupRevisionProposedChangeUnion{
		SavedGroupRevisionProposedChangeMove: &move,
		Type:                                 typ,
	}
}

func CreateSavedGroupRevisionProposedChangeUnionCopy(copy SavedGroupRevisionProposedChangeCopy) SavedGroupRevisionProposedChangeUnion {
	typ := SavedGroupRevisionProposedChangeUnionTypeCopy

	return SavedGroupRevisionProposedChangeUnion{
		SavedGroupRevisionProposedChangeCopy: &copy,
		Type:                                 typ,
	}
}

func CreateSavedGroupRevisionProposedChangeUnionTest(test SavedGroupRevisionProposedChangeTest) SavedGroupRevisionProposedChangeUnion {
	typ := SavedGroupRevisionProposedChangeUnionTypeTest

	return SavedGroupRevisionProposedChangeUnion{
		SavedGroupRevisionProposedChangeTest: &test,
		Type:                                 typ,
	}
}

func CreateSavedGroupRevisionProposedChangeUnionUnknown(raw json.RawMessage) SavedGroupRevisionProposedChangeUnion {
	return SavedGroupRevisionProposedChangeUnion{
		UnknownRaw: raw,
		Type:       SavedGroupRevisionProposedChangeUnionTypeUnknown,
	}
}

func (u SavedGroupRevisionProposedChangeUnion) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u SavedGroupRevisionProposedChangeUnion) IsUnknown() bool {
	return u.Type == SavedGroupRevisionProposedChangeUnionTypeUnknown
}

func (u *SavedGroupRevisionProposedChangeUnion) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Op string `json:"op"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = SavedGroupRevisionProposedChangeUnionTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = SavedGroupRevisionProposedChangeUnionTypeUnknown
		return nil
	}

	switch dis.Op {
	case "add":
		savedGroupRevisionProposedChangeAdd := new(SavedGroupRevisionProposedChangeAdd)
		if err := utils.UnmarshalJSON(data, &savedGroupRevisionProposedChangeAdd, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Op == add) type SavedGroupRevisionProposedChangeAdd within SavedGroupRevisionProposedChangeUnion: %w", string(data), err)
		}

		u.SavedGroupRevisionProposedChangeAdd = savedGroupRevisionProposedChangeAdd
		u.Type = SavedGroupRevisionProposedChangeUnionTypeAdd
		return nil
	case "remove":
		savedGroupRevisionProposedChangeRemove := new(SavedGroupRevisionProposedChangeRemove)
		if err := utils.UnmarshalJSON(data, &savedGroupRevisionProposedChangeRemove, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Op == remove) type SavedGroupRevisionProposedChangeRemove within SavedGroupRevisionProposedChangeUnion: %w", string(data), err)
		}

		u.SavedGroupRevisionProposedChangeRemove = savedGroupRevisionProposedChangeRemove
		u.Type = SavedGroupRevisionProposedChangeUnionTypeRemove
		return nil
	case "replace":
		savedGroupRevisionProposedChangeReplace := new(SavedGroupRevisionProposedChangeReplace)
		if err := utils.UnmarshalJSON(data, &savedGroupRevisionProposedChangeReplace, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Op == replace) type SavedGroupRevisionProposedChangeReplace within SavedGroupRevisionProposedChangeUnion: %w", string(data), err)
		}

		u.SavedGroupRevisionProposedChangeReplace = savedGroupRevisionProposedChangeReplace
		u.Type = SavedGroupRevisionProposedChangeUnionTypeReplace
		return nil
	case "move":
		savedGroupRevisionProposedChangeMove := new(SavedGroupRevisionProposedChangeMove)
		if err := utils.UnmarshalJSON(data, &savedGroupRevisionProposedChangeMove, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Op == move) type SavedGroupRevisionProposedChangeMove within SavedGroupRevisionProposedChangeUnion: %w", string(data), err)
		}

		u.SavedGroupRevisionProposedChangeMove = savedGroupRevisionProposedChangeMove
		u.Type = SavedGroupRevisionProposedChangeUnionTypeMove
		return nil
	case "copy":
		savedGroupRevisionProposedChangeCopy := new(SavedGroupRevisionProposedChangeCopy)
		if err := utils.UnmarshalJSON(data, &savedGroupRevisionProposedChangeCopy, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Op == copy) type SavedGroupRevisionProposedChangeCopy within SavedGroupRevisionProposedChangeUnion: %w", string(data), err)
		}

		u.SavedGroupRevisionProposedChangeCopy = savedGroupRevisionProposedChangeCopy
		u.Type = SavedGroupRevisionProposedChangeUnionTypeCopy
		return nil
	case "test":
		savedGroupRevisionProposedChangeTest := new(SavedGroupRevisionProposedChangeTest)
		if err := utils.UnmarshalJSON(data, &savedGroupRevisionProposedChangeTest, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Op == test) type SavedGroupRevisionProposedChangeTest within SavedGroupRevisionProposedChangeUnion: %w", string(data), err)
		}

		u.SavedGroupRevisionProposedChangeTest = savedGroupRevisionProposedChangeTest
		u.Type = SavedGroupRevisionProposedChangeUnionTypeTest
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = SavedGroupRevisionProposedChangeUnionTypeUnknown
		return nil
	}

}

func (u SavedGroupRevisionProposedChangeUnion) MarshalJSON() ([]byte, error) {
	if u.SavedGroupRevisionProposedChangeAdd != nil {
		return utils.MarshalJSON(u.SavedGroupRevisionProposedChangeAdd, "", true)
	}

	if u.SavedGroupRevisionProposedChangeRemove != nil {
		return utils.MarshalJSON(u.SavedGroupRevisionProposedChangeRemove, "", true)
	}

	if u.SavedGroupRevisionProposedChangeReplace != nil {
		return utils.MarshalJSON(u.SavedGroupRevisionProposedChangeReplace, "", true)
	}

	if u.SavedGroupRevisionProposedChangeMove != nil {
		return utils.MarshalJSON(u.SavedGroupRevisionProposedChangeMove, "", true)
	}

	if u.SavedGroupRevisionProposedChangeCopy != nil {
		return utils.MarshalJSON(u.SavedGroupRevisionProposedChangeCopy, "", true)
	}

	if u.SavedGroupRevisionProposedChangeTest != nil {
		return utils.MarshalJSON(u.SavedGroupRevisionProposedChangeTest, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type SavedGroupRevisionProposedChangeUnion: all fields are null")
}

type SavedGroupRevision struct {
	ID                 string                                  `json:"id"`
	Version            *int64                                  `json:"version,omitzero"`
	Title              *string                                 `json:"title,omitzero"`
	Status             SavedGroupRevisionStatus                `json:"status"`
	AuthorID           string                                  `json:"authorId"`
	AuthorEmail        *string                                 `json:"authorEmail,omitzero"`
	Contributors       []string                                `json:"contributors,omitzero"`
	RevertedFrom       *string                                 `json:"revertedFrom,omitzero"`
	Reviews            []SavedGroupRevisionReview              `json:"reviews"`
	ActivityLog        []SavedGroupRevisionActivityLogEntry    `json:"activityLog"`
	Resolution         *SavedGroupRevisionResolution           `json:"resolution,omitzero"`
	DateCreated        time.Time                               `json:"dateCreated"`
	DateUpdated        time.Time                               `json:"dateUpdated"`
	BaseSavedGroup     SavedGroup                              `json:"baseSavedGroup"`
	ProposedSavedGroup SavedGroup                              `json:"proposedSavedGroup"`
	ProposedChanges    []SavedGroupRevisionProposedChangeUnion `json:"proposedChanges"`
}

func (s SavedGroupRevision) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SavedGroupRevision) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SavedGroupRevision) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SavedGroupRevision) GetVersion() *int64 {
	if s == nil {
		return nil
	}
	return s.Version
}

func (s *SavedGroupRevision) GetTitle() *string {
	if s == nil {
		return nil
	}
	return s.Title
}

func (s *SavedGroupRevision) GetStatus() SavedGroupRevisionStatus {
	if s == nil {
		return SavedGroupRevisionStatus("")
	}
	return s.Status
}

func (s *SavedGroupRevision) GetAuthorID() string {
	if s == nil {
		return ""
	}
	return s.AuthorID
}

func (s *SavedGroupRevision) GetAuthorEmail() *string {
	if s == nil {
		return nil
	}
	return s.AuthorEmail
}

func (s *SavedGroupRevision) GetContributors() []string {
	if s == nil {
		return nil
	}
	return s.Contributors
}

func (s *SavedGroupRevision) GetRevertedFrom() *string {
	if s == nil {
		return nil
	}
	return s.RevertedFrom
}

func (s *SavedGroupRevision) GetReviews() []SavedGroupRevisionReview {
	if s == nil {
		return []SavedGroupRevisionReview{}
	}
	return s.Reviews
}

func (s *SavedGroupRevision) GetActivityLog() []SavedGroupRevisionActivityLogEntry {
	if s == nil {
		return []SavedGroupRevisionActivityLogEntry{}
	}
	return s.ActivityLog
}

func (s *SavedGroupRevision) GetResolution() *SavedGroupRevisionResolution {
	if s == nil {
		return nil
	}
	return s.Resolution
}

func (s *SavedGroupRevision) GetDateCreated() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.DateCreated
}

func (s *SavedGroupRevision) GetDateUpdated() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.DateUpdated
}

func (s *SavedGroupRevision) GetBaseSavedGroup() SavedGroup {
	if s == nil {
		return SavedGroup{}
	}
	return s.BaseSavedGroup
}

func (s *SavedGroupRevision) GetProposedSavedGroup() SavedGroup {
	if s == nil {
		return SavedGroup{}
	}
	return s.ProposedSavedGroup
}

func (s *SavedGroupRevision) GetProposedChanges() []SavedGroupRevisionProposedChangeUnion {
	if s == nil {
		return []SavedGroupRevisionProposedChangeUnion{}
	}
	return s.ProposedChanges
}
