// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package configs

import (
	"fmt"
	"github.com/growthbook/cli/internal/client"
	"github.com/growthbook/cli/internal/flagutil"
	"github.com/growthbook/cli/internal/interactive"
	"github.com/growthbook/cli/internal/output"
	"github.com/growthbook/cli/internal/sdk"
	"github.com/growthbook/cli/internal/sdk/models/operations"
	"github.com/growthbook/cli/internal/usage"
	"github.com/spf13/cobra"
)

var verifyConfigSchemaCmdMeta = []flagutil.FlagMeta{
	{FlagName: "key", Shorthand: "k", FieldPath: "Key", Kind: flagutil.FlagKindString, Required: true, Description: "The key of the config [required]"},
	{FlagName: "schema", Shorthand: "s", FieldPath: "Body.Schema", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: true, DiscriminatorKey: "Type", TypeDescription: "JSON value (variants: json-schema: { value: object }, typescript: { value: string }, protobuf: { value: string }, python: { value: string }, go: { value: string }, rust: { value: string })", Variants: []flagutil.UnionVariantMeta{
		{DiscriminatorValue: "json-schema", FlagName: "schema.json-schema", FieldName: "ConfigSchemaSourceJSONSchema", CanExpand: false, Description: "ConfigSchemaSource_JSONSchema variant as JSON"},
		{DiscriminatorValue: "typescript", FlagName: "schema.typescript", FieldName: "ConfigSchemaSourceTypescript", CanExpand: true, Description: "ConfigSchemaSource_Typescript variant as JSON", Fields: []flagutil.FlagMeta{
			{FlagName: "schema.typescript.value", FieldPath: "Value", Kind: flagutil.FlagKindString, Required: true, Description: "TypeScript source — an interface or object type. [required]"},
		}},
		{DiscriminatorValue: "protobuf", FlagName: "schema.protobuf", FieldName: "ConfigSchemaSourceProtobuf", CanExpand: true, Description: "ConfigSchemaSource_Protobuf variant as JSON", Fields: []flagutil.FlagMeta{
			{FlagName: "schema.protobuf.value", FieldPath: "Value", Kind: flagutil.FlagKindString, Required: true, Description: "Protobuf (proto3) source — a `message` definition. [required]"},
		}},
		{DiscriminatorValue: "python", FlagName: "schema.python", FieldName: "ConfigSchemaSourcePython", CanExpand: true, Description: "ConfigSchemaSource_Python variant as JSON", Fields: []flagutil.FlagMeta{
			{FlagName: "schema.python.value", FieldPath: "Value", Kind: flagutil.FlagKindString, Required: true, Description: "Python source — a Pydantic `BaseModel` class. [required]"},
		}},
		{DiscriminatorValue: "go", FlagName: "schema.go", FieldName: "ConfigSchemaSourceGo", CanExpand: true, Description: "ConfigSchemaSource_Go variant as JSON", Fields: []flagutil.FlagMeta{
			{FlagName: "schema.go.value", FieldPath: "Value", Kind: flagutil.FlagKindString, Required: true, Description: "Go source — a `struct` definition. [required]"},
		}},
		{DiscriminatorValue: "rust", FlagName: "schema.rust", FieldName: "ConfigSchemaSourceRust", CanExpand: true, Description: "ConfigSchemaSource_Rust variant as JSON", Fields: []flagutil.FlagMeta{
			{FlagName: "schema.rust.value", FieldPath: "Value", Kind: flagutil.FlagKindString, Required: true, Description: "Rust source — a serde `struct` definition. [required]"},
		}},
	}}},
}

// initVerifyConfigSchemaCmd initializes the verify-config-schema command.
func initVerifyConfigSchemaCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "verify-config-schema",
		Short:   "Verify a config's schema against a source (drift check)",
		Long:    "Verify a config's schema against a source (drift check)",
		Example: "  growthbook configs verify-config-schema --key <key> --schema '{\"type\":\"typescript\",\"value\":\"<value>\"}'",
		RunE:    runVerifyConfigSchemaCmd,
		Aliases: []string{"vcs"},
	}
	flagutil.RegisterFlags(cmd, verifyConfigSchemaCmdMeta)
	if err := flagutil.ValidateMeta[operations.VerifyConfigSchemaRequest](verifyConfigSchemaCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for verify-config-schema: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runVerifyConfigSchemaCmd executes the verify-config-schema command.
func runVerifyConfigSchemaCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, verifyConfigSchemaCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, verifyConfigSchemaCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.VerifyConfigSchemaRequest](cmd, verifyConfigSchemaCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Configs.VerifyConfigSchema(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
